version: '3.8'

configs:
  nginx_conf:
    file: './nginx.conf'
  dsp_rules:
    file: '../../dsp_rules.json'
  spp_rules:
    file: '../../spp_rules.json'
  ssl_fullchain:
    file: './ssl-certs/fullchain.pem'
  ssl_privkey:
    file: './ssl-certs/privkey.pem'

volumes:
  redis_data:
  kafka_data:
  nginx_logs:

services:
  mock-dsp-1:
    image: localhost:5000/rtb/mock-dsp-1:local
    hostname: mock-dsp-1
    ports:
      - target: 8090
        published: 8090
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    env_file:
      - env/mock-dsp-1.env

  mock-dsp-2:
    image: localhost:5000/rtb/mock-dsp-2:local
    hostname: mock-dsp-2
    ports:
      - target: 8091
        published: 8091
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    env_file:
      - env/mock-dsp-2.env

  mock-dsp-3:
    image: localhost:5000/rtb/mock-dsp-3:local
    hostname: mock-dsp-3
    ports:
      - target: 8092
        published: 8092
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    env_file:
      - env/mock-dsp-3.env

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - target: 6379
        published: 6379
        mode: host
    env_file:
      - env/redis.env
    command: ["sh", "-c", "redis-server --requirepass \"$${REDIS_PASSWORD}\""]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      endpoint_mode: dnsrr

  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    ports:
      - target: 9092
        published: 9092
        mode: host
    env_file:
      - env/kafka.env
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  bid-engine:
    image: ${BID_ENGINE_IMAGE:-localhost:5000/rtb/bid-engine:local}
    env_file:
      - env/bid-engine.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.rtb_latency == true
    depends_on:
      - redis

  router:
    image: ${ROUTER_IMAGE:-localhost:5000/rtb/router:local}
    env_file:
      - env/router.env
    configs:
      - source: dsp_rules
        target: /dsp_rules.json
      - source: spp_rules
        target: /spp_rules.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.rtb_latency == true
    depends_on:
      - redis

  orchestrator:
    image: ${ORCHESTRATOR_IMAGE:-localhost:5000/rtb/orchestrator:local}
    env_file:
      - env/orchestrator.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.rtb_latency == true
    depends_on:
      - redis
      - bid-engine
      - router

  spp-adapter:
    image: ${SPP_ADAPTER_IMAGE:-localhost:5000/rtb/spp-adapter:local}
    env_file:
      - env/spp-adapter.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      placement:
        constraints:
          - node.labels.rtb_latency == true
    depends_on:
      - redis
      - orchestrator

  kafka-loader:
    image: ${KAFKA_LOADER_IMAGE:-localhost:5000/rtb/kafka-loader:local}
    env_file:
      - env/kafka-loader.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - kafka

  clickhouse-loader:
    image: ${CLICKHOUSE_LOADER_IMAGE:-localhost:5000/rtb/clickhouse-loader:local}
    env_file:
      - env/clickhouse-loader.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - kafka

  nginx-gateway:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8083
        published: 8083
        mode: host
      - target: 8084
        published: 8084
        mode: host
      - target: 8085
        published: 8085
        mode: host
      - target: 8087
        published: 8087
        mode: host
      - target: 8088
        published: 8088
        mode: host
    volumes:
      - nginx_logs:/var/log/nginx
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: ssl_fullchain
        target: /etc/ssl/fullchain.pem
      - source: ssl_privkey
        target: /etc/ssl/privkey.pem
    command: ["nginx", "-g", "daemon off;"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      placement:
        constraints:
          - node.labels.rtb_latency == true
    depends_on:
      - redis
      - kafka
      - bid-engine
      - orchestrator
      - router
      - spp-adapter
      - kafka-loader
      - clickhouse-loader
