version: '3.8'

configs:
  nginx_conf:
    file: './nginx.conf'
  dsp_rules:
    file: '../../dsp_rules.json'
  spp_rules:
    file: '../../spp_rules.json'
  ssl_fullchain:
    file: './ssl-certs/fullchain.pem'
  ssl_privkey:
    file: './ssl-certs/privkey.pem'

volumes:
  redis_data:
  kafka_data:

services:
  redis:
    image: redis:7-alpine
    hostname: redis
    env_file:
      - env/redis.env
    command: ["sh", "-c", "redis-server --requirepass \"$${REDIS_PASSWORD}\""]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    env_file:
      - env/kafka.env
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  mock-dsp-1:
    image: ${MOCK_DSP_IMAGE:-localhost:5000/rtb/mock-dsp:local}
    env_file:
      - env/mock-dsp1.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mock-dsp-2:
    image: ${MOCK_DSP_IMAGE:-localhost:5000/rtb/mock-dsp:local}
    env_file:
      - env/mock-dsp2.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mock-dsp-3:
    image: ${MOCK_DSP_IMAGE:-localhost:5000/rtb/mock-dsp:local}
    env_file:
      - env/mock-dsp3.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  bid-engine:
    image: ${BID_ENGINE_IMAGE:-localhost:5000/rtb/bid-engine:local}
    env_file:
      - env/bid-engine.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis

  router:
    image: ${ROUTER_IMAGE:-localhost:5000/rtb/router:local}
    env_file:
      - env/router.env
    configs:
      - source: dsp_rules
        target: /dsp_rules.json
      - source: spp_rules
        target: /spp_rules.json
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - mock-dsp-1
      - mock-dsp-2
      - mock-dsp-3

  orchestrator:
    image: ${ORCHESTRATOR_IMAGE:-localhost:5000/rtb/orchestrator:local}
    env_file:
      - env/orchestrator.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - bid-engine
      - router

  spp-adapter:
    image: ${SPP_ADAPTER_IMAGE:-localhost:5000/rtb/spp-adapter:local}
    env_file:
      - env/spp-adapter.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - orchestrator

  kafka-loader:
    image: ${KAFKA_LOADER_IMAGE:-localhost:5000/rtb/kafka-loader:local}
    env_file:
      - env/kafka-loader.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - kafka

  clickhouse-loader:
    image: ${CLICKHOUSE_LOADER_IMAGE:-localhost:5000/rtb/clickhouse-loader:local}
    env_file:
      - env/clickhouse-loader.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - kafka

  nginx-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "9092:9092"
      - "6379:6379"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8087:8087"
      - "8088:8088"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: ssl_fullchain
        target: /etc/ssl/fullchain.pem
      - source: ssl_privkey
        target: /etc/ssl/privkey.pem
    command: ["nginx", "-g", "daemon off;"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    depends_on:
      - redis
      - kafka
      - bid-engine
      - orchestrator
      - router
      - spp-adapter
      - kafka-loader
      - clickhouse-loader
