syntax = "proto3";
package adv;
option go_package = "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/adv;advGrpc";

import "types/ortb_V2_5/ortb.proto";

service AdvService {
  rpc DoAuction(DoAuctionRequest) returns (DoAuctionResponse) {};
}

message DoAuctionRequest {
  ortb_V2_5.BidRequest bidRequest = 1;
  string format = 2;
  string traffic_type = 3;
  string ssp_domain = 4;
  map<string, string> impIdUuid = 5;
  reserved 6;
  reserved "feed";
}

message DoAuctionResponse {
  reserved 1, 6;
  reserved "selected", "code";

  string campaign_id = 2;
  string creative_id = 3;
  string adm = 4;
  double auction_price = 5;
  ortb_V2_5.BidResponse bid_response = 7;
  map<string, string> winnerUserIds = 8;
}
