syntax = "proto3";
package bidEngine;
option go_package = "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/bidEngine;bidEngineGrpc";

import "types/ortb_V2_5/ortb.proto";
import "google/protobuf/empty.proto";

service BidEngineService {
  rpc getWinnerBid_V2_5(BidEngineRequest_V2_5) returns (BidEngineResponse_V2_5) {};
  rpc ChangeSspGeoPercentsMap(SspGeoPercentsRequest_V2_5) returns (google.protobuf.Empty);
}

message BidEngineRequest_V2_5 {
  ortb_V2_5.BidRequest bidRequest = 1;
  map<string, ortb_V2_5.BidResponse> bidResponses = 2;
  string globalId = 3;
  string ssp_domain = 4;
}

message BidEngineResponse_V2_5 {
  ortb_V2_5.BidResponse bidResponse = 1;
  string globalId = 2;
}

message SspGeoPercentsRequest_V2_5 {
  map<string, MapStringToFloat> changes = 1;
}

message MapStringToFloat {
  map<string, float> values = 1;
}