syntax = "proto3";
package dspRouter;
option go_package = "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/dspRouter;dspRouterGrpc";

import "types/ortb_V2_5/ortb.proto";

service DspRouterService {
    rpc GetBids_V2_5(DspRouterRequest_V2_5) returns (DspRouterResponse_V2_5);
}

message DspRouterRequest_V2_5 {
  ortb_V2_5.BidRequest bidRequest = 1;
  string globalId = 2;
  string ssp_domain = 3;
  bool logged = 4;
  string typic = 5;
}

message DspRouterResponse_V2_5 {
  ortb_V2_5.BidRequest bidRequest = 1;
  map<string, ortb_V2_5.BidResponse> bidResponses = 2;
  string globalId = 3;
  string ssp_domain = 4;
}