// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: types/ortb_V2_4/ortb.proto

package ortb_V2_4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	At            *int32                 `protobuf:"varint,2,opt,name=at,proto3,oneof" json:"at,omitempty"`
	Imp           []*Imp                 `protobuf:"bytes,3,rep,name=imp,proto3" json:"imp,omitempty"`
	Site          *Site                  `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty"`
	App           *App                   `protobuf:"bytes,5,opt,name=app,proto3,oneof" json:"app,omitempty"`
	Device        *Device                `protobuf:"bytes,6,opt,name=device,proto3,oneof" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BidRequest) GetAt() int32 {
	if x != nil && x.At != nil {
		return *x.At
	}
	return 0
}

func (x *BidRequest) GetImp() []*Imp {
	if x != nil {
		return x.Imp
	}
	return nil
}

func (x *BidRequest) GetSite() *Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *BidRequest) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *BidRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type Imp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	BidFloor      *float32               `protobuf:"fixed32,2,opt,name=bidFloor,proto3,oneof" json:"bidFloor,omitempty"`
	Banner        *Banner                `protobuf:"bytes,3,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	Native        *Native                `protobuf:"bytes,4,opt,name=native,proto3,oneof" json:"native,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Imp) Reset() {
	*x = Imp{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Imp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imp) ProtoMessage() {}

func (x *Imp) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imp.ProtoReflect.Descriptor instead.
func (*Imp) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{1}
}

func (x *Imp) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Imp) GetBidFloor() float32 {
	if x != nil && x.BidFloor != nil {
		return *x.BidFloor
	}
	return 0
}

func (x *Imp) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Imp) GetNative() *Native {
	if x != nil {
		return x.Native
	}
	return nil
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             *int32                 `protobuf:"varint,1,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H             *int32                 `protobuf:"varint,2,opt,name=h,proto3,oneof" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{2}
}

func (x *Banner) GetW() int32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *Banner) GetH() int32 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

type Native struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *string                `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Native) Reset() {
	*x = Native{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Native) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Native) ProtoMessage() {}

func (x *Native) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Native.ProtoReflect.Descriptor instead.
func (*Native) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{3}
}

func (x *Native) GetRequest() string {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return ""
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{4}
}

func (x *Site) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{5}
}

func (x *App) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *string                `protobuf:"bytes,1,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Geo           *Geo                   `protobuf:"bytes,2,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{6}
}

func (x *Device) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Device) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

type Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *string                `protobuf:"bytes,1,opt,name=country,proto3,oneof" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geo) Reset() {
	*x = Geo{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo) ProtoMessage() {}

func (x *Geo) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo.ProtoReflect.Descriptor instead.
func (*Geo) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{7}
}

func (x *Geo) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

type SeatBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           []*Bid                 `protobuf:"bytes,1,rep,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatBid) Reset() {
	*x = SeatBid{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatBid) ProtoMessage() {}

func (x *SeatBid) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatBid.ProtoReflect.Descriptor instead.
func (*SeatBid) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{8}
}

func (x *SeatBid) GetBid() []*Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Impid         *string                `protobuf:"bytes,2,opt,name=impid,proto3,oneof" json:"impid,omitempty"`
	Price         *float32               `protobuf:"fixed32,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Adid          *string                `protobuf:"bytes,4,opt,name=adid,proto3,oneof" json:"adid,omitempty"`
	Nurl          *string                `protobuf:"bytes,5,opt,name=nurl,proto3,oneof" json:"nurl,omitempty"`
	Burl          *string                `protobuf:"bytes,6,opt,name=burl,proto3,oneof" json:"burl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{9}
}

func (x *Bid) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Bid) GetImpid() string {
	if x != nil && x.Impid != nil {
		return *x.Impid
	}
	return ""
}

func (x *Bid) GetPrice() float32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Bid) GetAdid() string {
	if x != nil && x.Adid != nil {
		return *x.Adid
	}
	return ""
}

func (x *Bid) GetNurl() string {
	if x != nil && x.Nurl != nil {
		return *x.Nurl
	}
	return ""
}

func (x *Bid) GetBurl() string {
	if x != nil && x.Burl != nil {
		return *x.Burl
	}
	return ""
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Seatbid       *SeatBid               `protobuf:"bytes,2,opt,name=seatbid,proto3,oneof" json:"seatbid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_4_ortb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_4_ortb_proto_rawDescGZIP(), []int{10}
}

func (x *BidResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BidResponse) GetSeatbid() *SeatBid {
	if x != nil {
		return x.Seatbid
	}
	return nil
}

var File_types_ortb_V2_4_ortb_proto protoreflect.FileDescriptor

const file_types_ortb_V2_4_ortb_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/ortb_V2_4/ortb.proto\x12\tortb_V2_4\"\x83\x02\n" +
	"\n" +
	"BidRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x13\n" +
	"\x02at\x18\x02 \x01(\x05H\x01R\x02at\x88\x01\x01\x12 \n" +
	"\x03imp\x18\x03 \x03(\v2\x0e.ortb_V2_4.ImpR\x03imp\x12(\n" +
	"\x04site\x18\x04 \x01(\v2\x0f.ortb_V2_4.SiteH\x02R\x04site\x88\x01\x01\x12%\n" +
	"\x03app\x18\x05 \x01(\v2\x0e.ortb_V2_4.AppH\x03R\x03app\x88\x01\x01\x12.\n" +
	"\x06device\x18\x06 \x01(\v2\x11.ortb_V2_4.DeviceH\x04R\x06device\x88\x01\x01B\x05\n" +
	"\x03_idB\x05\n" +
	"\x03_atB\a\n" +
	"\x05_siteB\x06\n" +
	"\x04_appB\t\n" +
	"\a_device\"\xc5\x01\n" +
	"\x03Imp\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bbidFloor\x18\x02 \x01(\x02H\x01R\bbidFloor\x88\x01\x01\x12.\n" +
	"\x06banner\x18\x03 \x01(\v2\x11.ortb_V2_4.BannerH\x02R\x06banner\x88\x01\x01\x12.\n" +
	"\x06native\x18\x04 \x01(\v2\x11.ortb_V2_4.NativeH\x03R\x06native\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_bidFloorB\t\n" +
	"\a_bannerB\t\n" +
	"\a_native\":\n" +
	"\x06Banner\x12\x11\n" +
	"\x01w\x18\x01 \x01(\x05H\x00R\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\x02 \x01(\x05H\x01R\x01h\x88\x01\x01B\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_h\"3\n" +
	"\x06Native\x12\x1d\n" +
	"\arequest\x18\x01 \x01(\tH\x00R\arequest\x88\x01\x01B\n" +
	"\n" +
	"\b_request\"\"\n" +
	"\x04Site\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"!\n" +
	"\x03App\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"S\n" +
	"\x06Device\x12\x13\n" +
	"\x02ip\x18\x01 \x01(\tH\x00R\x02ip\x88\x01\x01\x12%\n" +
	"\x03geo\x18\x02 \x01(\v2\x0e.ortb_V2_4.GeoH\x01R\x03geo\x88\x01\x01B\x05\n" +
	"\x03_ipB\x06\n" +
	"\x04_geo\"0\n" +
	"\x03Geo\x12\x1d\n" +
	"\acountry\x18\x01 \x01(\tH\x00R\acountry\x88\x01\x01B\n" +
	"\n" +
	"\b_country\"+\n" +
	"\aSeatBid\x12 \n" +
	"\x03bid\x18\x01 \x03(\v2\x0e.ortb_V2_4.BidR\x03bid\"\xd1\x01\n" +
	"\x03Bid\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05impid\x18\x02 \x01(\tH\x01R\x05impid\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x02H\x02R\x05price\x88\x01\x01\x12\x17\n" +
	"\x04adid\x18\x04 \x01(\tH\x03R\x04adid\x88\x01\x01\x12\x17\n" +
	"\x04nurl\x18\x05 \x01(\tH\x04R\x04nurl\x88\x01\x01\x12\x17\n" +
	"\x04burl\x18\x06 \x01(\tH\x05R\x04burl\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_impidB\b\n" +
	"\x06_priceB\a\n" +
	"\x05_adidB\a\n" +
	"\x05_nurlB\a\n" +
	"\x05_burl\"h\n" +
	"\vBidResponse\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x121\n" +
	"\aseatbid\x18\x02 \x01(\v2\x12.ortb_V2_4.SeatBidH\x01R\aseatbid\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_seatbidBXZVgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_4;ortb_V2_4b\x06proto3"

var (
	file_types_ortb_V2_4_ortb_proto_rawDescOnce sync.Once
	file_types_ortb_V2_4_ortb_proto_rawDescData []byte
)

func file_types_ortb_V2_4_ortb_proto_rawDescGZIP() []byte {
	file_types_ortb_V2_4_ortb_proto_rawDescOnce.Do(func() {
		file_types_ortb_V2_4_ortb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_ortb_V2_4_ortb_proto_rawDesc), len(file_types_ortb_V2_4_ortb_proto_rawDesc)))
	})
	return file_types_ortb_V2_4_ortb_proto_rawDescData
}

var file_types_ortb_V2_4_ortb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_types_ortb_V2_4_ortb_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: ortb_V2_4.BidRequest
	(*Imp)(nil),         // 1: ortb_V2_4.Imp
	(*Banner)(nil),      // 2: ortb_V2_4.Banner
	(*Native)(nil),      // 3: ortb_V2_4.Native
	(*Site)(nil),        // 4: ortb_V2_4.Site
	(*App)(nil),         // 5: ortb_V2_4.App
	(*Device)(nil),      // 6: ortb_V2_4.Device
	(*Geo)(nil),         // 7: ortb_V2_4.Geo
	(*SeatBid)(nil),     // 8: ortb_V2_4.SeatBid
	(*Bid)(nil),         // 9: ortb_V2_4.Bid
	(*BidResponse)(nil), // 10: ortb_V2_4.BidResponse
}
var file_types_ortb_V2_4_ortb_proto_depIdxs = []int32{
	1, // 0: ortb_V2_4.BidRequest.imp:type_name -> ortb_V2_4.Imp
	4, // 1: ortb_V2_4.BidRequest.site:type_name -> ortb_V2_4.Site
	5, // 2: ortb_V2_4.BidRequest.app:type_name -> ortb_V2_4.App
	6, // 3: ortb_V2_4.BidRequest.device:type_name -> ortb_V2_4.Device
	2, // 4: ortb_V2_4.Imp.banner:type_name -> ortb_V2_4.Banner
	3, // 5: ortb_V2_4.Imp.native:type_name -> ortb_V2_4.Native
	7, // 6: ortb_V2_4.Device.geo:type_name -> ortb_V2_4.Geo
	9, // 7: ortb_V2_4.SeatBid.bid:type_name -> ortb_V2_4.Bid
	8, // 8: ortb_V2_4.BidResponse.seatbid:type_name -> ortb_V2_4.SeatBid
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_types_ortb_V2_4_ortb_proto_init() }
func file_types_ortb_V2_4_ortb_proto_init() {
	if File_types_ortb_V2_4_ortb_proto != nil {
		return
	}
	file_types_ortb_V2_4_ortb_proto_msgTypes[0].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[2].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[4].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[5].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[6].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[7].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[9].OneofWrappers = []any{}
	file_types_ortb_V2_4_ortb_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_ortb_V2_4_ortb_proto_rawDesc), len(file_types_ortb_V2_4_ortb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_ortb_V2_4_ortb_proto_goTypes,
		DependencyIndexes: file_types_ortb_V2_4_ortb_proto_depIdxs,
		MessageInfos:      file_types_ortb_V2_4_ortb_proto_msgTypes,
	}.Build()
	File_types_ortb_V2_4_ortb_proto = out.File
	file_types_ortb_V2_4_ortb_proto_goTypes = nil
	file_types_ortb_V2_4_ortb_proto_depIdxs = nil
}
