import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight,
  BarChart3,
  Check,
  ChevronDown,
  CircleDollarSign,
  Globe2,
  Layers3,
  MousePointerClick,
  Rocket,
  SlidersHorizontal,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Zap,
} from "lucide-react";
import { AuthDialog } from "@/components/landing/AuthDialog";
import { useLanguage, type Lang } from "@/contexts/LanguageContext";
import twinbidLogo from "@/assets/twinbid-logo.svg";

type MoneyLang = Extract<Lang, "en" | "ru" | "es" | "fr">;

const copy = {
  en: {
    nav: { how: "How it works", example: "Example", benefits: "Why TwinBid", calculator: "Calculator", start: "Start now" },
    hero: {
      badge: "A simple way to start with traffic",
      title: "Turn Internet Traffic Into Profit",
      subtitle: "Buy targeted visitors from around the world, send them to high-paying affiliate offers and keep the difference.",
      spend: "Traffic",
      revenue: "Revenue",
      roi: "ROI",
      cta: "START MAKING YOUR FIRST CAMPAIGN",
      note: "Create your TwinBid account in less than a minute.",
    },
    how: {
      kicker: "THE MODEL",
      title: "How Do People Make Money With Traffic?",
      subtitle: "You do not need your own product. You need an offer, targeted visitors and a campaign that earns more than it costs.",
      steps: [
        { title: "Find an offer", text: "Choose an affiliate offer that pays for registrations, purchases, installs or other actions.", metric: "Example payout: $8 per registration" },
        { title: "Buy traffic with TwinBid", text: "Launch advertising and send targeted visitors directly to your selected offer.", metric: "Example traffic budget: $100" },
        { title: "Keep the profit", text: "Track conversions, improve targeting and scale combinations that bring back more than you spend.", metric: "30 × $8 − $100 = $140 profit" },
      ],
      result: "That is traffic arbitrage. TwinBid gives you the traffic. You find the winning combination.",
      cta: "TRY IT WITH TWINBID",
    },
    example: {
      kicker: "EXAMPLE CAMPAIGN",
      title: "What Can A Winning Campaign Look Like?",
      subtitle: "One clear dashboard shows the complete economics of your test.",
      metrics: [
        ["Ad spend", "$100"],
        ["Visitors", "12,840"],
        ["Conversions", "37"],
        ["Affiliate revenue", "$370"],
        ["Profit", "+$270"],
        ["ROI", "+270%"],
      ],
      in: "$100 IN",
      out: "$370 OUT",
      text: "Test offers, audiences and traffic sources until the revenue generated by visitors exceeds what you paid for them.",
    },
    benefits: {
      kicker: "WHY TWINBID",
      title: "Everything You Need To Buy And Optimize Traffic",
      subtitle: "You focus on profitable combinations. TwinBid handles the traffic.",
      cards: [
        ["Traffic in one place", "Access inventory from multiple providers without managing dozens of separate accounts."],
        ["Automatic CPM optimization", "TwinBid searches for a more efficient buying price while preserving traffic volume."],
        ["Worldwide traffic", "Launch campaigns across countries and audiences from one dashboard."],
        ["Precise targeting", "Control GEO, devices, operating systems, browsers and other campaign parameters."],
        ["Multiple ad formats", "Run Popunder, Banner, Native and In-Page Push campaigns from one platform."],
        ["Detailed analytics", "See where your budget goes and identify sources that perform best."],
      ],
    },
    simple: {
      kicker: "BUILT FOR YOUR FIRST TEST",
      title: "Never Bought Traffic Before? That’s Fine.",
      text: "You do not need to own a website, create a product or build an audience from scratch. Start with one offer, one campaign and a controlled test budget.",
      flow: ["Choose offer", "Create campaign", "Buy traffic", "Track conversions", "Scale winners"],
      cta: "CREATE MY FIRST CAMPAIGN",
    },
    scenarios: {
      kicker: "THE MATH",
      title: "See How A Campaign Can Scale",
      cards: [
        ["Small test", "$25", "$42", "+$17", "+68%"],
        ["Winning campaign", "$100", "$370", "+$270", "+270%"],
        ["Scaled campaign", "$1,000", "$2,450", "+$1,450", "+145%"],
      ],
      labels: ["Traffic cost", "Revenue", "Profit", "ROI"],
    },
    calculator: {
      kicker: "PROFIT CALCULATOR",
      title: "Build Your Own Traffic Scenario",
      subtitle: "Move the values and instantly see how traffic arbitrage economics work.",
      budget: "Advertising budget",
      visitorCost: "Cost per visitor",
      conversionRate: "Conversion rate",
      payout: "Payout per conversion",
      visitors: "Visitors",
      conversions: "Conversions",
      revenue: "Revenue",
      profit: "Potential profit",
      roi: "ROI",
      cta: "BUILD A CAMPAIGN LIKE THIS",
    },
    voices: {
      kicker: "BUILT FOR PERFORMANCE",
      title: "What Media Buyers Care About",
      cards: [
        ["Affiliate media buyer", "Test multiple GEOs from one dashboard and find profitable combinations faster."],
        ["Performance marketer", "Understand which sources work before increasing the campaign budget."],
        ["First-time advertiser", "Start with a controlled budget and improve campaigns using real data."],
      ],
    },
    final: {
      kicker: "START WITH ONE TEST",
      title: "Your First Profitable Campaign Starts With Action.",
      text: "Get access to worldwide traffic through TwinBid and start testing offers today.",
      cta: "CREATE FREE ACCOUNT",
      note: "Registration takes less than a minute.",
    },
  },
  ru: {
    nav: { how: "Как это работает", example: "Пример", benefits: "Почему TwinBid", calculator: "Калькулятор", start: "Начать" },
    hero: {
      badge: "Простой способ начать работать с трафиком",
      title: "Превратите интернет-трафик в прибыль",
      subtitle: "Покупайте целевых посетителей со всего мира, направляйте их на доходные партнёрские офферы и оставляйте разницу себе.",
      spend: "Трафик",
      revenue: "Доход",
      roi: "ROI",
      cta: "СОЗДАТЬ ПЕРВУЮ КАМПАНИЮ",
      note: "Создание аккаунта TwinBid занимает меньше минуты.",
    },
    how: {
      kicker: "МОДЕЛЬ ЗАРАБОТКА",
      title: "Как люди зарабатывают на трафике?",
      subtitle: "Собственный продукт не нужен. Нужны оффер, целевые посетители и кампания, которая приносит больше, чем стоит.",
      steps: [
        { title: "Найдите оффер", text: "Выберите партнёрский оффер, который платит за регистрации, покупки, установки или другие действия.", metric: "Пример выплаты: $8 за регистрацию" },
        { title: "Купите трафик в TwinBid", text: "Запустите рекламу и направьте целевых посетителей прямо на выбранный оффер.", metric: "Пример бюджета на трафик: $100" },
        { title: "Заберите прибыль", text: "Отслеживайте конверсии, улучшайте таргетинг и масштабируйте связки, которые приносят больше затрат.", metric: "30 × $8 − $100 = $140 прибыли" },
      ],
      result: "Это арбитраж трафика. TwinBid даёт вам трафик, а вы находите прибыльную связку.",
      cta: "ПОПРОБОВАТЬ TWINBID",
    },
    example: {
      kicker: "ПРИМЕР КАМПАНИИ",
      title: "Как может выглядеть прибыльная кампания?",
      subtitle: "В одном понятном кабинете видна вся экономика теста.",
      metrics: [["Расход", "$100"], ["Посетители", "12 840"], ["Конверсии", "37"], ["Доход от партнёрки", "$370"], ["Прибыль", "+$270"], ["ROI", "+270%"]],
      in: "$100 ВЛОЖЕНО",
      out: "$370 ПОЛУЧЕНО",
      text: "Тестируйте офферы, аудитории и источники, пока доход от посетителей не станет выше стоимости трафика.",
    },
    benefits: {
      kicker: "ПОЧЕМУ TWINBID",
      title: "Всё для покупки и оптимизации трафика",
      subtitle: "Вы ищете прибыльные связки. TwinBid занимается трафиком.",
      cards: [
        ["Трафик в одном месте", "Получайте инвентарь от нескольких поставщиков без десятков отдельных аккаунтов."],
        ["Автооптимизация CPM", "TwinBid ищет более выгодную цену покупки, стараясь сохранить объём трафика."],
        ["Трафик со всего мира", "Запускайте кампании по странам и аудиториям из одного кабинета."],
        ["Точные таргетинги", "Управляйте GEO, устройствами, ОС, браузерами и другими параметрами."],
        ["Несколько форматов", "Запускайте Popunder, Banner, Native и In-Page Push на одной платформе."],
        ["Подробная аналитика", "Смотрите, куда уходит бюджет, и находите самые эффективные источники."],
      ],
    },
    simple: {
      kicker: "ДЛЯ ПЕРВОГО ТЕСТА",
      title: "Никогда не покупали трафик? Это не проблема.",
      text: "Вам не нужен свой сайт, продукт или готовая аудитория. Начните с одного оффера, одной кампании и контролируемого тестового бюджета.",
      flow: ["Выберите оффер", "Создайте кампанию", "Купите трафик", "Отследите конверсии", "Масштабируйте"],
      cta: "СОЗДАТЬ ПЕРВУЮ КАМПАНИЮ",
    },
    scenarios: {
      kicker: "ПРОСТАЯ МАТЕМАТИКА",
      title: "Как может масштабироваться кампания",
      cards: [["Небольшой тест", "$25", "$42", "+$17", "+68%"], ["Прибыльная кампания", "$100", "$370", "+$270", "+270%"], ["Масштабирование", "$1 000", "$2 450", "+$1 450", "+145%"]],
      labels: ["Стоимость трафика", "Доход", "Прибыль", "ROI"],
    },
    calculator: {
      kicker: "КАЛЬКУЛЯТОР ПРИБЫЛИ",
      title: "Соберите свой сценарий кампании",
      subtitle: "Меняйте значения и сразу смотрите, как работает экономика арбитража.",
      budget: "Рекламный бюджет", visitorCost: "Стоимость посетителя", conversionRate: "Конверсия", payout: "Выплата за конверсию",
      visitors: "Посетители", conversions: "Конверсии", revenue: "Доход", profit: "Потенциальная прибыль", roi: "ROI", cta: "СОЗДАТЬ ТАКУЮ КАМПАНИЮ",
    },
    voices: {
      kicker: "СОЗДАНО ДЛЯ РЕЗУЛЬТАТА",
      title: "Что важно медиабайерам",
      cards: [["Арбитражник", "Тестируйте несколько GEO из одного кабинета и быстрее находите прибыльные связки."], ["Performance-маркетолог", "Понимайте, какие источники работают, до увеличения бюджета кампании."], ["Начинающий рекламодатель", "Начните с контролируемого бюджета и улучшайте кампанию по реальным данным."]],
    },
    final: {
      kicker: "НАЧНИТЕ С ОДНОГО ТЕСТА",
      title: "Первая прибыльная кампания начинается с действия.",
      text: "Получите доступ к мировому трафику через TwinBid и начните тестировать офферы сегодня.",
      cta: "СОЗДАТЬ БЕСПЛАТНЫЙ АККАУНТ",
      note: "Регистрация занимает меньше минуты.",
    },
  },
  es: {
    nav: { how: "Cómo funciona", example: "Ejemplo", benefits: "Por qué TwinBid", calculator: "Calculadora", start: "Empezar" },
    hero: {
      badge: "Una forma sencilla de empezar con tráfico",
      title: "Convierte el tráfico de Internet en ganancias",
      subtitle: "Compra visitantes segmentados de todo el mundo, envíalos a ofertas de afiliados rentables y quédate con la diferencia.",
      spend: "Tráfico", revenue: "Ingresos", roi: "ROI", cta: "CREAR MI PRIMERA CAMPAÑA", note: "Crea tu cuenta TwinBid en menos de un minuto.",
    },
    how: {
      kicker: "EL MODELO", title: "¿Cómo se gana dinero con tráfico?", subtitle: "No necesitas un producto propio. Necesitas una oferta, visitantes segmentados y una campaña que genere más de lo que cuesta.",
      steps: [
        { title: "Encuentra una oferta", text: "Elige una oferta de afiliados que pague por registros, compras, instalaciones u otras acciones.", metric: "Pago de ejemplo: $8 por registro" },
        { title: "Compra tráfico con TwinBid", text: "Lanza publicidad y envía visitantes segmentados directamente a la oferta elegida.", metric: "Presupuesto de ejemplo: $100" },
        { title: "Conserva la ganancia", text: "Mide conversiones, mejora la segmentación y escala las combinaciones que devuelven más de lo invertido.", metric: "30 × $8 − $100 = $140 de ganancia" },
      ],
      result: "Eso es arbitraje de tráfico. TwinBid te da el tráfico. Tú encuentras la combinación ganadora.", cta: "PROBAR TWINBID",
    },
    example: {
      kicker: "CAMPAÑA DE EJEMPLO", title: "¿Cómo puede verse una campaña ganadora?", subtitle: "Un panel claro muestra toda la economía de tu prueba.",
      metrics: [["Inversión publicitaria", "$100"], ["Visitantes", "12.840"], ["Conversiones", "37"], ["Ingresos de afiliado", "$370"], ["Ganancia", "+$270"], ["ROI", "+270%"]],
      in: "$100 INVERTIDOS", out: "$370 RECIBIDOS", text: "Prueba ofertas, audiencias y fuentes hasta que los ingresos generados superen el coste del tráfico.",
    },
    benefits: {
      kicker: "POR QUÉ TWINBID", title: "Todo para comprar y optimizar tráfico", subtitle: "Tú buscas combinaciones rentables. TwinBid gestiona el tráfico.",
      cards: [["Tráfico en un solo lugar", "Accede a inventario de varios proveedores sin gestionar decenas de cuentas."], ["Optimización automática de CPM", "TwinBid busca un precio más eficiente manteniendo el volumen."], ["Tráfico mundial", "Lanza campañas por países y audiencias desde un panel."], ["Segmentación precisa", "Controla GEO, dispositivos, sistemas, navegadores y otros parámetros."], ["Varios formatos", "Ejecuta Popunder, Banner, Native e In-Page Push en una plataforma."], ["Analítica detallada", "Mira dónde se invierte el presupuesto y encuentra las mejores fuentes."]],
    },
    simple: {
      kicker: "PARA TU PRIMERA PRUEBA", title: "¿Nunca compraste tráfico? No pasa nada.", text: "No necesitas sitio web, producto propio ni audiencia. Empieza con una oferta, una campaña y un presupuesto de prueba controlado.",
      flow: ["Elige una oferta", "Crea una campaña", "Compra tráfico", "Mide conversiones", "Escala ganadores"], cta: "CREAR MI PRIMERA CAMPAÑA",
    },
    scenarios: {
      kicker: "LOS NÚMEROS", title: "Cómo puede escalar una campaña", cards: [["Prueba pequeña", "$25", "$42", "+$17", "+68%"], ["Campaña ganadora", "$100", "$370", "+$270", "+270%"], ["Campaña escalada", "$1.000", "$2.450", "+$1.450", "+145%"]], labels: ["Coste de tráfico", "Ingresos", "Ganancia", "ROI"],
    },
    calculator: {
      kicker: "CALCULADORA DE GANANCIAS", title: "Crea tu propio escenario", subtitle: "Mueve los valores y mira al instante cómo funciona la economía del arbitraje.",
      budget: "Presupuesto publicitario", visitorCost: "Coste por visitante", conversionRate: "Tasa de conversión", payout: "Pago por conversión", visitors: "Visitantes", conversions: "Conversiones", revenue: "Ingresos", profit: "Ganancia potencial", roi: "ROI", cta: "CREAR UNA CAMPAÑA ASÍ",
    },
    voices: {
      kicker: "CREADO PARA RENDIR", title: "Lo que importa a los media buyers", cards: [["Media buyer afiliado", "Prueba varios GEO desde un panel y encuentra combinaciones rentables más rápido."], ["Performance marketer", "Descubre qué fuentes funcionan antes de aumentar el presupuesto."], ["Primer anunciante", "Empieza con un presupuesto controlado y mejora usando datos reales."]],
    },
    final: { kicker: "EMPIEZA CON UNA PRUEBA", title: "Tu primera campaña rentable empieza con una acción.", text: "Accede a tráfico mundial con TwinBid y empieza a probar ofertas hoy.", cta: "CREAR CUENTA GRATIS", note: "El registro tarda menos de un minuto." },
  },
  fr: {
    nav: { how: "Fonctionnement", example: "Exemple", benefits: "Pourquoi TwinBid", calculator: "Calculateur", start: "Commencer" },
    hero: {
      badge: "Une façon simple de commencer avec le trafic", title: "Transformez le trafic Internet en profit", subtitle: "Achetez des visiteurs ciblés dans le monde entier, envoyez-les vers des offres d’affiliation rémunératrices et gardez la différence.", spend: "Trafic", revenue: "Revenus", roi: "ROI", cta: "CRÉER MA PREMIÈRE CAMPAGNE", note: "Créez votre compte TwinBid en moins d’une minute.",
    },
    how: {
      kicker: "LE MODÈLE", title: "Comment gagner de l’argent avec le trafic ?", subtitle: "Vous n’avez pas besoin de votre propre produit. Il vous faut une offre, des visiteurs ciblés et une campagne qui rapporte plus qu’elle ne coûte.",
      steps: [{ title: "Trouvez une offre", text: "Choisissez une offre d’affiliation qui paie pour des inscriptions, achats, installations ou autres actions.", metric: "Exemple : 8 $ par inscription" }, { title: "Achetez du trafic avec TwinBid", text: "Lancez une publicité et envoyez des visiteurs ciblés directement vers l’offre choisie.", metric: "Exemple de budget : 100 $" }, { title: "Gardez le profit", text: "Suivez les conversions, améliorez le ciblage et développez les combinaisons rentables.", metric: "30 × 8 $ − 100 $ = 140 $ de profit" }],
      result: "C’est l’arbitrage de trafic. TwinBid fournit le trafic. Vous trouvez la combinaison gagnante.", cta: "ESSAYER TWINBID",
    },
    example: {
      kicker: "EXEMPLE DE CAMPAGNE", title: "À quoi peut ressembler une campagne gagnante ?", subtitle: "Une seule interface présente toute l’économie de votre test.", metrics: [["Dépenses publicitaires", "100 $"], ["Visiteurs", "12 840"], ["Conversions", "37"], ["Revenus d’affiliation", "370 $"], ["Profit", "+270 $"], ["ROI", "+270 %"]], in: "100 $ INVESTIS", out: "370 $ REÇUS", text: "Testez les offres, audiences et sources jusqu’à ce que les revenus générés dépassent le coût du trafic.",
    },
    benefits: {
      kicker: "POURQUOI TWINBID", title: "Tout pour acheter et optimiser votre trafic", subtitle: "Vous cherchez les combinaisons rentables. TwinBid gère le trafic.", cards: [["Le trafic au même endroit", "Accédez à plusieurs fournisseurs sans gérer des dizaines de comptes."], ["Optimisation automatique du CPM", "TwinBid recherche un prix d’achat plus efficace tout en préservant le volume."], ["Trafic mondial", "Lancez des campagnes par pays et audience depuis une seule interface."], ["Ciblage précis", "Contrôlez les GEO, appareils, systèmes, navigateurs et autres paramètres."], ["Plusieurs formats", "Lancez du Popunder, Banner, Native et In-Page Push sur une plateforme."], ["Analyses détaillées", "Voyez où va votre budget et identifiez les sources les plus performantes."]],
    },
    simple: {
      kicker: "POUR VOTRE PREMIER TEST", title: "Vous n’avez jamais acheté de trafic ? Aucun problème.", text: "Vous n’avez besoin ni d’un site, ni d’un produit, ni d’une audience. Commencez avec une offre, une campagne et un budget de test maîtrisé.", flow: ["Choisir une offre", "Créer une campagne", "Acheter du trafic", "Suivre les conversions", "Développer les gagnants"], cta: "CRÉER MA PREMIÈRE CAMPAGNE",
    },
    scenarios: {
      kicker: "LES CHIFFRES", title: "Comment une campagne peut évoluer", cards: [["Petit test", "25 $", "42 $", "+17 $", "+68 %"], ["Campagne gagnante", "100 $", "370 $", "+270 $", "+270 %"], ["Campagne développée", "1 000 $", "2 450 $", "+1 450 $", "+145 %"]], labels: ["Coût du trafic", "Revenus", "Profit", "ROI"],
    },
    calculator: {
      kicker: "CALCULATEUR DE PROFIT", title: "Construisez votre propre scénario", subtitle: "Modifiez les valeurs et observez immédiatement l’économie de l’arbitrage.", budget: "Budget publicitaire", visitorCost: "Coût par visiteur", conversionRate: "Taux de conversion", payout: "Paiement par conversion", visitors: "Visiteurs", conversions: "Conversions", revenue: "Revenus", profit: "Profit potentiel", roi: "ROI", cta: "CRÉER UNE CAMPAGNE COMME CELLE-CI",
    },
    voices: {
      kicker: "CONÇU POUR LA PERFORMANCE", title: "Ce qui compte pour les media buyers", cards: [["Media buyer affilié", "Testez plusieurs GEO depuis une interface et trouvez plus vite des combinaisons rentables."], ["Performance marketer", "Identifiez les sources efficaces avant d’augmenter le budget."], ["Nouvel annonceur", "Commencez avec un budget maîtrisé et progressez grâce aux données réelles."]],
    },
    final: { kicker: "COMMENCEZ PAR UN TEST", title: "Votre première campagne rentable commence par une action.", text: "Accédez au trafic mondial avec TwinBid et commencez à tester des offres aujourd’hui.", cta: "CRÉER UN COMPTE GRATUIT", note: "L’inscription prend moins d’une minute." },
  },
} as const;

const interfaceCopy = {
  en: {
    model: "Campaign economics",
    spendLabel: "You buy traffic",
    offerLabel: "Visitors reach the offer",
    returnLabel: "Offer generates revenue",
    profitLabel: "Difference is your result",
    clearModel: "One simple model",
    platform: "One platform",
    visibility: "Full visibility",
    clearModelText: "Spend less on traffic than the offer returns.",
    platformText: "Launch, target and optimize from one dashboard.",
    visibilityText: "See spend, traffic, conversions and sources.",
    campaignName: "Worldwide acquisition test",
    active: "Active",
    performance: "Performance overview",
    input: "Investment",
    output: "Revenue",
    netResult: "Net result",
    stepsTitle: "From an idea to a scalable campaign",
    calculatorCaption: "Change the campaign inputs",
    liveResult: "Live scenario",
    campaignReady: "Your traffic model",
    offer: "Offer",
  },
  ru: {
    model: "Экономика кампании",
    spendLabel: "Вы покупаете трафик",
    offerLabel: "Посетители переходят на оффер",
    returnLabel: "Оффер приносит доход",
    profitLabel: "Разница становится результатом",
    clearModel: "Простая модель",
    platform: "Одна платформа",
    visibility: "Полная прозрачность",
    clearModelText: "Трафик должен стоить меньше дохода от оффера.",
    platformText: "Запуск, таргетинг и оптимизация в одном кабинете.",
    visibilityText: "Расход, трафик, конверсии и источники перед глазами.",
    campaignName: "Тест кампании на мировом трафике",
    active: "Активна",
    performance: "Результаты кампании",
    input: "Вложения",
    output: "Доход",
    netResult: "Чистый результат",
    stepsTitle: "От идеи до масштабируемой кампании",
    calculatorCaption: "Изменяйте параметры кампании",
    liveResult: "Расчёт в реальном времени",
    campaignReady: "Ваша модель трафика",
    offer: "Оффер",
  },
  es: {
    model: "Economía de campaña",
    spendLabel: "Compras tráfico",
    offerLabel: "Los visitantes llegan a la oferta",
    returnLabel: "La oferta genera ingresos",
    profitLabel: "La diferencia es tu resultado",
    clearModel: "Un modelo sencillo",
    platform: "Una plataforma",
    visibility: "Visibilidad total",
    clearModelText: "El tráfico debe costar menos de lo que devuelve la oferta.",
    platformText: "Lanza, segmenta y optimiza desde un panel.",
    visibilityText: "Consulta inversión, tráfico, conversiones y fuentes.",
    campaignName: "Prueba mundial de adquisición",
    active: "Activa",
    performance: "Resumen de rendimiento",
    input: "Inversión",
    output: "Ingresos",
    netResult: "Resultado neto",
    stepsTitle: "De una idea a una campaña escalable",
    calculatorCaption: "Cambia los parámetros de campaña",
    liveResult: "Escenario en vivo",
    campaignReady: "Tu modelo de tráfico",
    offer: "Oferta",
  },
  fr: {
    model: "Économie de campagne",
    spendLabel: "Vous achetez du trafic",
    offerLabel: "Les visiteurs arrivent sur l’offre",
    returnLabel: "L’offre génère des revenus",
    profitLabel: "La différence devient votre résultat",
    clearModel: "Un modèle simple",
    platform: "Une plateforme",
    visibility: "Visibilité complète",
    clearModelText: "Le trafic doit coûter moins que les revenus de l’offre.",
    platformText: "Lancez, ciblez et optimisez depuis une interface.",
    visibilityText: "Suivez dépenses, trafic, conversions et sources.",
    campaignName: "Test d’acquisition mondial",
    active: "Active",
    performance: "Aperçu des performances",
    input: "Investissement",
    output: "Revenus",
    netResult: "Résultat net",
    stepsTitle: "D’une idée à une campagne évolutive",
    calculatorCaption: "Modifiez les paramètres de campagne",
    liveResult: "Scénario en direct",
    campaignReady: "Votre modèle de trafic",
    offer: "Offre",
  },
} as const;

const benefitIcons = [Layers3, Zap, Globe2, SlidersHorizontal, MousePointerClick, BarChart3];
const stepIcons = [Target, Users, CircleDollarSign];

const money = (value: number) => `$${value.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;

function SectionHeading({ kicker, title, subtitle, align = "center" }: { kicker: string; title: string; subtitle?: string; align?: "left" | "center" }) {
  return (
    <div className={`mb-10 max-w-3xl sm:mb-14 ${align === "center" ? "mx-auto text-center" : ""}`}>
      <div className="mb-4 flex items-center gap-3 font-mono text-[11px] font-semibold uppercase tracking-[0.22em] text-primary sm:text-xs">
        {align === "left" && <span className="h-px w-8 bg-primary/60" />}{kicker}
      </div>
      <h2 className="text-balance text-3xl font-medium leading-[1.05] tracking-[-0.045em] text-white sm:text-5xl lg:text-[3.4rem]">{title}</h2>
      {subtitle && <p className={`mt-5 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base ${align === "center" ? "mx-auto" : ""}`}>{subtitle}</p>}
    </div>
  );
}

function RegisterButton({ children, className = "" }: { children: string; className?: string }) {
  return (
    <AuthDialog
      defaultTab="register"
      trigger={
        <button className={`landing-button landing-button-primary group inline-flex min-h-14 items-center justify-center gap-3 px-6 py-4 text-sm font-semibold shadow-[0_16px_50px_hsl(var(--primary)/0.12)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_18px_60px_hsl(var(--primary)/0.24)] sm:px-8 ${className}`}>
          {children}<ArrowRight className="h-4 w-4 shrink-0 transition-transform group-hover:translate-x-1" />
        </button>
      }
    />
  );
}

function CalculatorControl({ label, value, display, min, max, step, onChange }: {
  label: string;
  value: number;
  display: string;
  min: number;
  max: number;
  step: number;
  onChange: (value: number) => void;
}) {
  return (
    <label className="block border border-white/[0.08] bg-white/[0.025] p-4 transition-colors focus-within:border-primary/35 sm:p-5">
      <span className="mb-4 flex items-center justify-between gap-4">
        <span className="text-sm text-slate-400">{label}</span>
        <strong className="font-mono text-base font-medium text-white sm:text-lg">{display}</strong>
      </span>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(event) => onChange(Number(event.target.value))}
        className="h-1.5 w-full cursor-pointer accent-[hsl(var(--primary))]"
      />
      <span className="mt-3 flex justify-between font-mono text-[9px] text-slate-600"><span>{min}</span><span>{max}</span></span>
    </label>
  );
}

export default function TwinBidMoney() {
  const { setLang } = useLanguage();
  const [lang, setMoneyLang] = useState<MoneyLang>("en");
  const [languageOpen, setLanguageOpen] = useState(false);
  const [budget, setBudget] = useState(100);
  const [visitorCost, setVisitorCost] = useState(0.01);
  const [conversionRate, setConversionRate] = useState(2);
  const [payout, setPayout] = useState(1.5);
  const text = copy[lang];
  const ui = interfaceCopy[lang];

  useEffect(() => {
    setLang(lang);
  }, [lang, setLang]);

  useEffect(() => {
    const previousTitle = document.title;
    document.title = "TwinBid — Turn Internet Traffic Into Profit";
    return () => { document.title = previousTitle; };
  }, []);

  const result = useMemo(() => {
    const visitors = visitorCost > 0 ? Math.floor(budget / visitorCost) : 0;
    const conversions = Math.round(visitors * conversionRate / 100);
    const revenue = conversions * payout;
    const profit = revenue - budget;
    const roi = budget > 0 ? profit / budget * 100 : 0;
    return { visitors, conversions, revenue, profit, roi };
  }, [budget, visitorCost, conversionRate, payout]);

  return (
    <div className="landing-shell twinbid-money-shell min-h-screen overflow-x-hidden bg-background text-foreground selection:bg-primary/30">
      <div className="pointer-events-none fixed inset-0 opacity-80" aria-hidden="true">
        <div className="absolute left-1/2 top-[-28rem] h-[56rem] w-[56rem] -translate-x-1/2 rounded-full bg-primary/[0.1] blur-[150px]" />
        <div className="absolute inset-x-0 top-0 h-[46rem] bg-[linear-gradient(180deg,hsl(200_18%_5%/0.16),transparent)]" />
      </div>

      <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 md:px-6 md:pt-5">
        <div className="landing-header-panel mx-auto flex h-[60px] max-w-[1320px] items-center justify-between rounded-[14px] border border-white/[0.09] bg-[hsl(200_18%_7%/0.92)] px-4 shadow-[0_18px_70px_rgba(0,0,0,0.4)] backdrop-blur-xl md:px-5">
          <a href="/twinbid_money" className="shrink-0" aria-label="TwinBid Money">
            <img src={twinbidLogo} alt="TwinBid" className="h-8 sm:h-9" />
          </a>
          <nav className="hidden items-center gap-1 lg:flex">
            <a href="#how" className="landing-header-nav-link">{text.nav.how}</a>
            <a href="#example" className="landing-header-nav-link">{text.nav.example}</a>
            <a href="#benefits" className="landing-header-nav-link">{text.nav.benefits}</a>
            <a href="#calculator" className="landing-header-nav-link">{text.nav.calculator}</a>
          </nav>
          <div className="flex items-center gap-2">
            <div className="relative">
              <button onClick={() => setLanguageOpen((value) => !value)} className="landing-language-trigger flex h-10 items-center gap-1 px-3 text-xs font-semibold" aria-expanded={languageOpen}>
                {lang.toUpperCase()}<ChevronDown className="h-3.5 w-3.5" />
              </button>
              {languageOpen && (
                <div className="absolute right-0 top-12 w-36 overflow-hidden rounded-xl border border-white/10 bg-[#0b1213] p-1 shadow-2xl">
                  {(["en", "ru", "es", "fr"] as MoneyLang[]).map((code) => (
                    <button key={code} onClick={() => { setMoneyLang(code); setLanguageOpen(false); }} className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm hover:bg-white/5">
                      {code.toUpperCase()}{lang === code && <Check className="h-4 w-4 text-primary" />}
                    </button>
                  ))}
                </div>
              )}
            </div>
            <AuthDialog defaultTab="register" trigger={<button className="landing-button landing-button-primary hidden h-10 px-5 text-xs font-semibold sm:block">{text.nav.start}</button>} />
          </div>
        </div>
      </header>

      <main className="relative z-10">
        <section className="mx-auto flex min-h-[100svh] max-w-7xl items-center px-4 pb-14 pt-28 sm:px-6 sm:pt-32">
          <div className="grid w-full items-center gap-12 lg:grid-cols-[1.03fr_0.97fr] lg:gap-16">
            <div>
              <div className="mb-7 inline-flex items-center gap-2.5 border border-primary/20 bg-primary/[0.07] px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-primary sm:text-xs">
                <span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full rounded-full bg-primary opacity-40" /><span className="relative inline-flex h-2 w-2 rounded-full bg-primary" /></span>{text.hero.badge}
              </div>
              <h1 className="max-w-4xl text-balance text-[clamp(3.25rem,7vw,6.6rem)] font-medium leading-[0.91] tracking-[-0.065em]">{text.hero.title}</h1>
              <p className="mt-7 max-w-2xl text-base leading-7 text-slate-300 sm:text-xl sm:leading-8">{text.hero.subtitle}</p>
              <div className="mt-9 flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:gap-5">
                <RegisterButton>{text.hero.cta}</RegisterButton>
                <p className="max-w-[15rem] text-xs leading-5 text-slate-500">{text.hero.note}</p>
              </div>
            </div>

            <div className="relative mx-auto w-full max-w-[35rem]">
              <div className="absolute inset-10 rounded-full bg-primary/[0.16] blur-[100px]" />
              <div className="relative overflow-hidden border border-white/[0.11] bg-[#0a1213]/95 p-4 shadow-[0_35px_110px_rgba(0,0,0,0.55)] sm:p-6">
                <div className="flex items-center justify-between border-b border-white/[0.07] pb-5">
                  <div><div className="font-mono text-[9px] uppercase tracking-[0.22em] text-slate-500">TwinBid Money</div><div className="mt-1 text-sm font-medium text-slate-200">{ui.model}</div></div>
                  <span className="flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/[0.07] px-3 py-1.5 text-xs font-semibold text-emerald-300"><TrendingUp className="h-3.5 w-3.5" />+270%</span>
                </div>

                <div className="mt-5 grid gap-3 sm:grid-cols-2">
                  <div className="border border-white/[0.07] bg-white/[0.025] p-5">
                    <div className="text-xs text-slate-500">{ui.input}</div><div className="mt-2 text-4xl font-light tracking-[-0.05em]">$100</div><div className="mt-4 h-1.5 rounded-full bg-white/[0.05]"><div className="h-full w-[27%] rounded-full bg-slate-500" /></div>
                  </div>
                  <div className="border border-primary/20 bg-primary/[0.065] p-5">
                    <div className="text-xs text-primary/70">{ui.output}</div><div className="mt-2 text-4xl font-light tracking-[-0.05em] text-primary">$370</div><div className="mt-4 h-1.5 rounded-full bg-white/[0.06]"><div className="h-full w-full rounded-full bg-primary" /></div>
                  </div>
                </div>

                <div className="mt-3 border border-emerald-400/15 bg-emerald-400/[0.045] p-5 sm:p-6">
                  <div className="flex items-start justify-between gap-5"><div><div className="text-xs text-emerald-200/55">{ui.netResult}</div><div className="mt-2 text-5xl font-light tracking-[-0.055em] text-emerald-300 sm:text-6xl">+$270</div></div><CircleDollarSign className="h-8 w-8 text-emerald-300/50" /></div>
                  <div className="mt-5 flex items-center gap-2 font-mono text-[10px] text-slate-500"><span>$370</span><span>−</span><span>$100</span><span>=</span><span className="text-emerald-300">+$270</span></div>
                </div>

                <div className="mt-3 grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 border border-white/[0.06] bg-black/20 p-3 text-center">
                  <div><div className="text-sm font-semibold">$100</div><div className="mt-1 text-[8px] uppercase tracking-wider text-slate-600">{text.hero.spend}</div></div><ArrowRight className="h-3.5 w-3.5 text-slate-600" /><div><Target className="mx-auto h-4 w-4 text-primary" /><div className="mt-1 text-[8px] uppercase tracking-wider text-slate-600">{ui.offer}</div></div><ArrowRight className="h-3.5 w-3.5 text-slate-600" /><div><div className="text-sm font-semibold text-emerald-300">$370</div><div className="mt-1 text-[8px] uppercase tracking-wider text-slate-600">{text.hero.revenue}</div></div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="border-y border-white/[0.06] bg-white/[0.012] px-4 py-6 sm:px-6">
          <div className="mx-auto grid max-w-7xl divide-y divide-white/[0.06] sm:grid-cols-3 sm:divide-x sm:divide-y-0">
            {[
              { title: ui.clearModel, description: ui.clearModelText, icon: CircleDollarSign },
              { title: ui.platform, description: ui.platformText, icon: Layers3 },
              { title: ui.visibility, description: ui.visibilityText, icon: BarChart3 },
            ].map(({ title, description, icon: Icon }, index) => (
              <div key={title} className={`flex gap-4 py-5 sm:px-6 ${index === 0 ? "sm:pl-0" : ""}`}>
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-primary/15 bg-primary/[0.06] text-primary"><Icon className="h-[18px] w-[18px]" /></div>
                <div><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{description}</div></div>
              </div>
            ))}
          </div>
        </section>

        <section id="how" className="scroll-mt-24 px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto max-w-7xl">
            <SectionHeading kicker={text.how.kicker} title={text.how.title} subtitle={text.how.subtitle} />
            <div className="relative grid gap-4 md:grid-cols-3">
              <div className="absolute left-[16.7%] right-[16.7%] top-12 hidden h-px bg-gradient-to-r from-transparent via-primary/35 to-transparent md:block" />
              {text.how.steps.map((step, index) => {
                const Icon = stepIcons[index];
                return <article key={step.title} className="relative overflow-hidden border border-white/[0.08] bg-[#0a1112] p-6 sm:p-8"><div className="absolute right-5 top-4 font-mono text-xs text-white/20">0{index + 1}</div><div className="relative mb-7 flex h-12 w-12 items-center justify-center border border-primary/20 bg-[#0a1112] text-primary shadow-[0_0_35px_hsl(var(--primary)/0.1)]"><Icon className="h-5 w-5" /></div><h3 className="text-xl font-medium">{step.title}</h3><p className="mt-3 min-h-[4.5rem] text-sm leading-6 text-slate-400">{step.text}</p><div className="mt-6 border-t border-white/[0.07] pt-5 font-mono text-xs font-medium text-primary">{step.metric}</div></article>;
              })}
            </div>
            <div className="mx-auto mt-10 max-w-3xl text-center"><p className="text-lg leading-8 text-slate-200">{text.how.result}</p><div className="mt-7"><RegisterButton>{text.how.cta}</RegisterButton></div></div>
          </div>
        </section>

        <section id="example" className="scroll-mt-24 border-y border-white/[0.06] bg-[#091011] px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.82fr_1.18fr] lg:gap-16">
            <div>
              <SectionHeading kicker={text.example.kicker} title={text.example.title} subtitle={text.example.subtitle} align="left" />
              <div className="flex flex-wrap items-center gap-3"><div className="border border-white/[0.08] bg-white/[0.025] px-5 py-4"><div className="text-xs text-slate-500">{ui.input}</div><div className="mt-1 text-2xl font-medium">$100</div></div><ArrowRight className="h-5 w-5 text-primary" /><div className="border border-emerald-400/15 bg-emerald-400/[0.045] px-5 py-4"><div className="text-xs text-emerald-200/50">{ui.output}</div><div className="mt-1 text-2xl font-medium text-emerald-300">$370</div></div></div>
              <p className="mt-6 text-sm leading-7 text-slate-400 sm:text-base">{text.example.text}</p>
            </div>
            <div className="overflow-hidden border border-white/[0.09] bg-[#0b1314] shadow-[0_30px_90px_rgba(0,0,0,0.3)]">
              <div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4 sm:px-7"><div><div className="text-sm font-medium">{ui.campaignName}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.18em] text-slate-600">Popunder · Worldwide</div></div><span className="flex items-center gap-2 rounded-full bg-emerald-400/[0.07] px-3 py-1.5 text-xs text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />{ui.active}</span></div>
              <div className="grid gap-6 p-5 sm:p-7 md:grid-cols-[1fr_0.78fr]">
                <div><div className="mb-5 text-xs text-slate-500">{ui.performance}</div><div className="divide-y divide-white/[0.06]">{text.example.metrics.map(([label, value], index) => <div key={label} className="flex items-center justify-between gap-4 py-3"><span className="text-sm text-slate-500">{label}</span><span className={`font-mono text-base font-medium ${index >= 4 ? "text-emerald-300" : "text-slate-200"}`}>{value}</span></div>)}</div></div>
                <div className="flex min-h-[17rem] flex-col justify-between border border-primary/15 bg-primary/[0.045] p-5"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary/60">ROI</div><div className="mt-2 text-6xl font-light tracking-[-0.06em] text-primary">+270%</div></div><svg viewBox="0 0 260 100" className="h-28 w-full" preserveAspectRatio="none" aria-hidden><defs><linearGradient id="campaign-chart" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="hsl(var(--primary))" stopOpacity=".25"/><stop offset="1" stopColor="hsl(var(--primary))" stopOpacity="0"/></linearGradient></defs><path d="M0 86 C28 82 40 72 68 76 S108 61 130 64 S168 48 190 43 S228 27 260 10 L260 100 L0 100Z" fill="url(#campaign-chart)"/><path d="M0 86 C28 82 40 72 68 76 S108 61 130 64 S168 48 190 43 S228 27 260 10" fill="none" stroke="hsl(var(--primary))" strokeWidth="2.5"/></svg><div className="flex items-center justify-between border-t border-white/[0.07] pt-4"><span className="text-xs text-slate-500">{ui.netResult}</span><span className="font-mono text-xl text-emerald-300">+$270</span></div></div>
              </div>
            </div>
          </div>
        </section>

        <section id="benefits" className="scroll-mt-24 px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto max-w-7xl">
            <SectionHeading kicker={text.benefits.kicker} title={text.benefits.title} subtitle={text.benefits.subtitle} />
            <div className="grid overflow-hidden border border-white/[0.08] bg-[#0a1112] sm:grid-cols-2 lg:grid-cols-3">{text.benefits.cards.map(([title, description], index) => { const Icon = benefitIcons[index]; return <article key={title} className="group border-b border-white/[0.07] p-6 last:border-b-0 sm:border-r sm:p-8 lg:[&:nth-child(3n)]:border-r-0 lg:[&:nth-last-child(-n+3)]:border-b-0"><div className="mb-7 flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center border border-primary/15 bg-primary/[0.06] text-primary"><Icon className="h-5 w-5" /></div><span className="font-mono text-[10px] text-white/15">0{index + 1}</span></div><h3 className="text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p></article>; })}</div>
          </div>
        </section>

        <section className="border-y border-white/[0.06] bg-[#091011] px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto max-w-7xl">
            <div className="grid items-end gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:gap-16">
              <div><div className="font-mono text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">{text.simple.kicker}</div><h2 className="mt-4 text-balance text-3xl font-medium leading-[1.05] tracking-[-0.045em] sm:text-5xl">{text.simple.title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400 sm:text-base">{text.simple.text}</p><div className="mt-7"><RegisterButton>{text.simple.cta}</RegisterButton></div></div>
              <div><div className="mb-5 text-sm font-medium text-slate-300">{ui.stepsTitle}</div><div className="overflow-hidden border border-white/[0.08] bg-[#0a1112]">{text.simple.flow.map((item, index) => <div key={item} className="flex items-center gap-4 border-b border-white/[0.06] px-5 py-4 last:border-b-0 sm:px-6"><span className="font-mono text-xs text-primary">0{index + 1}</span><span className="font-medium">{item}</span>{index < text.simple.flow.length - 1 && <ArrowRight className="ml-auto h-4 w-4 text-slate-700" />}</div>)}</div></div>
            </div>
          </div>
        </section>

        <section id="calculator" className="scroll-mt-24 px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto max-w-7xl"><SectionHeading kicker={text.calculator.kicker} title={text.calculator.title} subtitle={text.calculator.subtitle} />
            <div className="grid overflow-hidden border border-white/[0.09] bg-[#0a1112] shadow-[0_35px_100px_rgba(0,0,0,0.25)] lg:grid-cols-[1.05fr_0.95fr]">
              <div className="p-5 sm:p-8 lg:p-10">
                <div className="mb-6 flex items-center gap-3 border-b border-white/[0.07] pb-5"><SlidersHorizontal className="h-4 w-4 text-primary" /><span className="text-sm font-medium">{ui.calculatorCaption}</span></div>
                <div className="grid gap-3 sm:grid-cols-2">
                  <CalculatorControl label={text.calculator.budget} value={budget} display={money(budget)} min={25} max={2000} step={25} onChange={setBudget} />
                  <CalculatorControl label={text.calculator.visitorCost} value={visitorCost} display={`$${visitorCost.toFixed(3)}`} min={0.005} max={0.2} step={0.005} onChange={setVisitorCost} />
                  <CalculatorControl label={text.calculator.conversionRate} value={conversionRate} display={`${conversionRate.toFixed(1)}%`} min={0.2} max={10} step={0.1} onChange={setConversionRate} />
                  <CalculatorControl label={text.calculator.payout} value={payout} display={money(payout)} min={0.1} max={20} step={0.1} onChange={setPayout} />
                </div>
              </div>
              <div className="flex flex-col justify-center border-t border-white/[0.08] bg-[radial-gradient(circle_at_top_right,hsl(var(--primary)/0.13),transparent_60%)] p-6 sm:p-10 lg:border-l lg:border-t-0">
                <div className="mb-5 flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary/70">{ui.liveResult}</div><div className="mt-1 text-sm font-medium">{ui.campaignReady}</div></div><Sparkles className="h-5 w-5 text-primary/60" /></div>
                <div className="grid grid-cols-2 gap-3">{[[text.calculator.visitors, result.visitors.toLocaleString("en-US")], [text.calculator.conversions, result.conversions.toLocaleString("en-US")], [text.calculator.revenue, money(result.revenue)], [text.calculator.roi, `${result.roi >= 0 ? "+" : ""}${result.roi.toFixed(0)}%`]].map(([label, value]) => <div key={label} className="border border-white/[0.08] bg-black/20 p-4"><div className="text-[9px] uppercase tracking-[0.14em] text-slate-600 sm:text-[10px]">{label}</div><div className="mt-2 break-words font-mono text-xl font-medium sm:text-2xl">{value}</div></div>)}</div>
                <div className="mt-3 border border-emerald-400/20 bg-emerald-400/[0.055] p-5 sm:p-6"><div className="text-xs text-emerald-200/55">{text.calculator.profit}</div><div className={`mt-2 break-words text-5xl font-light tracking-[-0.055em] sm:text-6xl ${result.profit >= 0 ? "text-emerald-300" : "text-red-400"}`}>{result.profit >= 0 ? "+" : ""}{money(result.profit)}</div></div>
                <div className="mt-6"><RegisterButton className="w-full">{text.calculator.cta}</RegisterButton></div>
              </div>
            </div>
          </div>
        </section>

        <section className="border-y border-white/[0.06] bg-[#091011] px-4 py-20 sm:px-6 sm:py-28">
          <div className="mx-auto max-w-7xl">
            <SectionHeading kicker={text.scenarios.kicker} title={text.scenarios.title} />
            <div className="grid gap-4 md:grid-cols-3">{text.scenarios.cards.map((card, index) => <article key={card[0]} className={`relative overflow-hidden border p-6 sm:p-8 ${index === 1 ? "border-primary/30 bg-primary/[0.065] shadow-[0_24px_70px_hsl(var(--primary)/0.07)]" : "border-white/[0.08] bg-[#0a1112]"}`}>{index === 1 && <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary to-transparent" />}<div className="flex items-center justify-between"><div className="text-sm font-medium text-slate-300">{card[0]}</div><span className="font-mono text-[10px] text-slate-600">0{index + 1}</span></div><div className="mt-7 space-y-3">{text.scenarios.labels.map((label, metricIndex) => <div key={label} className="flex justify-between gap-3 border-b border-white/[0.06] pb-3 last:border-b-0"><span className="text-sm text-slate-500">{label}</span><span className={`font-mono font-medium ${metricIndex >= 2 ? "text-emerald-300" : "text-slate-200"}`}>{card[metricIndex + 1]}</span></div>)}</div></article>)}</div>
          </div>
        </section>

        <section className="px-4 py-20 sm:px-6 sm:py-32">
          <div className="relative mx-auto max-w-5xl overflow-hidden border border-primary/20 bg-[#0a1213] px-5 py-16 text-center shadow-[0_35px_110px_rgba(0,0,0,0.38)] sm:px-12 sm:py-24">
            <div className="pointer-events-none absolute left-1/2 top-0 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/20 blur-[90px]" />
            <div className="relative"><div className="mx-auto flex h-12 w-12 items-center justify-center border border-primary/20 bg-primary/[0.07] text-primary"><Rocket className="h-5 w-5" /></div><div className="mt-6 font-mono text-[11px] font-semibold uppercase tracking-[0.2em] text-primary">{text.final.kicker}</div><h2 className="mx-auto mt-5 max-w-4xl text-balance text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-6xl">{text.final.title}</h2><p className="mx-auto mt-6 max-w-2xl text-sm leading-7 text-slate-400 sm:text-lg">{text.final.text}</p><div className="mt-8"><RegisterButton>{text.final.cta}</RegisterButton></div><p className="mt-3 text-xs text-slate-600">{text.final.note}</p></div>
          </div>
        </section>
      </main>

      <footer className="relative z-10 border-t border-white/[0.06] px-4 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-center sm:flex-row sm:text-left"><img src={twinbidLogo} alt="TwinBid" className="h-8" /><div className="text-xs text-slate-700">© 2026 TwinBid. Innovative Traffic Aggregator.</div></div></footer>
    </div>
  );
}
