// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: services/adv.proto

package advGrpc

import (
	ortb_V2_5 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest  `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoAuctionRequest) Reset() {
	*x = DoAuctionRequest{}
	mi := &file_services_adv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoAuctionRequest) ProtoMessage() {}

func (x *DoAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_adv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoAuctionRequest.ProtoReflect.Descriptor instead.
func (*DoAuctionRequest) Descriptor() ([]byte, []int) {
	return file_services_adv_proto_rawDescGZIP(), []int{0}
}

func (x *DoAuctionRequest) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

type DoAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selected      bool                   `protobuf:"varint,1,opt,name=selected,proto3" json:"selected,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CreativeId    string                 `protobuf:"bytes,3,opt,name=creative_id,json=creativeId,proto3" json:"creative_id,omitempty"`
	Adm           string                 `protobuf:"bytes,4,opt,name=adm,proto3" json:"adm,omitempty"`
	AuctionPrice  float64                `protobuf:"fixed64,5,opt,name=auction_price,json=auctionPrice,proto3" json:"auction_price,omitempty"`
	Code          int32                  `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoAuctionResponse) Reset() {
	*x = DoAuctionResponse{}
	mi := &file_services_adv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoAuctionResponse) ProtoMessage() {}

func (x *DoAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_adv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoAuctionResponse.ProtoReflect.Descriptor instead.
func (*DoAuctionResponse) Descriptor() ([]byte, []int) {
	return file_services_adv_proto_rawDescGZIP(), []int{1}
}

func (x *DoAuctionResponse) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *DoAuctionResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DoAuctionResponse) GetCreativeId() string {
	if x != nil {
		return x.CreativeId
	}
	return ""
}

func (x *DoAuctionResponse) GetAdm() string {
	if x != nil {
		return x.Adm
	}
	return ""
}

func (x *DoAuctionResponse) GetAuctionPrice() float64 {
	if x != nil {
		return x.AuctionPrice
	}
	return 0
}

func (x *DoAuctionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_services_adv_proto protoreflect.FileDescriptor

const file_services_adv_proto_rawDesc = "" +
	"\n" +
	"\x12services/adv.proto\x12\x03adv\x1a\x1atypes/ortb_V2_5/ortb.proto\"I\n" +
	"\x10DoAuctionRequest\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_5.BidRequestR\n" +
	"bidRequest\"\xbc\x01\n" +
	"\x11DoAuctionResponse\x12\x1a\n" +
	"\bselected\x18\x01 \x01(\bR\bselected\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x1f\n" +
	"\vcreative_id\x18\x03 \x01(\tR\n" +
	"creativeId\x12\x10\n" +
	"\x03adm\x18\x04 \x01(\tR\x03adm\x12#\n" +
	"\rauction_price\x18\x05 \x01(\x01R\fauctionPrice\x12\x12\n" +
	"\x04code\x18\x06 \x01(\x05R\x04code2J\n" +
	"\n" +
	"AdvService\x12<\n" +
	"\tDoAuction\x12\x15.adv.DoAuctionRequest\x1a\x16.adv.DoAuctionResponse\"\x00BSZQgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/adv;advGrpcb\x06proto3"

var (
	file_services_adv_proto_rawDescOnce sync.Once
	file_services_adv_proto_rawDescData []byte
)

func file_services_adv_proto_rawDescGZIP() []byte {
	file_services_adv_proto_rawDescOnce.Do(func() {
		file_services_adv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_adv_proto_rawDesc), len(file_services_adv_proto_rawDesc)))
	})
	return file_services_adv_proto_rawDescData
}

var file_services_adv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_adv_proto_goTypes = []any{
	(*DoAuctionRequest)(nil),     // 0: adv.DoAuctionRequest
	(*DoAuctionResponse)(nil),    // 1: adv.DoAuctionResponse
	(*ortb_V2_5.BidRequest)(nil), // 2: ortb_V2_5.BidRequest
}
var file_services_adv_proto_depIdxs = []int32{
	2, // 0: adv.DoAuctionRequest.bidRequest:type_name -> ortb_V2_5.BidRequest
	0, // 1: adv.AdvService.DoAuction:input_type -> adv.DoAuctionRequest
	1, // 2: adv.AdvService.DoAuction:output_type -> adv.DoAuctionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_adv_proto_init() }
func file_services_adv_proto_init() {
	if File_services_adv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_adv_proto_rawDesc), len(file_services_adv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_adv_proto_goTypes,
		DependencyIndexes: file_services_adv_proto_depIdxs,
		MessageInfos:      file_services_adv_proto_msgTypes,
	}.Build()
	File_services_adv_proto = out.File
	file_services_adv_proto_goTypes = nil
	file_services_adv_proto_depIdxs = nil
}
