// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/adv.proto

package advGrpc

import (
	ortb_V2_5 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest  `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	TrafficType   string                 `protobuf:"bytes,3,opt,name=traffic_type,json=trafficType,proto3" json:"traffic_type,omitempty"`
	SspDomain     string                 `protobuf:"bytes,4,opt,name=ssp_domain,json=sspDomain,proto3" json:"ssp_domain,omitempty"`
	ImpIdUuid     map[string]string      `protobuf:"bytes,5,rep,name=impIdUuid,proto3" json:"impIdUuid,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoAuctionRequest) Reset() {
	*x = DoAuctionRequest{}
	mi := &file_services_adv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoAuctionRequest) ProtoMessage() {}

func (x *DoAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_adv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoAuctionRequest.ProtoReflect.Descriptor instead.
func (*DoAuctionRequest) Descriptor() ([]byte, []int) {
	return file_services_adv_proto_rawDescGZIP(), []int{0}
}

func (x *DoAuctionRequest) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *DoAuctionRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DoAuctionRequest) GetTrafficType() string {
	if x != nil {
		return x.TrafficType
	}
	return ""
}

func (x *DoAuctionRequest) GetSspDomain() string {
	if x != nil {
		return x.SspDomain
	}
	return ""
}

func (x *DoAuctionRequest) GetImpIdUuid() map[string]string {
	if x != nil {
		return x.ImpIdUuid
	}
	return nil
}

type DoAuctionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CampaignId       string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CreativeId       string                 `protobuf:"bytes,3,opt,name=creative_id,json=creativeId,proto3" json:"creative_id,omitempty"`
	Adm              string                 `protobuf:"bytes,4,opt,name=adm,proto3" json:"adm,omitempty"`
	AuctionPrice     float64                `protobuf:"fixed64,5,opt,name=auction_price,json=auctionPrice,proto3" json:"auction_price,omitempty"`
	BidResponse      *ortb_V2_5.BidResponse `protobuf:"bytes,7,opt,name=bid_response,json=bidResponse,proto3" json:"bid_response,omitempty"`
	WinnerUserIds    map[string]string      `protobuf:"bytes,8,rep,name=winnerUserIds,proto3" json:"winnerUserIds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WinnerBasePrices map[string]float64     `protobuf:"bytes,9,rep,name=winnerBasePrices,proto3" json:"winnerBasePrices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DoAuctionResponse) Reset() {
	*x = DoAuctionResponse{}
	mi := &file_services_adv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoAuctionResponse) ProtoMessage() {}

func (x *DoAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_adv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoAuctionResponse.ProtoReflect.Descriptor instead.
func (*DoAuctionResponse) Descriptor() ([]byte, []int) {
	return file_services_adv_proto_rawDescGZIP(), []int{1}
}

func (x *DoAuctionResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *DoAuctionResponse) GetCreativeId() string {
	if x != nil {
		return x.CreativeId
	}
	return ""
}

func (x *DoAuctionResponse) GetAdm() string {
	if x != nil {
		return x.Adm
	}
	return ""
}

func (x *DoAuctionResponse) GetAuctionPrice() float64 {
	if x != nil {
		return x.AuctionPrice
	}
	return 0
}

func (x *DoAuctionResponse) GetBidResponse() *ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponse
	}
	return nil
}

func (x *DoAuctionResponse) GetWinnerUserIds() map[string]string {
	if x != nil {
		return x.WinnerUserIds
	}
	return nil
}

func (x *DoAuctionResponse) GetWinnerBasePrices() map[string]float64 {
	if x != nil {
		return x.WinnerBasePrices
	}
	return nil
}

var File_services_adv_proto protoreflect.FileDescriptor

const file_services_adv_proto_rawDesc = "\n\x12services/adv.proto\x12\x03adv\x1a\x1atypes/ortb_V2_5/ortb.proto\"\xb1\x02\n\x10DoAuctionRequest\x125\n\nbidRequest\x18\x01 \x01(\x0b2\x15.ortb_V2_5.BidRequestR\nbidRequest\x12\x16\n\x06format\x18\x02 \x01(\tR\x06format\x12!\n\x0ctraffic_type\x18\x03 \x01(\tR\x0btrafficType\x12\x1d\n\nssp_domain\x18\x04 \x01(\tR\tsspDomain\x12B\n\timpIdUuid\x18\x05 \x03(\x0b2$.adv.DoAuctionRequest.ImpIdUuidEntryR\timpIdUuid\x1a<\n\x0eImpIdUuidEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\x08\x06\x10\x07R\x04feed\"\x95\x04\n\x11DoAuctionResponse\x12\x1f\n\x0bcampaign_id\x18\x02 \x01(\tR\ncampaignId\x12\x1f\n\x0bcreative_id\x18\x03 \x01(\tR\ncreativeId\x12\x10\n\x03adm\x18\x04 \x01(\tR\x03adm\x12#\n\rauction_price\x18\x05 \x01(\x01R\x0cauctionPrice\x129\n\x0cbid_response\x18\x07 \x01(\x0b2\x16.ortb_V2_5.BidResponseR\x0bbidResponse\x12O\n\rwinnerUserIds\x18\x08 \x03(\x0b2).adv.DoAuctionResponse.WinnerUserIdsEntryR\rwinnerUserIds\x12X\n\x10winnerBasePrices\x18\t \x03(\x0b2,.adv.DoAuctionResponse.WinnerBasePricesEntryR\x10winnerBasePrices\x1a@\n\x12WinnerUserIdsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n\x15WinnerBasePricesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01J\x04\x08\x01\x10\x02J\x04\x08\x06\x10\x07R\x08selectedR\x04code2J\n\nAdvService\x12<\n\tDoAuction\x12\x15.adv.DoAuctionRequest\x1a\x16.adv.DoAuctionResponse\"\x00BSZQgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/adv;advGrpcb\x06proto3"

var (
	file_services_adv_proto_rawDescOnce sync.Once
	file_services_adv_proto_rawDescData []byte
)

func file_services_adv_proto_rawDescGZIP() []byte {
	file_services_adv_proto_rawDescOnce.Do(func() {
		file_services_adv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_adv_proto_rawDesc), len(file_services_adv_proto_rawDesc)))
	})
	return file_services_adv_proto_rawDescData
}

var file_services_adv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_adv_proto_goTypes = []any{
	(*DoAuctionRequest)(nil),      // 0: adv.DoAuctionRequest
	(*DoAuctionResponse)(nil),     // 1: adv.DoAuctionResponse
	nil,                           // 2: adv.DoAuctionRequest.ImpIdUuidEntry
	nil,                           // 3: adv.DoAuctionResponse.WinnerUserIdsEntry
	nil,                           // 4: adv.DoAuctionResponse.WinnerBasePricesEntry
	(*ortb_V2_5.BidRequest)(nil),  // 5: ortb_V2_5.BidRequest
	(*ortb_V2_5.BidResponse)(nil), // 6: ortb_V2_5.BidResponse
}
var file_services_adv_proto_depIdxs = []int32{
	5, // 0: adv.DoAuctionRequest.bidRequest:type_name -> ortb_V2_5.BidRequest
	2, // 1: adv.DoAuctionRequest.impIdUuid:type_name -> adv.DoAuctionRequest.ImpIdUuidEntry
	6, // 2: adv.DoAuctionResponse.bid_response:type_name -> ortb_V2_5.BidResponse
	3, // 3: adv.DoAuctionResponse.winnerUserIds:type_name -> adv.DoAuctionResponse.WinnerUserIdsEntry
	4, // 4: adv.DoAuctionResponse.winnerBasePrices:type_name -> adv.DoAuctionResponse.WinnerBasePricesEntry
	0, // 5: adv.AdvService.DoAuction:input_type -> adv.DoAuctionRequest
	1, // 6: adv.AdvService.DoAuction:output_type -> adv.DoAuctionResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_adv_proto_init() }
func file_services_adv_proto_init() {
	if File_services_adv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_adv_proto_rawDesc), len(file_services_adv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_adv_proto_goTypes,
		DependencyIndexes: file_services_adv_proto_depIdxs,
		MessageInfos:      file_services_adv_proto_msgTypes,
	}.Build()
	File_services_adv_proto = out.File
	file_services_adv_proto_goTypes = nil
	file_services_adv_proto_depIdxs = nil
}
