// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: services/adv.proto

package advGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdvService_DoAuction_FullMethodName = "/adv.AdvService/DoAuction"
)

// AdvServiceClient is the client API for AdvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdvServiceClient interface {
	DoAuction(ctx context.Context, in *DoAuctionRequest, opts ...grpc.CallOption) (*DoAuctionResponse, error)
}

type advServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvServiceClient(cc grpc.ClientConnInterface) AdvServiceClient {
	return &advServiceClient{cc}
}

func (c *advServiceClient) DoAuction(ctx context.Context, in *DoAuctionRequest, opts ...grpc.CallOption) (*DoAuctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoAuctionResponse)
	err := c.cc.Invoke(ctx, AdvService_DoAuction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvServiceServer is the server API for AdvService service.
// All implementations must embed UnimplementedAdvServiceServer
// for forward compatibility.
type AdvServiceServer interface {
	DoAuction(context.Context, *DoAuctionRequest) (*DoAuctionResponse, error)
	mustEmbedUnimplementedAdvServiceServer()
}

// UnimplementedAdvServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdvServiceServer struct{}

func (UnimplementedAdvServiceServer) DoAuction(context.Context, *DoAuctionRequest) (*DoAuctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DoAuction not implemented")
}
func (UnimplementedAdvServiceServer) mustEmbedUnimplementedAdvServiceServer() {}
func (UnimplementedAdvServiceServer) testEmbeddedByValue()                    {}

// UnsafeAdvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdvServiceServer will
// result in compilation errors.
type UnsafeAdvServiceServer interface {
	mustEmbedUnimplementedAdvServiceServer()
}

func RegisterAdvServiceServer(s grpc.ServiceRegistrar, srv AdvServiceServer) {
	// If the following call panics, it indicates UnimplementedAdvServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdvService_ServiceDesc, srv)
}

func _AdvService_DoAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvServiceServer).DoAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvService_DoAuction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvServiceServer).DoAuction(ctx, req.(*DoAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdvService_ServiceDesc is the grpc.ServiceDesc for AdvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adv.AdvService",
	HandlerType: (*AdvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoAuction",
			Handler:    _AdvService_DoAuction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/adv.proto",
}
