apiVersion: v1
kind: Service
metadata:
  name: bid-engine-service
  namespace: exchange
spec:
  selector:
    app: bid-engine
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
