apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: exchange
  labels:
    app: gateway
    component: edge
spec:
  type: ClusterIP
  selector:
    app: gateway
    component: edge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
