apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: exchange
  labels:
    app: gateway
    component: edge
spec:
  type: LoadBalancer
  selector:
    app: gateway
    component: edge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: bid-engine
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
    - name: orchestrator
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081
    - name: router
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31082
    - name: spp-adapter
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31083
    - name: ch-loader
      protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 31084
    - name: kafka-loader
      protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 31085
