apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: exchange
  labels:
    app: gateway
    component: edge
spec:
  type: LoadBalancer
  loadBalancerIP: 142.93.239.222
  selector:
    app: gateway
    component: edge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

