apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: exchange
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: client
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: controller
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: exchange
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: client
  selector:
    app: kafka
  type: ClusterIP
