apiVersion: v1
kind: Service
metadata:
  name: kafka-service-external
  namespace: exchange
  labels:
    app: kafka
    exposure: external
spec:
  type: LoadBalancer  # Меняем на LoadBalancer для единообразия
  selector:
    app: kafka
  ports:
    - name: broker
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30902