apiVersion: v1
kind: Service
metadata:
  name: kafka-service-external
  namespace: exchange
  labels:
    app: kafka
    exposure: external
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: client
      protocol: TCP
      port: 9092
      targetPort: 9092
  externalTrafficPolicy: Cluster
