apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: exchange
spec:
  selector:
    app: orchestrator
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
