apiVersion: v1
kind: Service
metadata:
  name: redis-service-external
  namespace: exchange
  labels:
    app: redis
    exposure: external
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  externalTrafficPolicy: Cluster
