apiVersion: v1
kind: Service
metadata:
  name: router-service-external
  namespace: exchange
  labels:
    app: router
    exposure: external
spec:
  type: NodePort
  selector:
    app: router
  ports:
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  externalTrafficPolicy: Cluster
