apiVersion: v1
kind: Service
metadata:
  name: router-service-external
  namespace: exchange
  labels:
    app: router
    exposure: external
spec:
  type: LoadBalancer
  selector:
    app: router
  ports:
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
  externalTrafficPolicy: Cluster
