apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: exchange
spec:
  selector:
    app: router
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
