// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: buffer/buffer.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]string      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponses) Reset() {
	*x = BidResponses{}
	mi := &file_buffer_buffer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponses) ProtoMessage() {}

func (x *BidResponses) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_buffer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponses.ProtoReflect.Descriptor instead.
func (*BidResponses) Descriptor() ([]byte, []int) {
	return file_buffer_buffer_proto_rawDescGZIP(), []int{0}
}

func (x *BidResponses) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrtbEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventTimeMs    int64                  `protobuf:"varint,2,opt,name=event_time_ms,json=eventTimeMs,proto3" json:"event_time_ms,omitempty"`
	Typic          string                 `protobuf:"bytes,3,opt,name=typic,proto3" json:"typic,omitempty"`
	Format         string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	SppDomain      string                 `protobuf:"bytes,5,opt,name=spp_domain,json=sppDomain,proto3" json:"spp_domain,omitempty"`
	Geo            string                 `protobuf:"bytes,6,opt,name=geo,proto3" json:"geo,omitempty"`
	CityId         uint32                 `protobuf:"varint,7,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	BidResponses   map[string]string      `protobuf:"bytes,8,rep,name=bid_responses,json=bidResponses,proto3" json:"bid_responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ip             string                 `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	Ipv6           string                 `protobuf:"bytes,10,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Lang           string                 `protobuf:"bytes,11,opt,name=lang,proto3" json:"lang,omitempty"`
	Browser        string                 `protobuf:"bytes,12,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion string                 `protobuf:"bytes,13,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	Os             string                 `protobuf:"bytes,14,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion      string                 `protobuf:"bytes,15,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Device         string                 `protobuf:"bytes,16,opt,name=device,proto3" json:"device,omitempty"`
	SiteId         string                 `protobuf:"bytes,17,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SiteDomain     string                 `protobuf:"bytes,18,opt,name=site_domain,json=siteDomain,proto3" json:"site_domain,omitempty"`
	BidFloor       float64                `protobuf:"fixed64,19,opt,name=bid_floor,json=bidFloor,proto3" json:"bid_floor,omitempty"`
	WinDspDomain   string                 `protobuf:"bytes,20,opt,name=win_dsp_domain,json=winDspDomain,proto3" json:"win_dsp_domain,omitempty"`
	WinPrice       float64                `protobuf:"fixed64,21,opt,name=win_price,json=winPrice,proto3" json:"win_price,omitempty"`
	WinDspPrice    float64                `protobuf:"fixed64,22,opt,name=win_dsp_price,json=winDspPrice,proto3" json:"win_dsp_price,omitempty"`
	WinCid         string                 `protobuf:"bytes,23,opt,name=win_cid,json=winCid,proto3" json:"win_cid,omitempty"`
	WinCrid        string                 `protobuf:"bytes,24,opt,name=win_crid,json=winCrid,proto3" json:"win_crid,omitempty"`
	WinUserId      string                 `protobuf:"bytes,25,opt,name=win_user_id,json=winUserId,proto3" json:"win_user_id,omitempty"`
	Code           uint32                 `protobuf:"varint,26,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrtbEvent) Reset() {
	*x = OrtbEvent{}
	mi := &file_buffer_buffer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrtbEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrtbEvent) ProtoMessage() {}

func (x *OrtbEvent) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_buffer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrtbEvent.ProtoReflect.Descriptor instead.
func (*OrtbEvent) Descriptor() ([]byte, []int) {
	return file_buffer_buffer_proto_rawDescGZIP(), []int{1}
}

func (x *OrtbEvent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *OrtbEvent) GetEventTimeMs() int64 {
	if x != nil {
		return x.EventTimeMs
	}
	return 0
}

func (x *OrtbEvent) GetTypic() string {
	if x != nil {
		return x.Typic
	}
	return ""
}

func (x *OrtbEvent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *OrtbEvent) GetSppDomain() string {
	if x != nil {
		return x.SppDomain
	}
	return ""
}

func (x *OrtbEvent) GetGeo() string {
	if x != nil {
		return x.Geo
	}
	return ""
}

func (x *OrtbEvent) GetCityId() uint32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *OrtbEvent) GetBidResponses() map[string]string {
	if x != nil {
		return x.BidResponses
	}
	return nil
}

func (x *OrtbEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OrtbEvent) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *OrtbEvent) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *OrtbEvent) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *OrtbEvent) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *OrtbEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *OrtbEvent) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *OrtbEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *OrtbEvent) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *OrtbEvent) GetSiteDomain() string {
	if x != nil {
		return x.SiteDomain
	}
	return ""
}

func (x *OrtbEvent) GetBidFloor() float64 {
	if x != nil {
		return x.BidFloor
	}
	return 0
}

func (x *OrtbEvent) GetWinDspDomain() string {
	if x != nil {
		return x.WinDspDomain
	}
	return ""
}

func (x *OrtbEvent) GetWinPrice() float64 {
	if x != nil {
		return x.WinPrice
	}
	return 0
}

func (x *OrtbEvent) GetWinDspPrice() float64 {
	if x != nil {
		return x.WinDspPrice
	}
	return 0
}

func (x *OrtbEvent) GetWinCid() string {
	if x != nil {
		return x.WinCid
	}
	return ""
}

func (x *OrtbEvent) GetWinCrid() string {
	if x != nil {
		return x.WinCrid
	}
	return ""
}

func (x *OrtbEvent) GetWinUserId() string {
	if x != nil {
		return x.WinUserId
	}
	return ""
}

func (x *OrtbEvent) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ImpressionEvent struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ImpressionsUuid        string                 `protobuf:"bytes,1,opt,name=impressions_uuid,json=impressionsUuid,proto3" json:"impressions_uuid,omitempty"`
	OrtbUuid               string                 `protobuf:"bytes,2,opt,name=ortb_uuid,json=ortbUuid,proto3" json:"ortb_uuid,omitempty"`
	EventTimeImpressionsMs int64                  `protobuf:"varint,3,opt,name=event_time_impressions_ms,json=eventTimeImpressionsMs,proto3" json:"event_time_impressions_ms,omitempty"`
	Format                 string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImpressionEvent) Reset() {
	*x = ImpressionEvent{}
	mi := &file_buffer_buffer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpressionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpressionEvent) ProtoMessage() {}

func (x *ImpressionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_buffer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpressionEvent.ProtoReflect.Descriptor instead.
func (*ImpressionEvent) Descriptor() ([]byte, []int) {
	return file_buffer_buffer_proto_rawDescGZIP(), []int{2}
}

func (x *ImpressionEvent) GetImpressionsUuid() string {
	if x != nil {
		return x.ImpressionsUuid
	}
	return ""
}

func (x *ImpressionEvent) GetOrtbUuid() string {
	if x != nil {
		return x.OrtbUuid
	}
	return ""
}

func (x *ImpressionEvent) GetEventTimeImpressionsMs() int64 {
	if x != nil {
		return x.EventTimeImpressionsMs
	}
	return 0
}

func (x *ImpressionEvent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ClickEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClicksUuid        string                 `protobuf:"bytes,1,opt,name=clicks_uuid,json=clicksUuid,proto3" json:"clicks_uuid,omitempty"`
	OrtbUuid          string                 `protobuf:"bytes,2,opt,name=ortb_uuid,json=ortbUuid,proto3" json:"ortb_uuid,omitempty"`
	EventTimeClicksMs int64                  `protobuf:"varint,3,opt,name=event_time_clicks_ms,json=eventTimeClicksMs,proto3" json:"event_time_clicks_ms,omitempty"`
	Format            string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_buffer_buffer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_buffer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_buffer_buffer_proto_rawDescGZIP(), []int{3}
}

func (x *ClickEvent) GetClicksUuid() string {
	if x != nil {
		return x.ClicksUuid
	}
	return ""
}

func (x *ClickEvent) GetOrtbUuid() string {
	if x != nil {
		return x.OrtbUuid
	}
	return ""
}

func (x *ClickEvent) GetEventTimeClicksMs() int64 {
	if x != nil {
		return x.EventTimeClicksMs
	}
	return 0
}

func (x *ClickEvent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_buffer_buffer_proto protoreflect.FileDescriptor

const file_buffer_buffer_proto_rawDesc = "" +
	"\n" +
	"\x13buffer/buffer.proto\x12\x06events\"\x7f\n" +
	"\fBidResponses\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.events.BidResponses.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x06\n" +
	"\tOrtbEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\"\n" +
	"\revent_time_ms\x18\x02 \x01(\x03R\veventTimeMs\x12\x14\n" +
	"\x05typic\x18\x03 \x01(\tR\x05typic\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"spp_domain\x18\x05 \x01(\tR\tsppDomain\x12\x10\n" +
	"\x03geo\x18\x06 \x01(\tR\x03geo\x12\x17\n" +
	"\acity_id\x18\a \x01(\rR\x06cityId\x12H\n" +
	"\rbid_responses\x18\b \x03(\v2#.events.OrtbEvent.BidResponsesEntryR\fbidResponses\x12\x0e\n" +
	"\x02ip\x18\t \x01(\tR\x02ip\x12\x12\n" +
	"\x04ipv6\x18\n" +
	" \x01(\tR\x04ipv6\x12\x12\n" +
	"\x04lang\x18\v \x01(\tR\x04lang\x12\x18\n" +
	"\abrowser\x18\f \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\r \x01(\tR\x0ebrowserVersion\x12\x0e\n" +
	"\x02os\x18\x0e \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x0f \x01(\tR\tosVersion\x12\x16\n" +
	"\x06device\x18\x10 \x01(\tR\x06device\x12\x17\n" +
	"\asite_id\x18\x11 \x01(\tR\x06siteId\x12\x1f\n" +
	"\vsite_domain\x18\x12 \x01(\tR\n" +
	"siteDomain\x12\x1b\n" +
	"\tbid_floor\x18\x13 \x01(\x01R\bbidFloor\x12$\n" +
	"\x0ewin_dsp_domain\x18\x14 \x01(\tR\fwinDspDomain\x12\x1b\n" +
	"\twin_price\x18\x15 \x01(\x01R\bwinPrice\x12\"\n" +
	"\rwin_dsp_price\x18\x16 \x01(\x01R\vwinDspPrice\x12\x17\n" +
	"\awin_cid\x18\x17 \x01(\tR\x06winCid\x12\x19\n" +
	"\bwin_crid\x18\x18 \x01(\tR\awinCrid\x12\x1e\n" +
	"\vwin_user_id\x18\x19 \x01(\tR\twinUserId\x12\x12\n" +
	"\x04code\x18\x1a \x01(\rR\x04code\x1a?\n" +
	"\x11BidResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x0fImpressionEvent\x12)\n" +
	"\x10impressions_uuid\x18\x01 \x01(\tR\x0fimpressionsUuid\x12\x1b\n" +
	"\tortb_uuid\x18\x02 \x01(\tR\bortbUuid\x129\n" +
	"\x19event_time_impressions_ms\x18\x03 \x01(\x03R\x16eventTimeImpressionsMs\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\x93\x01\n" +
	"\n" +
	"ClickEvent\x12\x1f\n" +
	"\vclicks_uuid\x18\x01 \x01(\tR\n" +
	"clicksUuid\x12\x1b\n" +
	"\tortb_uuid\x18\x02 \x01(\tR\bortbUuid\x12/\n" +
	"\x14event_time_clicks_ms\x18\x03 \x01(\x03R\x11eventTimeClicksMs\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06formatBNZLgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/buffer;eventspbb\x06proto3"

var (
	file_buffer_buffer_proto_rawDescOnce sync.Once
	file_buffer_buffer_proto_rawDescData []byte
)

func file_buffer_buffer_proto_rawDescGZIP() []byte {
	file_buffer_buffer_proto_rawDescOnce.Do(func() {
		file_buffer_buffer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buffer_buffer_proto_rawDesc), len(file_buffer_buffer_proto_rawDesc)))
	})
	return file_buffer_buffer_proto_rawDescData
}

var file_buffer_buffer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_buffer_buffer_proto_goTypes = []any{
	(*BidResponses)(nil),    // 0: events.BidResponses
	(*OrtbEvent)(nil),       // 1: events.OrtbEvent
	(*ImpressionEvent)(nil), // 2: events.ImpressionEvent
	(*ClickEvent)(nil),      // 3: events.ClickEvent
	nil,                     // 4: events.BidResponses.ItemsEntry
	nil,                     // 5: events.OrtbEvent.BidResponsesEntry
}
var file_buffer_buffer_proto_depIdxs = []int32{
	4, // 0: events.BidResponses.items:type_name -> events.BidResponses.ItemsEntry
	5, // 1: events.OrtbEvent.bid_responses:type_name -> events.OrtbEvent.BidResponsesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_buffer_buffer_proto_init() }
func file_buffer_buffer_proto_init() {
	if File_buffer_buffer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buffer_buffer_proto_rawDesc), len(file_buffer_buffer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buffer_buffer_proto_goTypes,
		DependencyIndexes: file_buffer_buffer_proto_depIdxs,
		MessageInfos:      file_buffer_buffer_proto_msgTypes,
	}.Build()
	File_buffer_buffer_proto = out.File
	file_buffer_buffer_proto_goTypes = nil
	file_buffer_buffer_proto_depIdxs = nil
}
