// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buffer/clicks_wins.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClicksWinEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClicksWinsUuid        string                 `protobuf:"bytes,1,opt,name=clicks_wins_uuid,json=clicksWinsUuid,proto3" json:"clicks_wins_uuid,omitempty"`
	OrtbUuid              string                 `protobuf:"bytes,2,opt,name=ortb_uuid,json=ortbUuid,proto3" json:"ortb_uuid,omitempty"`
	EventTimeClicksWinsMs int64                  `protobuf:"varint,3,opt,name=event_time_clicks_wins_ms,json=eventTimeClicksWinsMs,proto3" json:"event_time_clicks_wins_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClicksWinEvent) Reset() {
	*x = ClicksWinEvent{}
	mi := &file_buffer_clicks_wins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClicksWinEvent) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ClicksWinEvent) ProtoMessage()    {}
func (x *ClicksWinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_clicks_wins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClicksWinEvent.ProtoReflect.Descriptor instead.
func (*ClicksWinEvent) Descriptor() ([]byte, []int) {
	return file_buffer_clicks_wins_proto_rawDescGZIP(), []int{0}
}

func (x *ClicksWinEvent) GetClicksWinsUuid() string {
	if x != nil {
		return x.ClicksWinsUuid
	}
	return ""
}
func (x *ClicksWinEvent) GetOrtbUuid() string {
	if x != nil {
		return x.OrtbUuid
	}
	return ""
}
func (x *ClicksWinEvent) GetEventTimeClicksWinsMs() int64 {
	if x != nil {
		return x.EventTimeClicksWinsMs
	}
	return 0
}

var File_buffer_clicks_wins_proto protoreflect.FileDescriptor

var file_buffer_clicks_wins_proto_rawDesc = []byte{0x0a, 0x18, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x57, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x73, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x57, 0x69, 0x6e, 0x73, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x74, 0x62, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x74, 0x62, 0x55, 0x75, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x19, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x73, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x57, 0x69, 0x6e, 0x73, 0x4d, 0x73, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x62, 0x69, 0x64, 0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x52, 0x54, 0x42, 0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33}

var (
	file_buffer_clicks_wins_proto_rawDescOnce sync.Once
	file_buffer_clicks_wins_proto_rawDescData = file_buffer_clicks_wins_proto_rawDesc
)

func file_buffer_clicks_wins_proto_rawDescGZIP() []byte {
	file_buffer_clicks_wins_proto_rawDescOnce.Do(func() {
		file_buffer_clicks_wins_proto_rawDescData = protoimpl.X.CompressGZIP(file_buffer_clicks_wins_proto_rawDescData)
	})
	return file_buffer_clicks_wins_proto_rawDescData
}

var file_buffer_clicks_wins_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_buffer_clicks_wins_proto_goTypes = []any{
	(*ClicksWinEvent)(nil), // 0: events.ClicksWinEvent
}

func init() { file_buffer_clicks_wins_proto_init() }
func file_buffer_clicks_wins_proto_init() {
	if File_buffer_clicks_wins_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buffer_clicks_wins_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ClicksWinEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buffer_clicks_wins_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:      file_buffer_clicks_wins_proto_goTypes,
		MessageInfos: file_buffer_clicks_wins_proto_msgTypes,
	}.Build()
	File_buffer_clicks_wins_proto = out.File
	file_buffer_clicks_wins_proto_rawDesc = nil
	file_buffer_clicks_wins_proto_goTypes = nil
}
