// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: buffer/clicks_wins.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClicksWinEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClicksWinsUuid        string                 `protobuf:"bytes,1,opt,name=clicks_wins_uuid,json=clicksWinsUuid,proto3" json:"clicks_wins_uuid,omitempty"`
	OrtbUuid              string                 `protobuf:"bytes,2,opt,name=ortb_uuid,json=ortbUuid,proto3" json:"ortb_uuid,omitempty"`
	EventTimeClicksWinsMs int64                  `protobuf:"varint,3,opt,name=event_time_clicks_wins_ms,json=eventTimeClicksWinsMs,proto3" json:"event_time_clicks_wins_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClicksWinEvent) Reset() {
	*x = ClicksWinEvent{}
	mi := &file_buffer_clicks_wins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClicksWinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClicksWinEvent) ProtoMessage() {}

func (x *ClicksWinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_clicks_wins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClicksWinEvent.ProtoReflect.Descriptor instead.
func (*ClicksWinEvent) Descriptor() ([]byte, []int) {
	return file_buffer_clicks_wins_proto_rawDescGZIP(), []int{0}
}

func (x *ClicksWinEvent) GetClicksWinsUuid() string {
	if x != nil {
		return x.ClicksWinsUuid
	}
	return ""
}

func (x *ClicksWinEvent) GetOrtbUuid() string {
	if x != nil {
		return x.OrtbUuid
	}
	return ""
}

func (x *ClicksWinEvent) GetEventTimeClicksWinsMs() int64 {
	if x != nil {
		return x.EventTimeClicksWinsMs
	}
	return 0
}

var File_buffer_clicks_wins_proto protoreflect.FileDescriptor

const file_buffer_clicks_wins_proto_rawDesc = "" +
	"\n" +
	"\x18buffer/clicks_wins.proto\x12\x06events\"\x91\x01\n" +
	"\x0eClicksWinEvent\x12(\n" +
	"\x10clicks_wins_uuid\x18\x01 \x01(\tR\x0eclicksWinsUuid\x12\x1b\n" +
	"\tortb_uuid\x18\x02 \x01(\tR\bortbUuid\x128\n" +
	"\x19event_time_clicks_wins_ms\x18\x03 \x01(\x03R\x15eventTimeClicksWinsMsBNZLgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/buffer;eventspbb\x06proto3"

var (
	file_buffer_clicks_wins_proto_rawDescOnce sync.Once
	file_buffer_clicks_wins_proto_rawDescData []byte
)

func file_buffer_clicks_wins_proto_rawDescGZIP() []byte {
	file_buffer_clicks_wins_proto_rawDescOnce.Do(func() {
		file_buffer_clicks_wins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buffer_clicks_wins_proto_rawDesc), len(file_buffer_clicks_wins_proto_rawDesc)))
	})
	return file_buffer_clicks_wins_proto_rawDescData
}

var file_buffer_clicks_wins_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_buffer_clicks_wins_proto_goTypes = []any{
	(*ClicksWinEvent)(nil), // 0: events.ClicksWinEvent
}
var file_buffer_clicks_wins_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buffer_clicks_wins_proto_init() }
func file_buffer_clicks_wins_proto_init() {
	if File_buffer_clicks_wins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buffer_clicks_wins_proto_rawDesc), len(file_buffer_clicks_wins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buffer_clicks_wins_proto_goTypes,
		DependencyIndexes: file_buffer_clicks_wins_proto_depIdxs,
		MessageInfos:      file_buffer_clicks_wins_proto_msgTypes,
	}.Build()
	File_buffer_clicks_wins_proto = out.File
	file_buffer_clicks_wins_proto_goTypes = nil
	file_buffer_clicks_wins_proto_depIdxs = nil
}
