apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: exchange
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
              name: client
            - containerPort: 9093
              name: controller
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-headless.exchange.svc.cluster.local:9093"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: kafka-data
          emptyDir: {}
