// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: types/ortb_V2_5/ortb.proto

package ortb_V2_5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	At            *int32                 `protobuf:"varint,2,opt,name=at,proto3,oneof" json:"at,omitempty"`
	Imp           []*Imp                 `protobuf:"bytes,3,rep,name=imp,proto3" json:"imp,omitempty"`
	Device        *Device                `protobuf:"bytes,4,opt,name=device,proto3,oneof" json:"device,omitempty"`
	Site          *Site                  `protobuf:"bytes,5,opt,name=site,proto3,oneof" json:"site,omitempty"`
	User          *User                  `protobuf:"bytes,6,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Tmax          *int32                 `protobuf:"varint,7,opt,name=tmax,proto3,oneof" json:"tmax,omitempty"`
	Cur           []string               `protobuf:"bytes,8,rep,name=cur,proto3" json:"cur,omitempty"`
	Bcat          []string               `protobuf:"bytes,9,rep,name=bcat,proto3" json:"bcat,omitempty"`
	Test          *int32                 `protobuf:"varint,10,opt,name=test,proto3,oneof" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BidRequest) GetAt() int32 {
	if x != nil && x.At != nil {
		return *x.At
	}
	return 0
}

func (x *BidRequest) GetImp() []*Imp {
	if x != nil {
		return x.Imp
	}
	return nil
}

func (x *BidRequest) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BidRequest) GetSite() *Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *BidRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BidRequest) GetTmax() int32 {
	if x != nil && x.Tmax != nil {
		return *x.Tmax
	}
	return 0
}

func (x *BidRequest) GetCur() []string {
	if x != nil {
		return x.Cur
	}
	return nil
}

func (x *BidRequest) GetBcat() []string {
	if x != nil {
		return x.Bcat
	}
	return nil
}

func (x *BidRequest) GetTest() int32 {
	if x != nil && x.Test != nil {
		return *x.Test
	}
	return 0
}

type Imp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Bidfloor      *float32               `protobuf:"fixed32,2,opt,name=bidfloor,proto3,oneof" json:"bidfloor,omitempty"`
	Tagid         *string                `protobuf:"bytes,3,opt,name=tagid,proto3,oneof" json:"tagid,omitempty"`
	Secure        *int32                 `protobuf:"varint,4,opt,name=secure,proto3,oneof" json:"secure,omitempty"`
	Instl         *int32                 `protobuf:"varint,5,opt,name=instl,proto3,oneof" json:"instl,omitempty"`
	Bidfloorcur   *string                `protobuf:"bytes,6,opt,name=bidfloorcur,proto3,oneof" json:"bidfloorcur,omitempty"`
	Ext           *Imp_Ext               `protobuf:"bytes,7,opt,name=ext,proto3,oneof" json:"ext,omitempty"`
	Banner        *Banner                `protobuf:"bytes,8,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	Native        *Native                `protobuf:"bytes,9,opt,name=native,proto3,oneof" json:"native,omitempty"` // только request и ver
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Imp) Reset() {
	*x = Imp{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Imp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imp) ProtoMessage() {}

func (x *Imp) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imp.ProtoReflect.Descriptor instead.
func (*Imp) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{1}
}

func (x *Imp) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Imp) GetBidfloor() float32 {
	if x != nil && x.Bidfloor != nil {
		return *x.Bidfloor
	}
	return 0
}

func (x *Imp) GetTagid() string {
	if x != nil && x.Tagid != nil {
		return *x.Tagid
	}
	return ""
}

func (x *Imp) GetSecure() int32 {
	if x != nil && x.Secure != nil {
		return *x.Secure
	}
	return 0
}

func (x *Imp) GetInstl() int32 {
	if x != nil && x.Instl != nil {
		return *x.Instl
	}
	return 0
}

func (x *Imp) GetBidfloorcur() string {
	if x != nil && x.Bidfloorcur != nil {
		return *x.Bidfloorcur
	}
	return ""
}

func (x *Imp) GetExt() *Imp_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *Imp) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Imp) GetNative() *Native {
	if x != nil {
		return x.Native
	}
	return nil
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             *int32                 `protobuf:"varint,1,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H             *int32                 `protobuf:"varint,2,opt,name=h,proto3,oneof" json:"h,omitempty"`
	Pos           *int32                 `protobuf:"varint,3,opt,name=pos,proto3,oneof" json:"pos,omitempty"`
	Mimes         []string               `protobuf:"bytes,4,rep,name=mimes,proto3" json:"mimes,omitempty"`
	Api           *string                `protobuf:"bytes,5,opt,name=api,proto3,oneof" json:"api,omitempty"`
	Topframe      *int32                 `protobuf:"varint,6,opt,name=topframe,proto3,oneof" json:"topframe,omitempty"`
	Btype         []int32                `protobuf:"varint,7,rep,packed,name=btype,proto3" json:"btype,omitempty"`
	Battr         []int32                `protobuf:"varint,8,rep,packed,name=battr,proto3" json:"battr,omitempty"`
	Ext           []string               `protobuf:"bytes,9,rep,name=ext,proto3" json:"ext,omitempty"`
	Format        []*Format              `protobuf:"bytes,10,rep,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{2}
}

func (x *Banner) GetW() int32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *Banner) GetH() int32 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

func (x *Banner) GetPos() int32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *Banner) GetMimes() []string {
	if x != nil {
		return x.Mimes
	}
	return nil
}

func (x *Banner) GetApi() string {
	if x != nil && x.Api != nil {
		return *x.Api
	}
	return ""
}

func (x *Banner) GetTopframe() int32 {
	if x != nil && x.Topframe != nil {
		return *x.Topframe
	}
	return 0
}

func (x *Banner) GetBtype() []int32 {
	if x != nil {
		return x.Btype
	}
	return nil
}

func (x *Banner) GetBattr() []int32 {
	if x != nil {
		return x.Battr
	}
	return nil
}

func (x *Banner) GetExt() []string {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *Banner) GetFormat() []*Format {
	if x != nil {
		return x.Format
	}
	return nil
}

type Format struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             *int32                 `protobuf:"varint,1,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H             *int32                 `protobuf:"varint,2,opt,name=h,proto3,oneof" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Format) Reset() {
	*x = Format{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Format) ProtoMessage() {}

func (x *Format) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Format.ProtoReflect.Descriptor instead.
func (*Format) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{3}
}

func (x *Format) GetW() int32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *Format) GetH() int32 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

type Native struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *string                `protobuf:"bytes,1,opt,name=request,proto3,oneof" json:"request,omitempty"` // JSON строка
	Ver           *string                `protobuf:"bytes,2,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Native) Reset() {
	*x = Native{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Native) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Native) ProtoMessage() {}

func (x *Native) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Native.ProtoReflect.Descriptor instead.
func (*Native) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{4}
}

func (x *Native) GetRequest() string {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return ""
}

func (x *Native) GetVer() string {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return ""
}

type Imp_Ext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subid         *string                `protobuf:"bytes,1,opt,name=subid,proto3,oneof" json:"subid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Imp_Ext) Reset() {
	*x = Imp_Ext{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Imp_Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imp_Ext) ProtoMessage() {}

func (x *Imp_Ext) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imp_Ext.ProtoReflect.Descriptor instead.
func (*Imp_Ext) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{5}
}

func (x *Imp_Ext) GetSubid() string {
	if x != nil && x.Subid != nil {
		return *x.Subid
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             *string                `protobuf:"bytes,1,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Geo            *Geo                   `protobuf:"bytes,2,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	Ua             *string                `protobuf:"bytes,3,opt,name=ua,proto3,oneof" json:"ua,omitempty"`
	Js             *int32                 `protobuf:"varint,4,opt,name=js,proto3,oneof" json:"js,omitempty"`
	Language       *string                `protobuf:"bytes,5,opt,name=language,proto3,oneof" json:"language,omitempty"`
	DeviceExt      *Ext                   `protobuf:"bytes,6,opt,name=device_ext,json=deviceExt,proto3,oneof" json:"device_ext,omitempty"`
	Ipv6           *string                `protobuf:"bytes,7,opt,name=ipv6,proto3,oneof" json:"ipv6,omitempty"`
	Connectiontype *int32                 `protobuf:"varint,8,opt,name=connectiontype,proto3,oneof" json:"connectiontype,omitempty"`
	Carrier        *string                `protobuf:"bytes,9,opt,name=carrier,proto3,oneof" json:"carrier,omitempty"`
	Os             *string                `protobuf:"bytes,10,opt,name=os,proto3,oneof" json:"os,omitempty"`
	DeviceType     *int32                 `protobuf:"varint,11,opt,name=deviceType,proto3,oneof" json:"deviceType,omitempty"`
	W              *int32                 `protobuf:"varint,12,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H              *int32                 `protobuf:"varint,13,opt,name=h,proto3,oneof" json:"h,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{6}
}

func (x *Device) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Device) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *Device) GetUa() string {
	if x != nil && x.Ua != nil {
		return *x.Ua
	}
	return ""
}

func (x *Device) GetJs() int32 {
	if x != nil && x.Js != nil {
		return *x.Js
	}
	return 0
}

func (x *Device) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *Device) GetDeviceExt() *Ext {
	if x != nil {
		return x.DeviceExt
	}
	return nil
}

func (x *Device) GetIpv6() string {
	if x != nil && x.Ipv6 != nil {
		return *x.Ipv6
	}
	return ""
}

func (x *Device) GetConnectiontype() int32 {
	if x != nil && x.Connectiontype != nil {
		return *x.Connectiontype
	}
	return 0
}

func (x *Device) GetCarrier() string {
	if x != nil && x.Carrier != nil {
		return *x.Carrier
	}
	return ""
}

func (x *Device) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *Device) GetDeviceType() int32 {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return 0
}

func (x *Device) GetW() int32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *Device) GetH() int32 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

type Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *string                `protobuf:"bytes,1,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Lat           *float32               `protobuf:"fixed32,2,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float32               `protobuf:"fixed32,3,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Region        *string                `protobuf:"bytes,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	City          *string                `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Zip           *string                `protobuf:"bytes,6,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	Type          *int32                 `protobuf:"varint,7,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geo) Reset() {
	*x = Geo{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geo) ProtoMessage() {}

func (x *Geo) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geo.ProtoReflect.Descriptor instead.
func (*Geo) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{7}
}

func (x *Geo) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Geo) GetLat() float32 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Geo) GetLon() float32 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Geo) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *Geo) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Geo) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

func (x *Geo) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Page          *string                `protobuf:"bytes,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Domain        *string                `protobuf:"bytes,4,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	Ref           *string                `protobuf:"bytes,5,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	Cat           []string               `protobuf:"bytes,6,rep,name=cat,proto3" json:"cat,omitempty"`
	Publisher     *Publisher             `protobuf:"bytes,7,opt,name=publisher,proto3,oneof" json:"publisher,omitempty"`
	Keywords      *string                `protobuf:"bytes,8,opt,name=keywords,proto3,oneof" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{8}
}

func (x *Site) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Site) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Site) GetPage() string {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return ""
}

func (x *Site) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *Site) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

func (x *Site) GetCat() []string {
	if x != nil {
		return x.Cat
	}
	return nil
}

func (x *Site) GetPublisher() *Publisher {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *Site) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

type Publisher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{9}
}

func (x *Publisher) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Publisher) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Keywords      *string                `protobuf:"bytes,2,opt,name=keywords,proto3,oneof" json:"keywords,omitempty"`
	Buyeruid      *string                `protobuf:"bytes,3,opt,name=buyeruid,proto3,oneof" json:"buyeruid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *User) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

func (x *User) GetBuyeruid() string {
	if x != nil && x.Buyeruid != nil {
		return *x.Buyeruid
	}
	return ""
}

type SeatBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           []*Bid                 `protobuf:"bytes,1,rep,name=bid,proto3" json:"bid,omitempty"`
	Seat          *string                `protobuf:"bytes,2,opt,name=seat,proto3,oneof" json:"seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatBid) Reset() {
	*x = SeatBid{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatBid) ProtoMessage() {}

func (x *SeatBid) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatBid.ProtoReflect.Descriptor instead.
func (*SeatBid) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{11}
}

func (x *SeatBid) GetBid() []*Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *SeatBid) GetSeat() string {
	if x != nil && x.Seat != nil {
		return *x.Seat
	}
	return ""
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Impid         *string                `protobuf:"bytes,2,opt,name=impid,proto3,oneof" json:"impid,omitempty"`
	Price         *float32               `protobuf:"fixed32,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Adid          *string                `protobuf:"bytes,4,opt,name=adid,proto3,oneof" json:"adid,omitempty"`
	Nurl          *string                `protobuf:"bytes,5,opt,name=nurl,proto3,oneof" json:"nurl,omitempty"`
	Burl          *string                `protobuf:"bytes,6,opt,name=burl,proto3,oneof" json:"burl,omitempty"`
	Adm           *string                `protobuf:"bytes,7,opt,name=adm,proto3,oneof" json:"adm,omitempty"` // просто строка, хоть нативка хоть баннер
	Adomain       []string               `protobuf:"bytes,8,rep,name=adomain,proto3" json:"adomain,omitempty"`
	Bundle        *string                `protobuf:"bytes,9,opt,name=bundle,proto3,oneof" json:"bundle,omitempty"`
	Iurl          *string                `protobuf:"bytes,10,opt,name=iurl,proto3,oneof" json:"iurl,omitempty"`
	Cid           *string                `protobuf:"bytes,11,opt,name=cid,proto3,oneof" json:"cid,omitempty"`
	Crid          *string                `protobuf:"bytes,12,opt,name=crid,proto3,oneof" json:"crid,omitempty"`
	Attr          []int32                `protobuf:"varint,13,rep,packed,name=attr,proto3" json:"attr,omitempty"`
	Dealid        *string                `protobuf:"bytes,14,opt,name=dealid,proto3,oneof" json:"dealid,omitempty"`
	W             *int32                 `protobuf:"varint,15,opt,name=w,proto3,oneof" json:"w,omitempty"`
	H             *int32                 `protobuf:"varint,16,opt,name=h,proto3,oneof" json:"h,omitempty"`
	Ext           *BidExt                `protobuf:"bytes,17,opt,name=ext,proto3,oneof" json:"ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{12}
}

func (x *Bid) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Bid) GetImpid() string {
	if x != nil && x.Impid != nil {
		return *x.Impid
	}
	return ""
}

func (x *Bid) GetPrice() float32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Bid) GetAdid() string {
	if x != nil && x.Adid != nil {
		return *x.Adid
	}
	return ""
}

func (x *Bid) GetNurl() string {
	if x != nil && x.Nurl != nil {
		return *x.Nurl
	}
	return ""
}

func (x *Bid) GetBurl() string {
	if x != nil && x.Burl != nil {
		return *x.Burl
	}
	return ""
}

func (x *Bid) GetAdm() string {
	if x != nil && x.Adm != nil {
		return *x.Adm
	}
	return ""
}

func (x *Bid) GetAdomain() []string {
	if x != nil {
		return x.Adomain
	}
	return nil
}

func (x *Bid) GetBundle() string {
	if x != nil && x.Bundle != nil {
		return *x.Bundle
	}
	return ""
}

func (x *Bid) GetIurl() string {
	if x != nil && x.Iurl != nil {
		return *x.Iurl
	}
	return ""
}

func (x *Bid) GetCid() string {
	if x != nil && x.Cid != nil {
		return *x.Cid
	}
	return ""
}

func (x *Bid) GetCrid() string {
	if x != nil && x.Crid != nil {
		return *x.Crid
	}
	return ""
}

func (x *Bid) GetAttr() []int32 {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *Bid) GetDealid() string {
	if x != nil && x.Dealid != nil {
		return *x.Dealid
	}
	return ""
}

func (x *Bid) GetW() int32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

func (x *Bid) GetH() int32 {
	if x != nil && x.H != nil {
		return *x.H
	}
	return 0
}

func (x *Bid) GetExt() *BidExt {
	if x != nil {
		return x.Ext
	}
	return nil
}

type BidExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Btype         *int32                 `protobuf:"varint,1,opt,name=btype,proto3,oneof" json:"btype,omitempty"`
	VerticalId    *int32                 `protobuf:"varint,2,opt,name=vertical_id,json=verticalId,proto3,oneof" json:"vertical_id,omitempty"`
	Cwin          *string                `protobuf:"bytes,3,opt,name=cwin,proto3,oneof" json:"cwin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidExt) Reset() {
	*x = BidExt{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidExt) ProtoMessage() {}

func (x *BidExt) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidExt.ProtoReflect.Descriptor instead.
func (*BidExt) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{13}
}

func (x *BidExt) GetBtype() int32 {
	if x != nil && x.Btype != nil {
		return *x.Btype
	}
	return 0
}

func (x *BidExt) GetVerticalId() int32 {
	if x != nil && x.VerticalId != nil {
		return *x.VerticalId
	}
	return 0
}

func (x *BidExt) GetCwin() string {
	if x != nil && x.Cwin != nil {
		return *x.Cwin
	}
	return ""
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Seatbid       []*SeatBid             `protobuf:"bytes,2,rep,name=seatbid,proto3" json:"seatbid,omitempty"` // у тебя всегда один SeatBid с одним Bid
	Bidid         *string                `protobuf:"bytes,3,opt,name=bidid,proto3,oneof" json:"bidid,omitempty"`
	Cur           *string                `protobuf:"bytes,4,opt,name=cur,proto3,oneof" json:"cur,omitempty"`
	Nbr           *int32                 `protobuf:"varint,5,opt,name=nbr,proto3,oneof" json:"nbr,omitempty"`
	Ext           *Ext                   `protobuf:"bytes,6,opt,name=ext,proto3,oneof" json:"ext,omitempty"` // Galaxyon кидает "Ext" на этом уровне
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{14}
}

func (x *BidResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BidResponse) GetSeatbid() []*SeatBid {
	if x != nil {
		return x.Seatbid
	}
	return nil
}

func (x *BidResponse) GetBidid() string {
	if x != nil && x.Bidid != nil {
		return *x.Bidid
	}
	return ""
}

func (x *BidResponse) GetCur() string {
	if x != nil && x.Cur != nil {
		return *x.Cur
	}
	return ""
}

func (x *BidResponse) GetNbr() int32 {
	if x != nil && x.Nbr != nil {
		return *x.Nbr
	}
	return 0
}

func (x *BidResponse) GetExt() *Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

type Ext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ext) Reset() {
	*x = Ext{}
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ext) ProtoMessage() {}

func (x *Ext) ProtoReflect() protoreflect.Message {
	mi := &file_types_ortb_V2_5_ortb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ext.ProtoReflect.Descriptor instead.
func (*Ext) Descriptor() ([]byte, []int) {
	return file_types_ortb_V2_5_ortb_proto_rawDescGZIP(), []int{15}
}

func (x *Ext) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_types_ortb_V2_5_ortb_proto protoreflect.FileDescriptor

const file_types_ortb_V2_5_ortb_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/ortb_V2_5/ortb.proto\x12\tortb_V2_5\"\xf1\x02\n" +
	"\n" +
	"BidRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x13\n" +
	"\x02at\x18\x02 \x01(\x05H\x01R\x02at\x88\x01\x01\x12 \n" +
	"\x03imp\x18\x03 \x03(\v2\x0e.ortb_V2_5.ImpR\x03imp\x12.\n" +
	"\x06device\x18\x04 \x01(\v2\x11.ortb_V2_5.DeviceH\x02R\x06device\x88\x01\x01\x12(\n" +
	"\x04site\x18\x05 \x01(\v2\x0f.ortb_V2_5.SiteH\x03R\x04site\x88\x01\x01\x12(\n" +
	"\x04user\x18\x06 \x01(\v2\x0f.ortb_V2_5.UserH\x04R\x04user\x88\x01\x01\x12\x17\n" +
	"\x04tmax\x18\a \x01(\x05H\x05R\x04tmax\x88\x01\x01\x12\x10\n" +
	"\x03cur\x18\b \x03(\tR\x03cur\x12\x12\n" +
	"\x04bcat\x18\t \x03(\tR\x04bcat\x12\x17\n" +
	"\x04test\x18\n" +
	" \x01(\x05H\x06R\x04test\x88\x01\x01B\x05\n" +
	"\x03_idB\x05\n" +
	"\x03_atB\t\n" +
	"\a_deviceB\a\n" +
	"\x05_siteB\a\n" +
	"\x05_userB\a\n" +
	"\x05_tmaxB\a\n" +
	"\x05_test\"\xa1\x03\n" +
	"\x03Imp\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bbidfloor\x18\x02 \x01(\x02H\x01R\bbidfloor\x88\x01\x01\x12\x19\n" +
	"\x05tagid\x18\x03 \x01(\tH\x02R\x05tagid\x88\x01\x01\x12\x1b\n" +
	"\x06secure\x18\x04 \x01(\x05H\x03R\x06secure\x88\x01\x01\x12\x19\n" +
	"\x05instl\x18\x05 \x01(\x05H\x04R\x05instl\x88\x01\x01\x12%\n" +
	"\vbidfloorcur\x18\x06 \x01(\tH\x05R\vbidfloorcur\x88\x01\x01\x12)\n" +
	"\x03ext\x18\a \x01(\v2\x12.ortb_V2_5.Imp_ExtH\x06R\x03ext\x88\x01\x01\x12.\n" +
	"\x06banner\x18\b \x01(\v2\x11.ortb_V2_5.BannerH\aR\x06banner\x88\x01\x01\x12.\n" +
	"\x06native\x18\t \x01(\v2\x11.ortb_V2_5.NativeH\bR\x06native\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_bidfloorB\b\n" +
	"\x06_tagidB\t\n" +
	"\a_secureB\b\n" +
	"\x06_instlB\x0e\n" +
	"\f_bidfloorcurB\x06\n" +
	"\x04_extB\t\n" +
	"\a_bannerB\t\n" +
	"\a_native\"\xa5\x02\n" +
	"\x06Banner\x12\x11\n" +
	"\x01w\x18\x01 \x01(\x05H\x00R\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\x02 \x01(\x05H\x01R\x01h\x88\x01\x01\x12\x15\n" +
	"\x03pos\x18\x03 \x01(\x05H\x02R\x03pos\x88\x01\x01\x12\x14\n" +
	"\x05mimes\x18\x04 \x03(\tR\x05mimes\x12\x15\n" +
	"\x03api\x18\x05 \x01(\tH\x03R\x03api\x88\x01\x01\x12\x1f\n" +
	"\btopframe\x18\x06 \x01(\x05H\x04R\btopframe\x88\x01\x01\x12\x14\n" +
	"\x05btype\x18\a \x03(\x05R\x05btype\x12\x14\n" +
	"\x05battr\x18\b \x03(\x05R\x05battr\x12\x10\n" +
	"\x03ext\x18\t \x03(\tR\x03ext\x12)\n" +
	"\x06format\x18\n" +
	" \x03(\v2\x11.ortb_V2_5.FormatR\x06formatB\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_hB\x06\n" +
	"\x04_posB\x06\n" +
	"\x04_apiB\v\n" +
	"\t_topframe\":\n" +
	"\x06Format\x12\x11\n" +
	"\x01w\x18\x01 \x01(\x05H\x00R\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\x02 \x01(\x05H\x01R\x01h\x88\x01\x01B\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_h\"R\n" +
	"\x06Native\x12\x1d\n" +
	"\arequest\x18\x01 \x01(\tH\x00R\arequest\x88\x01\x01\x12\x15\n" +
	"\x03ver\x18\x02 \x01(\tH\x01R\x03ver\x88\x01\x01B\n" +
	"\n" +
	"\b_requestB\x06\n" +
	"\x04_ver\".\n" +
	"\aImp_Ext\x12\x19\n" +
	"\x05subid\x18\x01 \x01(\tH\x00R\x05subid\x88\x01\x01B\b\n" +
	"\x06_subid\"\x8b\x04\n" +
	"\x06Device\x12\x13\n" +
	"\x02ip\x18\x01 \x01(\tH\x00R\x02ip\x88\x01\x01\x12%\n" +
	"\x03geo\x18\x02 \x01(\v2\x0e.ortb_V2_5.GeoH\x01R\x03geo\x88\x01\x01\x12\x13\n" +
	"\x02ua\x18\x03 \x01(\tH\x02R\x02ua\x88\x01\x01\x12\x13\n" +
	"\x02js\x18\x04 \x01(\x05H\x03R\x02js\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x05 \x01(\tH\x04R\blanguage\x88\x01\x01\x122\n" +
	"\n" +
	"device_ext\x18\x06 \x01(\v2\x0e.ortb_V2_5.ExtH\x05R\tdeviceExt\x88\x01\x01\x12\x17\n" +
	"\x04ipv6\x18\a \x01(\tH\x06R\x04ipv6\x88\x01\x01\x12+\n" +
	"\x0econnectiontype\x18\b \x01(\x05H\aR\x0econnectiontype\x88\x01\x01\x12\x1d\n" +
	"\acarrier\x18\t \x01(\tH\bR\acarrier\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\n" +
	" \x01(\tH\tR\x02os\x88\x01\x01\x12#\n" +
	"\n" +
	"deviceType\x18\v \x01(\x05H\n" +
	"R\n" +
	"deviceType\x88\x01\x01\x12\x11\n" +
	"\x01w\x18\f \x01(\x05H\vR\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\r \x01(\x05H\fR\x01h\x88\x01\x01B\x05\n" +
	"\x03_ipB\x06\n" +
	"\x04_geoB\x05\n" +
	"\x03_uaB\x05\n" +
	"\x03_jsB\v\n" +
	"\t_languageB\r\n" +
	"\v_device_extB\a\n" +
	"\x05_ipv6B\x11\n" +
	"\x0f_connectiontypeB\n" +
	"\n" +
	"\b_carrierB\x05\n" +
	"\x03_osB\r\n" +
	"\v_deviceTypeB\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_h\"\xf9\x01\n" +
	"\x03Geo\x12\x1d\n" +
	"\acountry\x18\x01 \x01(\tH\x00R\acountry\x88\x01\x01\x12\x15\n" +
	"\x03lat\x18\x02 \x01(\x02H\x01R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x03 \x01(\x02H\x02R\x03lon\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\tH\x03R\x06region\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x05 \x01(\tH\x04R\x04city\x88\x01\x01\x12\x15\n" +
	"\x03zip\x18\x06 \x01(\tH\x05R\x03zip\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\a \x01(\x05H\x06R\x04type\x88\x01\x01B\n" +
	"\n" +
	"\b_countryB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\t\n" +
	"\a_regionB\a\n" +
	"\x05_cityB\x06\n" +
	"\x04_zipB\a\n" +
	"\x05_type\"\xb4\x02\n" +
	"\x04Site\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\tH\x02R\x04page\x88\x01\x01\x12\x1b\n" +
	"\x06domain\x18\x04 \x01(\tH\x03R\x06domain\x88\x01\x01\x12\x15\n" +
	"\x03ref\x18\x05 \x01(\tH\x04R\x03ref\x88\x01\x01\x12\x10\n" +
	"\x03cat\x18\x06 \x03(\tR\x03cat\x127\n" +
	"\tpublisher\x18\a \x01(\v2\x14.ortb_V2_5.PublisherH\x05R\tpublisher\x88\x01\x01\x12\x1f\n" +
	"\bkeywords\x18\b \x01(\tH\x06R\bkeywords\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_pageB\t\n" +
	"\a_domainB\x06\n" +
	"\x04_refB\f\n" +
	"\n" +
	"_publisherB\v\n" +
	"\t_keywords\"I\n" +
	"\tPublisher\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_name\"~\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bkeywords\x18\x02 \x01(\tH\x01R\bkeywords\x88\x01\x01\x12\x1f\n" +
	"\bbuyeruid\x18\x03 \x01(\tH\x02R\bbuyeruid\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_keywordsB\v\n" +
	"\t_buyeruid\"M\n" +
	"\aSeatBid\x12 \n" +
	"\x03bid\x18\x01 \x03(\v2\x0e.ortb_V2_5.BidR\x03bid\x12\x17\n" +
	"\x04seat\x18\x02 \x01(\tH\x00R\x04seat\x88\x01\x01B\a\n" +
	"\x05_seat\"\xb5\x04\n" +
	"\x03Bid\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05impid\x18\x02 \x01(\tH\x01R\x05impid\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x02H\x02R\x05price\x88\x01\x01\x12\x17\n" +
	"\x04adid\x18\x04 \x01(\tH\x03R\x04adid\x88\x01\x01\x12\x17\n" +
	"\x04nurl\x18\x05 \x01(\tH\x04R\x04nurl\x88\x01\x01\x12\x17\n" +
	"\x04burl\x18\x06 \x01(\tH\x05R\x04burl\x88\x01\x01\x12\x15\n" +
	"\x03adm\x18\a \x01(\tH\x06R\x03adm\x88\x01\x01\x12\x18\n" +
	"\aadomain\x18\b \x03(\tR\aadomain\x12\x1b\n" +
	"\x06bundle\x18\t \x01(\tH\aR\x06bundle\x88\x01\x01\x12\x17\n" +
	"\x04iurl\x18\n" +
	" \x01(\tH\bR\x04iurl\x88\x01\x01\x12\x15\n" +
	"\x03cid\x18\v \x01(\tH\tR\x03cid\x88\x01\x01\x12\x17\n" +
	"\x04crid\x18\f \x01(\tH\n" +
	"R\x04crid\x88\x01\x01\x12\x12\n" +
	"\x04attr\x18\r \x03(\x05R\x04attr\x12\x1b\n" +
	"\x06dealid\x18\x0e \x01(\tH\vR\x06dealid\x88\x01\x01\x12\x11\n" +
	"\x01w\x18\x0f \x01(\x05H\fR\x01w\x88\x01\x01\x12\x11\n" +
	"\x01h\x18\x10 \x01(\x05H\rR\x01h\x88\x01\x01\x12(\n" +
	"\x03ext\x18\x11 \x01(\v2\x11.ortb_V2_5.BidExtH\x0eR\x03ext\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_impidB\b\n" +
	"\x06_priceB\a\n" +
	"\x05_adidB\a\n" +
	"\x05_nurlB\a\n" +
	"\x05_burlB\x06\n" +
	"\x04_admB\t\n" +
	"\a_bundleB\a\n" +
	"\x05_iurlB\x06\n" +
	"\x04_cidB\a\n" +
	"\x05_cridB\t\n" +
	"\a_dealidB\x04\n" +
	"\x02_wB\x04\n" +
	"\x02_hB\x06\n" +
	"\x04_ext\"\x85\x01\n" +
	"\x06BidExt\x12\x19\n" +
	"\x05btype\x18\x01 \x01(\x05H\x00R\x05btype\x88\x01\x01\x12$\n" +
	"\vvertical_id\x18\x02 \x01(\x05H\x01R\n" +
	"verticalId\x88\x01\x01\x12\x17\n" +
	"\x04cwin\x18\x03 \x01(\tH\x02R\x04cwin\x88\x01\x01B\b\n" +
	"\x06_btypeB\x0e\n" +
	"\f_vertical_idB\a\n" +
	"\x05_cwin\"\xe9\x01\n" +
	"\vBidResponse\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12,\n" +
	"\aseatbid\x18\x02 \x03(\v2\x12.ortb_V2_5.SeatBidR\aseatbid\x12\x19\n" +
	"\x05bidid\x18\x03 \x01(\tH\x01R\x05bidid\x88\x01\x01\x12\x15\n" +
	"\x03cur\x18\x04 \x01(\tH\x02R\x03cur\x88\x01\x01\x12\x15\n" +
	"\x03nbr\x18\x05 \x01(\x05H\x03R\x03nbr\x88\x01\x01\x12%\n" +
	"\x03ext\x18\x06 \x01(\v2\x0e.ortb_V2_5.ExtH\x04R\x03ext\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_bididB\x06\n" +
	"\x04_curB\x06\n" +
	"\x04_nbrB\x06\n" +
	"\x04_ext\"t\n" +
	"\x03Ext\x122\n" +
	"\x06values\x18\x01 \x03(\v2\x1a.ortb_V2_5.Ext.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BXZVgitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5;ortb_V2_5b\x06proto3"

var (
	file_types_ortb_V2_5_ortb_proto_rawDescOnce sync.Once
	file_types_ortb_V2_5_ortb_proto_rawDescData []byte
)

func file_types_ortb_V2_5_ortb_proto_rawDescGZIP() []byte {
	file_types_ortb_V2_5_ortb_proto_rawDescOnce.Do(func() {
		file_types_ortb_V2_5_ortb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_ortb_V2_5_ortb_proto_rawDesc), len(file_types_ortb_V2_5_ortb_proto_rawDesc)))
	})
	return file_types_ortb_V2_5_ortb_proto_rawDescData
}

var file_types_ortb_V2_5_ortb_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_types_ortb_V2_5_ortb_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: ortb_V2_5.BidRequest
	(*Imp)(nil),         // 1: ortb_V2_5.Imp
	(*Banner)(nil),      // 2: ortb_V2_5.Banner
	(*Format)(nil),      // 3: ortb_V2_5.Format
	(*Native)(nil),      // 4: ortb_V2_5.Native
	(*Imp_Ext)(nil),     // 5: ortb_V2_5.Imp_Ext
	(*Device)(nil),      // 6: ortb_V2_5.Device
	(*Geo)(nil),         // 7: ortb_V2_5.Geo
	(*Site)(nil),        // 8: ortb_V2_5.Site
	(*Publisher)(nil),   // 9: ortb_V2_5.Publisher
	(*User)(nil),        // 10: ortb_V2_5.User
	(*SeatBid)(nil),     // 11: ortb_V2_5.SeatBid
	(*Bid)(nil),         // 12: ortb_V2_5.Bid
	(*BidExt)(nil),      // 13: ortb_V2_5.BidExt
	(*BidResponse)(nil), // 14: ortb_V2_5.BidResponse
	(*Ext)(nil),         // 15: ortb_V2_5.Ext
	nil,                 // 16: ortb_V2_5.Ext.ValuesEntry
}
var file_types_ortb_V2_5_ortb_proto_depIdxs = []int32{
	1,  // 0: ortb_V2_5.BidRequest.imp:type_name -> ortb_V2_5.Imp
	6,  // 1: ortb_V2_5.BidRequest.device:type_name -> ortb_V2_5.Device
	8,  // 2: ortb_V2_5.BidRequest.site:type_name -> ortb_V2_5.Site
	10, // 3: ortb_V2_5.BidRequest.user:type_name -> ortb_V2_5.User
	5,  // 4: ortb_V2_5.Imp.ext:type_name -> ortb_V2_5.Imp_Ext
	2,  // 5: ortb_V2_5.Imp.banner:type_name -> ortb_V2_5.Banner
	4,  // 6: ortb_V2_5.Imp.native:type_name -> ortb_V2_5.Native
	3,  // 7: ortb_V2_5.Banner.format:type_name -> ortb_V2_5.Format
	7,  // 8: ortb_V2_5.Device.geo:type_name -> ortb_V2_5.Geo
	15, // 9: ortb_V2_5.Device.device_ext:type_name -> ortb_V2_5.Ext
	9,  // 10: ortb_V2_5.Site.publisher:type_name -> ortb_V2_5.Publisher
	12, // 11: ortb_V2_5.SeatBid.bid:type_name -> ortb_V2_5.Bid
	13, // 12: ortb_V2_5.Bid.ext:type_name -> ortb_V2_5.BidExt
	11, // 13: ortb_V2_5.BidResponse.seatbid:type_name -> ortb_V2_5.SeatBid
	15, // 14: ortb_V2_5.BidResponse.ext:type_name -> ortb_V2_5.Ext
	16, // 15: ortb_V2_5.Ext.values:type_name -> ortb_V2_5.Ext.ValuesEntry
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_types_ortb_V2_5_ortb_proto_init() }
func file_types_ortb_V2_5_ortb_proto_init() {
	if File_types_ortb_V2_5_ortb_proto != nil {
		return
	}
	file_types_ortb_V2_5_ortb_proto_msgTypes[0].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[1].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[2].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[4].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[5].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[6].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[7].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[8].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[9].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[10].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[11].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[12].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[13].OneofWrappers = []any{}
	file_types_ortb_V2_5_ortb_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_ortb_V2_5_ortb_proto_rawDesc), len(file_types_ortb_V2_5_ortb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_ortb_V2_5_ortb_proto_goTypes,
		DependencyIndexes: file_types_ortb_V2_5_ortb_proto_depIdxs,
		MessageInfos:      file_types_ortb_V2_5_ortb_proto_msgTypes,
	}.Build()
	File_types_ortb_V2_5_ortb_proto = out.File
	file_types_ortb_V2_5_ortb_proto_goTypes = nil
	file_types_ortb_V2_5_ortb_proto_depIdxs = nil
}
