// Auto-generated dimension dictionaries (countries, languages, OS, browsers).
// Used in targeting (campaign create/edit) and statistics filters.

export interface CountryEntry { code: string; ru: string; en: string; }
export const COUNTRIES: CountryEntry[] = [
  { code: "AD", ru: "Андорра", en: "AD" },
  { code: "AE", ru: "Объединённые Арабские Эмираты", en: "AE" },
  { code: "AF", ru: "Афганистан", en: "AF" },
  { code: "AG", ru: "Антигуа и Барбуда", en: "AG" },
  { code: "AI", ru: "Ангилья", en: "AI" },
  { code: "AL", ru: "Албания", en: "AL" },
  { code: "AM", ru: "Армения", en: "AM" },
  { code: "AO", ru: "Ангола", en: "AO" },
  { code: "AQ", ru: "Антарктида", en: "AQ" },
  { code: "AR", ru: "Аргентина", en: "AR" },
  { code: "AS", ru: "Американское Самоа", en: "AS" },
  { code: "AT", ru: "Австрия", en: "AT" },
  { code: "AU", ru: "Австралия", en: "AU" },
  { code: "AW", ru: "Аруба", en: "AW" },
  { code: "AX", ru: "Аландские острова", en: "AX" },
  { code: "AZ", ru: "Азербайджан", en: "AZ" },
  { code: "BA", ru: "Босния и Герцеговина", en: "BA" },
  { code: "BB", ru: "Барбадос", en: "BB" },
  { code: "BD", ru: "Бангладеш", en: "BD" },
  { code: "BE", ru: "Бельгия", en: "BE" },
  { code: "BF", ru: "Буркина-Фасо", en: "BF" },
  { code: "BG", ru: "Болгария", en: "BG" },
  { code: "BH", ru: "Бахрейн", en: "BH" },
  { code: "BI", ru: "Бурунди", en: "BI" },
  { code: "BJ", ru: "Бенин", en: "BJ" },
  { code: "BL", ru: "Сен-Бартелеми", en: "BL" },
  { code: "BM", ru: "Бермуды", en: "BM" },
  { code: "BN", ru: "Бруней", en: "BN" },
  { code: "BO", ru: "Боливия", en: "BO" },
  { code: "BQ", ru: "Карибские Нидерланды (Бонайре, Синт-Эстатиус и Саба)", en: "BQ" },
  { code: "BR", ru: "Бразилия", en: "BR" },
  { code: "BS", ru: "Багамы", en: "BS" },
  { code: "BT", ru: "Бутан", en: "BT" },
  { code: "BV", ru: "Остров Буве", en: "BV" },
  { code: "BW", ru: "Ботсвана", en: "BW" },
  { code: "BY", ru: "Беларусь", en: "BY" },
  { code: "BZ", ru: "Белиз", en: "BZ" },
  { code: "CA", ru: "Канада", en: "CA" },
  { code: "CC", ru: "Кокосовые (Килинг) острова", en: "CC" },
  { code: "CD", ru: "Демократическая Республика Конго", en: "CD" },
  { code: "CF", ru: "Центральноафриканская Республика", en: "CF" },
  { code: "CG", ru: "Республика Конго", en: "CG" },
  { code: "CH", ru: "Швейцария", en: "CH" },
  { code: "CI", ru: "Кот-д’Ивуар", en: "CI" },
  { code: "CK", ru: "Острова Кука", en: "CK" },
  { code: "CL", ru: "Чили", en: "CL" },
  { code: "CM", ru: "Камерун", en: "CM" },
  { code: "CN", ru: "Китай", en: "CN" },
  { code: "CO", ru: "Колумбия", en: "CO" },
  { code: "CR", ru: "Коста-Рика", en: "CR" },
  { code: "CU", ru: "Куба", en: "CU" },
  { code: "CV", ru: "Кабо-Верде", en: "CV" },
  { code: "CW", ru: "Кюрасао", en: "CW" },
  { code: "CX", ru: "Остров Рождества", en: "CX" },
  { code: "CY", ru: "Кипр", en: "CY" },
  { code: "CZ", ru: "Чехия", en: "CZ" },
  { code: "DE", ru: "Германия", en: "DE" },
  { code: "DJ", ru: "Джибути", en: "DJ" },
  { code: "DK", ru: "Дания", en: "DK" },
  { code: "DM", ru: "Доминика", en: "DM" },
  { code: "DO", ru: "Доминиканская Республика", en: "DO" },
  { code: "DZ", ru: "Алжир", en: "DZ" },
  { code: "EC", ru: "Эквадор", en: "EC" },
  { code: "EE", ru: "Эстония", en: "EE" },
  { code: "EG", ru: "Египет", en: "EG" },
  { code: "EH", ru: "Западная Сахара", en: "EH" },
  { code: "ER", ru: "Эритрея", en: "ER" },
  { code: "ES", ru: "Испания", en: "ES" },
  { code: "ET", ru: "Эфиопия", en: "ET" },
  { code: "FI", ru: "Финляндия", en: "FI" },
  { code: "FJ", ru: "Фиджи", en: "FJ" },
  { code: "FK", ru: "Фолклендские острова", en: "FK" },
  { code: "FM", ru: "Микронезия", en: "FM" },
  { code: "FO", ru: "Фарерские острова", en: "FO" },
  { code: "FR", ru: "Франция", en: "FR" },
  { code: "GA", ru: "Габон", en: "GA" },
  { code: "GB", ru: "Великобритания", en: "GB" },
  { code: "GD", ru: "Гренада", en: "GD" },
  { code: "GE", ru: "Грузия", en: "GE" },
  { code: "GF", ru: "Французская Гвиана", en: "GF" },
  { code: "GG", ru: "Гернси", en: "GG" },
  { code: "GH", ru: "Гана", en: "GH" },
  { code: "GI", ru: "Гибралтар", en: "GI" },
  { code: "GL", ru: "Гренландия", en: "GL" },
  { code: "GM", ru: "Гамбия", en: "GM" },
  { code: "GN", ru: "Гвинея", en: "GN" },
  { code: "GP", ru: "Гваделупа", en: "GP" },
  { code: "GQ", ru: "Экваториальная Гвинея", en: "GQ" },
  { code: "GR", ru: "Греция", en: "GR" },
  { code: "GS", ru: "Южная Георгия и Южные Сандвичевы острова", en: "GS" },
  { code: "GT", ru: "Гватемала", en: "GT" },
  { code: "GU", ru: "Гуам", en: "GU" },
  { code: "GW", ru: "Гвинея-Бисау", en: "GW" },
  { code: "GY", ru: "Гайана", en: "GY" },
  { code: "HK", ru: "Гонконг", en: "HK" },
  { code: "HM", ru: "Остров Херд и острова Макдональд", en: "HM" },
  { code: "HN", ru: "Гондурас", en: "HN" },
  { code: "HR", ru: "Хорватия", en: "HR" },
  { code: "HT", ru: "Гаити", en: "HT" },
  { code: "HU", ru: "Венгрия", en: "HU" },
  { code: "ID", ru: "Индонезия", en: "ID" },
  { code: "IE", ru: "Ирландия", en: "IE" },
  { code: "IL", ru: "Израиль", en: "IL" },
  { code: "IM", ru: "Остров Мэн", en: "IM" },
  { code: "IN", ru: "Индия", en: "IN" },
  { code: "IO", ru: "Британская территория в Индийском океане", en: "IO" },
  { code: "IQ", ru: "Ирак", en: "IQ" },
  { code: "IR", ru: "Иран", en: "IR" },
  { code: "IS", ru: "Исландия", en: "IS" },
  { code: "IT", ru: "Италия", en: "IT" },
  { code: "JE", ru: "Джерси", en: "JE" },
  { code: "JM", ru: "Ямайка", en: "JM" },
  { code: "JO", ru: "Иордания", en: "JO" },
  { code: "JP", ru: "Япония", en: "JP" },
  { code: "KE", ru: "Кения", en: "KE" },
  { code: "KG", ru: "Кыргызстан", en: "KG" },
  { code: "KH", ru: "Камбоджа", en: "KH" },
  { code: "KI", ru: "Кирибати", en: "KI" },
  { code: "KM", ru: "Коморы", en: "KM" },
  { code: "KN", ru: "Сент-Китс и Невис", en: "KN" },
  { code: "KP", ru: "Северная Корея", en: "KP" },
  { code: "KR", ru: "Южная Корея", en: "KR" },
  { code: "KW", ru: "Кувейт", en: "KW" },
  { code: "KY", ru: "Каймановы острова", en: "KY" },
  { code: "KZ", ru: "Казахстан", en: "KZ" },
  { code: "LA", ru: "Лаос", en: "LA" },
  { code: "LB", ru: "Ливан", en: "LB" },
  { code: "LC", ru: "Сент-Люсия", en: "LC" },
  { code: "LI", ru: "Лихтенштейн", en: "LI" },
  { code: "LK", ru: "Шри-Ланка", en: "LK" },
  { code: "LR", ru: "Либерия", en: "LR" },
  { code: "LS", ru: "Лесото", en: "LS" },
  { code: "LT", ru: "Литва", en: "LT" },
  { code: "LU", ru: "Люксембург", en: "LU" },
  { code: "LV", ru: "Латвия", en: "LV" },
  { code: "LY", ru: "Ливия", en: "LY" },
  { code: "MA", ru: "Марокко", en: "MA" },
  { code: "MC", ru: "Монако", en: "MC" },
  { code: "MD", ru: "Молдова", en: "MD" },
  { code: "ME", ru: "Черногория", en: "ME" },
  { code: "MF", ru: "Сен-Мартен (французская часть)", en: "MF" },
  { code: "MG", ru: "Мадагаскар", en: "MG" },
  { code: "MH", ru: "Маршалловы Острова", en: "MH" },
  { code: "MK", ru: "Северная Македония", en: "MK" },
  { code: "ML", ru: "Мали", en: "ML" },
  { code: "MM", ru: "Мьянма", en: "MM" },
  { code: "MN", ru: "Монголия", en: "MN" },
  { code: "MO", ru: "Макао", en: "MO" },
  { code: "MP", ru: "Северные Марианские острова", en: "MP" },
  { code: "MQ", ru: "Мартиника", en: "MQ" },
  { code: "MR", ru: "Мавритания", en: "MR" },
  { code: "MS", ru: "Монтсеррат", en: "MS" },
  { code: "MT", ru: "Мальта", en: "MT" },
  { code: "MU", ru: "Маврикий", en: "MU" },
  { code: "MV", ru: "Мальдивы", en: "MV" },
  { code: "MW", ru: "Малави", en: "MW" },
  { code: "MX", ru: "Мексика", en: "MX" },
  { code: "MY", ru: "Малайзия", en: "MY" },
  { code: "MZ", ru: "Мозамбик", en: "MZ" },
  { code: "NC", ru: "Новая Каледония", en: "NC" },
  { code: "NE", ru: "Нигер", en: "NE" },
  { code: "NF", ru: "Остров Норфолк", en: "NF" },
  { code: "NG", ru: "Нигерия", en: "NG" },
  { code: "NI", ru: "Никарагуа", en: "NI" },
  { code: "NL", ru: "Нидерланды", en: "NL" },
  { code: "NO", ru: "Норвегия", en: "NO" },
  { code: "NP", ru: "Непал", en: "NP" },
  { code: "NR", ru: "Науру", en: "NR" },
  { code: "NU", ru: "Ниуэ", en: "NU" },
  { code: "NZ", ru: "Новая Зеландия", en: "NZ" },
  { code: "OM", ru: "Оман", en: "OM" },
  { code: "PA", ru: "Панама", en: "PA" },
  { code: "PE", ru: "Перу", en: "PE" },
  { code: "PF", ru: "Французская Полинезия", en: "PF" },
  { code: "PG", ru: "Папуа — Новая Гвинея", en: "PG" },
  { code: "PH", ru: "Филиппины", en: "PH" },
  { code: "PK", ru: "Пакистан", en: "PK" },
  { code: "PL", ru: "Польша", en: "PL" },
  { code: "PM", ru: "Сен-Пьер и Микелон", en: "PM" },
  { code: "PN", ru: "Острова Питкэрн", en: "PN" },
  { code: "PR", ru: "Пуэрто-Рико", en: "PR" },
  { code: "PS", ru: "Палестина", en: "PS" },
  { code: "PT", ru: "Португалия", en: "PT" },
  { code: "PW", ru: "Палау", en: "PW" },
  { code: "PY", ru: "Парагвай", en: "PY" },
  { code: "QA", ru: "Катар", en: "QA" },
  { code: "RE", ru: "Реюньон", en: "RE" },
  { code: "RO", ru: "Румыния", en: "RO" },
  { code: "RS", ru: "Сербия", en: "RS" },
  { code: "RU", ru: "Россия", en: "RU" },
  { code: "RW", ru: "Руанда", en: "RW" },
  { code: "SA", ru: "Саудовская Аравия", en: "SA" },
  { code: "SB", ru: "Соломоновы Острова", en: "SB" },
  { code: "SC", ru: "Сейшелы", en: "SC" },
  { code: "SD", ru: "Судан", en: "SD" },
  { code: "SE", ru: "Швеция", en: "SE" },
  { code: "SG", ru: "Сингапур", en: "SG" },
  { code: "SH", ru: "Остров Святой Елены, Вознесения и Тристан-да-Кунья", en: "SH" },
  { code: "SI", ru: "Словения", en: "SI" },
  { code: "SJ", ru: "Шпицберген и Ян-Майен", en: "SJ" },
  { code: "SK", ru: "Словакия", en: "SK" },
  { code: "SL", ru: "Сьерра-Леоне", en: "SL" },
  { code: "SM", ru: "Сан-Марино", en: "SM" },
  { code: "SN", ru: "Сенегал", en: "SN" },
  { code: "SO", ru: "Сомали", en: "SO" },
  { code: "SR", ru: "Суринам", en: "SR" },
  { code: "SS", ru: "Южный Судан", en: "SS" },
  { code: "ST", ru: "Сан-Томе и Принсипи", en: "ST" },
  { code: "SV", ru: "Сальвадор", en: "SV" },
  { code: "SX", ru: "Синт-Мартен (нидерландская часть)", en: "SX" },
  { code: "SY", ru: "Сирия", en: "SY" },
  { code: "SZ", ru: "Эсватини", en: "SZ" },
  { code: "TC", ru: "Острова Теркс и Кайкос", en: "TC" },
  { code: "TD", ru: "Чад", en: "TD" },
  { code: "TF", ru: "Французские Южные и Антарктические территории", en: "TF" },
  { code: "TG", ru: "Того", en: "TG" },
  { code: "TH", ru: "Таиланд", en: "TH" },
  { code: "TJ", ru: "Таджикистан", en: "TJ" },
  { code: "TK", ru: "Токелау", en: "TK" },
  { code: "TL", ru: "Тимор-Лесте", en: "TL" },
  { code: "TM", ru: "Туркменистан", en: "TM" },
  { code: "TN", ru: "Тунис", en: "TN" },
  { code: "TO", ru: "Тонга", en: "TO" },
  { code: "TR", ru: "Турция", en: "TR" },
  { code: "TT", ru: "Тринидад и Тобаго", en: "TT" },
  { code: "TV", ru: "Тувалу", en: "TV" },
  { code: "TW", ru: "Тайвань", en: "TW" },
  { code: "TZ", ru: "Танзания", en: "TZ" },
  { code: "UA", ru: "Украина", en: "UA" },
  { code: "UG", ru: "Уганда", en: "UG" },
  { code: "UM", ru: "Внешние малые острова США", en: "UM" },
  { code: "US", ru: "Соединённые Штаты Америки", en: "US" },
  { code: "UY", ru: "Уругвай", en: "UY" },
  { code: "UZ", ru: "Узбекистан", en: "UZ" },
  { code: "VA", ru: "Ватикан", en: "VA" },
  { code: "VC", ru: "Сент-Винсент и Гренадины", en: "VC" },
  { code: "VE", ru: "Венесуэла", en: "VE" },
  { code: "VG", ru: "Британские Виргинские острова", en: "VG" },
  { code: "VI", ru: "Виргинские острова США", en: "VI" },
  { code: "VN", ru: "Вьетнам", en: "VN" },
  { code: "VU", ru: "Вануату", en: "VU" },
  { code: "WF", ru: "Уоллис и Футуна", en: "WF" },
  { code: "WS", ru: "Самоа", en: "WS" },
  { code: "YE", ru: "Йемен", en: "YE" },
  { code: "YT", ru: "Майотта", en: "YT" },
  { code: "ZA", ru: "Южно-Африканская Республика", en: "ZA" },
  { code: "ZM", ru: "Замбия", en: "ZM" },
  { code: "ZW", ru: "Зимбабве", en: "ZW" },
];

export interface LanguageEntry { code: string; en: string; }
export const LANGUAGES: LanguageEntry[] = [
  { code: "AA", en: "Afar" },
  { code: "AB", en: "Abkhazian" },
  { code: "AE", en: "Avestan" },
  { code: "AF", en: "Afrikaans" },
  { code: "AK", en: "Akan" },
  { code: "AM", en: "Amharic" },
  { code: "AN", en: "Aragonese" },
  { code: "AR", en: "Arabic" },
  { code: "AS", en: "Assamese" },
  { code: "AV", en: "Avaric" },
  { code: "AY", en: "Aymara" },
  { code: "AZ", en: "Azerbaijani" },
  { code: "BA", en: "Bashkir" },
  { code: "BE", en: "Belarusian" },
  { code: "BG", en: "Bulgarian" },
  { code: "BI", en: "Bislama" },
  { code: "BM", en: "Bambara" },
  { code: "BN", en: "Bengali" },
  { code: "BO", en: "Tibetan" },
  { code: "BR", en: "Breton" },
  { code: "BS", en: "Bosnian" },
  { code: "CA", en: "Catalan" },
  { code: "CE", en: "Chechen" },
  { code: "CH", en: "Chamorro" },
  { code: "CO", en: "Corsican" },
  { code: "CR", en: "Cree" },
  { code: "CS", en: "Czech" },
  { code: "CU", en: "Church Slavic" },
  { code: "CV", en: "Chuvash" },
  { code: "CY", en: "Welsh" },
  { code: "DA", en: "Danish" },
  { code: "DE", en: "German" },
  { code: "DV", en: "Divehi" },
  { code: "DZ", en: "Dzongkha" },
  { code: "EE", en: "Ewe" },
  { code: "EL", en: "Greek" },
  { code: "EN", en: "English" },
  { code: "EO", en: "Esperanto" },
  { code: "ES", en: "Spanish" },
  { code: "ET", en: "Estonian" },
  { code: "EU", en: "Basque" },
  { code: "FA", en: "Persian" },
  { code: "FF", en: "Fulah" },
  { code: "FI", en: "Finnish" },
  { code: "FJ", en: "Fijian" },
  { code: "FO", en: "Faroese" },
  { code: "FR", en: "French" },
  { code: "FY", en: "Western Frisian" },
  { code: "GA", en: "Irish" },
  { code: "GD", en: "Scottish Gaelic" },
  { code: "GL", en: "Galician" },
  { code: "GN", en: "Guarani" },
  { code: "GU", en: "Gujarati" },
  { code: "GV", en: "Manx" },
  { code: "HA", en: "Hausa" },
  { code: "HE", en: "Hebrew" },
  { code: "HI", en: "Hindi" },
  { code: "HO", en: "Hiri Motu" },
  { code: "HR", en: "Croatian" },
  { code: "HT", en: "Haitian Creole" },
  { code: "HU", en: "Hungarian" },
  { code: "HY", en: "Armenian" },
  { code: "HZ", en: "Herero" },
  { code: "IA", en: "Interlingua" },
  { code: "ID", en: "Indonesian" },
  { code: "IE", en: "Interlingue" },
  { code: "IG", en: "Igbo" },
  { code: "II", en: "Sichuan Yi" },
  { code: "IK", en: "Inupiaq" },
  { code: "IO", en: "Ido" },
  { code: "IS", en: "Icelandic" },
  { code: "IT", en: "Italian" },
  { code: "IU", en: "Inuktitut" },
  { code: "JA", en: "Japanese" },
  { code: "JV", en: "Javanese" },
  { code: "KA", en: "Georgian" },
  { code: "KG", en: "Kongo" },
  { code: "KI", en: "Kikuyu" },
  { code: "KJ", en: "Kuanyama" },
  { code: "KK", en: "Kazakh" },
  { code: "KL", en: "Kalaallisut" },
  { code: "KM", en: "Central Khmer" },
  { code: "KN", en: "Kannada" },
  { code: "KO", en: "Korean" },
  { code: "KR", en: "Kanuri" },
  { code: "KS", en: "Kashmiri" },
  { code: "KU", en: "Kurdish" },
  { code: "KV", en: "Komi" },
  { code: "KW", en: "Cornish" },
  { code: "KY", en: "Kirghiz" },
  { code: "LA", en: "Latin" },
  { code: "LB", en: "Luxembourgish" },
  { code: "LG", en: "Ganda" },
  { code: "LI", en: "Limburgan" },
  { code: "LN", en: "Lingala" },
  { code: "LO", en: "Lao" },
  { code: "LT", en: "Lithuanian" },
  { code: "LU", en: "Luba-Katanga" },
  { code: "LV", en: "Latvian" },
  { code: "MG", en: "Malagasy" },
  { code: "MH", en: "Marshallese" },
  { code: "MI", en: "Maori" },
  { code: "MK", en: "Macedonian" },
  { code: "ML", en: "Malayalam" },
  { code: "MN", en: "Mongolian" },
  { code: "MR", en: "Marathi" },
  { code: "MS", en: "Malay" },
  { code: "MT", en: "Maltese" },
  { code: "MY", en: "Burmese" },
  { code: "NA", en: "Nauru" },
  { code: "NB", en: "Norwegian Bokmål" },
  { code: "ND", en: "North Ndebele" },
  { code: "NE", en: "Nepali" },
  { code: "NG", en: "Ndonga" },
  { code: "NL", en: "Dutch" },
  { code: "NN", en: "Norwegian Nynorsk" },
  { code: "NO", en: "Norwegian" },
  { code: "NR", en: "South Ndebele" },
  { code: "NV", en: "Navajo" },
  { code: "NY", en: "Chichewa" },
  { code: "OC", en: "Occitan" },
  { code: "OJ", en: "Ojibwa" },
  { code: "OM", en: "Oromo" },
  { code: "OR", en: "Oriya" },
  { code: "OS", en: "Ossetian" },
  { code: "PA", en: "Panjabi" },
  { code: "PI", en: "Pali" },
  { code: "PL", en: "Polish" },
  { code: "PS", en: "Pushto" },
  { code: "PT", en: "Portuguese" },
  { code: "QU", en: "Quechua" },
  { code: "RM", en: "Romansh" },
  { code: "RN", en: "Rundi" },
  { code: "RO", en: "Romanian" },
  { code: "RU", en: "Russian" },
  { code: "RW", en: "Kinyarwanda" },
  { code: "SA", en: "Sanskrit" },
  { code: "SC", en: "Sardinian" },
  { code: "SD", en: "Sindhi" },
  { code: "SE", en: "Northern Sami" },
  { code: "SG", en: "Sango" },
  { code: "SI", en: "Sinhala" },
  { code: "SK", en: "Slovak" },
  { code: "SL", en: "Slovenian" },
  { code: "SM", en: "Samoan" },
  { code: "SN", en: "Shona" },
  { code: "SO", en: "Somali" },
  { code: "SQ", en: "Albanian" },
  { code: "SR", en: "Serbian" },
  { code: "SS", en: "Swati" },
  { code: "ST", en: "Southern Sotho" },
  { code: "SU", en: "Sundanese" },
  { code: "SV", en: "Swedish" },
  { code: "SW", en: "Swahili" },
  { code: "TA", en: "Tamil" },
  { code: "TE", en: "Telugu" },
  { code: "TG", en: "Tajik" },
  { code: "TH", en: "Thai" },
  { code: "TI", en: "Tigrinya" },
  { code: "TK", en: "Turkmen" },
  { code: "TL", en: "Tagalog" },
  { code: "TN", en: "Tswana" },
  { code: "TO", en: "Tonga" },
  { code: "TR", en: "Turkish" },
  { code: "TS", en: "Tsonga" },
  { code: "TT", en: "Tatar" },
  { code: "TW", en: "Twi" },
  { code: "TY", en: "Tahitian" },
  { code: "UG", en: "Uighur" },
  { code: "UK", en: "Ukrainian" },
  { code: "UR", en: "Urdu" },
  { code: "UZ", en: "Uzbek" },
  { code: "VE", en: "Venda" },
  { code: "VI", en: "Vietnamese" },
  { code: "VO", en: "Volapük" },
  { code: "WA", en: "Walloon" },
  { code: "WO", en: "Wolof" },
  { code: "XH", en: "Xhosa" },
  { code: "YI", en: "Yiddish" },
  { code: "YO", en: "Yoruba" },
  { code: "ZA", en: "Zhuang" },
  { code: "ZH", en: "Chinese" },
  { code: "ZU", en: "Zulu" },
];

export const OPERATING_SYSTEMS: string[] = [
  "Android",
  "Windows",
  "iOS",
  "iPad iOS",
  "MacOS",
  "Linux",
  "Chrome OS",
  "Windows Mobile",
  "BlackBerry",
  "Symbian",
  "Undefined",
  "Ubuntu",
  "Other",
  "Tizen",
];

export const BROWSERS: string[] = [
  "Undefined",
  "Other",
  "Pale Moon",
  "Safari",
  "Puffin",
  "Opera",
  "iPhone",
  "WeChat",
  "Telegram",
  "Edge",
  "Maxthon",
  "Baidu",
  "LINE",
  "TikTok",
  "Seamonkey",
  "Snapchat",
  "Edge PC",
  "Obigo",
  "Firefox",
  "IE Mobile",
  "iOS Safari",
  "Twitter / X",
  "Samsung Browser",
  "Yandex Browser",
  "Mozilla Firefox",
  "Edge iOS",
  "Instagram",
  "Chrome iOS",
  "Android Chrome",
  "Internet Explorer",
  "Google Chrome",
  "Pinterest",
  "UC Browser (UCWEB)",
  "Miui Browser (Xiaomi)",
  "Facebook App / Messenger",
  "Huawei Browser",
  "QQ Browser",
  "Vivo Browser",
  "NetCast",
];

export const COUNTRY_CODES: string[] = COUNTRIES.map(c => c.code);
export const LANGUAGE_CODES: string[] = LANGUAGES.map(l => l.code);

export const DEVICE_TYPES = ["mobile", "tablet", "desktop", "other"];
