// Auto-generated dimension dictionaries (countries, languages, OS, browsers).
// Used in targeting (campaign create/edit) and statistics filters.

export interface CountryEntry { code: string; en: string; ru: string; es: string; }
export const COUNTRIES: CountryEntry[] = [
  { code: "AF", en: "Afghanistan", ru: "Афганистан", es: "Afganistán" },
  { code: "AL", en: "Albania", ru: "Албания", es: "Albania" },
  { code: "DZ", en: "Algeria", ru: "Алжир", es: "Argelia" },
  { code: "AS", en: "American Samoa", ru: "Американское Самоа", es: "Samoa Americana" },
  { code: "AD", en: "Andorra", ru: "Андорра", es: "Andorra" },
  { code: "AO", en: "Angola", ru: "Ангола", es: "Angola" },
  { code: "AI", en: "Anguilla", ru: "Ангилья", es: "Anguila" },
  { code: "AQ", en: "Antarctica", ru: "Антарктида", es: "Antártida" },
  { code: "AG", en: "Antigua & Barbuda", ru: "Антигуа и Барбуда", es: "Antigua y Barbuda" },
  { code: "AR", en: "Argentina", ru: "Аргентина", es: "Argentina" },
  { code: "AM", en: "Armenia", ru: "Армения", es: "Armenia" },
  { code: "AW", en: "Aruba", ru: "Аруба", es: "Aruba" },
  { code: "AU", en: "Australia", ru: "Австралия", es: "Australia" },
  { code: "AT", en: "Austria", ru: "Австрия", es: "Austria" },
  { code: "AZ", en: "Azerbaijan", ru: "Азербайджан", es: "Azerbaiyán" },
  { code: "BS", en: "Bahamas", ru: "Багамы", es: "Bahamas" },
  { code: "BH", en: "Bahrain", ru: "Бахрейн", es: "Baréin" },
  { code: "BD", en: "Bangladesh", ru: "Бангладеш", es: "Bangladés" },
  { code: "BB", en: "Barbados", ru: "Барбадос", es: "Barbados" },
  { code: "BY", en: "Belarus", ru: "Беларусь", es: "Bielorrusia" },
  { code: "BE", en: "Belgium", ru: "Бельгия", es: "Bélgica" },
  { code: "BZ", en: "Belize", ru: "Белиз", es: "Belice" },
  { code: "BJ", en: "Benin", ru: "Бенин", es: "Benín" },
  { code: "BM", en: "Bermuda", ru: "Бермудские о-ва", es: "Bermudas" },
  { code: "BT", en: "Bhutan", ru: "Бутан", es: "Bután" },
  { code: "BO", en: "Bolivia", ru: "Боливия", es: "Bolivia" },
  { code: "BA", en: "Bosnia & Herzegovina", ru: "Босния и Герцеговина", es: "Bosnia y Herzegovina" },
  { code: "BW", en: "Botswana", ru: "Ботсвана", es: "Botsuana" },
  { code: "BR", en: "Brazil", ru: "Бразилия", es: "Brasil" },
  { code: "IO", en: "British Indian Ocean Territory", ru: "Британская территория в Индийском океане", es: "Territorio Británico del Océano Índico" },
  { code: "VG", en: "British Virgin Islands", ru: "Виргинские о-ва (Великобритания)", es: "Islas Vírgenes Británicas" },
  { code: "BN", en: "Brunei", ru: "Бруней", es: "Brunéi" },
  { code: "BG", en: "Bulgaria", ru: "Болгария", es: "Bulgaria" },
  { code: "BF", en: "Burkina Faso", ru: "Буркина-Фасо", es: "Burkina Faso" },
  { code: "BI", en: "Burundi", ru: "Бурунди", es: "Burundi" },
  { code: "KH", en: "Cambodia", ru: "Камбоджа", es: "Camboya" },
  { code: "CM", en: "Cameroon", ru: "Камерун", es: "Camerún" },
  { code: "CA", en: "Canada", ru: "Канада", es: "Canadá" },
  { code: "CV", en: "Cape Verde", ru: "Кабо-Верде", es: "Cabo Verde" },
  { code: "BQ", en: "Caribbean Netherlands", ru: "Caribbean Netherlands", es: "Caribe neerlandés" },
  { code: "KY", en: "Cayman Islands", ru: "о-ва Кайман", es: "Islas Caimán" },
  { code: "CF", en: "Central African Republic", ru: "Центрально-Африканская Республика", es: "República Centroafricana" },
  { code: "TD", en: "Chad", ru: "Чад", es: "Chad" },
  { code: "CL", en: "Chile", ru: "Чили", es: "Chile" },
  { code: "CN", en: "China", ru: "Китай", es: "China" },
  { code: "CO", en: "Colombia", ru: "Колумбия", es: "Colombia" },
  { code: "KM", en: "Comoros", ru: "Коморы", es: "Comoras" },
  { code: "CG", en: "Congo - Brazzaville", ru: "Конго - Браззавиль", es: "Congo" },
  { code: "CD", en: "Congo - Kinshasa", ru: "Конго - Киншаса", es: "República Democrática del Congo" },
  { code: "CK", en: "Cook Islands", ru: "о-ва Кука", es: "Islas Cook" },
  { code: "CR", en: "Costa Rica", ru: "Коста-Рика", es: "Costa Rica" },
  { code: "HR", en: "Croatia", ru: "Хорватия", es: "Croacia" },
  { code: "CU", en: "Cuba", ru: "Куба", es: "Cuba" },
  { code: "CW", en: "Curaçao", ru: "Кюрасао", es: "Curazao" },
  { code: "CY", en: "Cyprus", ru: "Кипр", es: "Chipre" },
  { code: "CZ", en: "Czechia", ru: "Чехия", es: "Chequia" },
  { code: "CI", en: "Côte d’Ivoire", ru: "Кот-д’Ивуар", es: "Côte d’Ivoire" },
  { code: "DK", en: "Denmark", ru: "Дания", es: "Dinamarca" },
  { code: "DJ", en: "Djibouti", ru: "Джибути", es: "Yibuti" },
  { code: "DM", en: "Dominica", ru: "Доминика", es: "Dominica" },
  { code: "DO", en: "Dominican Republic", ru: "Доминиканская Республика", es: "República Dominicana" },
  { code: "EC", en: "Ecuador", ru: "Эквадор", es: "Ecuador" },
  { code: "EG", en: "Egypt", ru: "Египет", es: "Egipto" },
  { code: "SV", en: "El Salvador", ru: "Сальвадор", es: "El Salvador" },
  { code: "GQ", en: "Equatorial Guinea", ru: "Экваториальная Гвинея", es: "Guinea Ecuatorial" },
  { code: "ER", en: "Eritrea", ru: "Эритрея", es: "Eritrea" },
  { code: "EE", en: "Estonia", ru: "Эстония", es: "Estonia" },
  { code: "SZ", en: "Eswatini", ru: "Эсватини", es: "Esuatini" },
  { code: "ET", en: "Ethiopia", ru: "Эфиопия", es: "Etiopía" },
  { code: "FK", en: "Falkland Islands", ru: "Фолклендские о-ва", es: "Islas Malvinas" },
  { code: "FO", en: "Faroe Islands", ru: "Фарерские о-ва", es: "Islas Feroe" },
  { code: "FJ", en: "Fiji", ru: "Фиджи", es: "Fiyi" },
  { code: "FI", en: "Finland", ru: "Финляндия", es: "Finlandia" },
  { code: "FR", en: "France", ru: "Франция", es: "Francia" },
  { code: "GF", en: "French Guiana", ru: "Французская Гвиана", es: "Guayana Francesa" },
  { code: "PF", en: "French Polynesia", ru: "Французская Полинезия", es: "Polinesia Francesa" },
  { code: "GA", en: "Gabon", ru: "Габон", es: "Gabón" },
  { code: "GM", en: "Gambia", ru: "Гамбия", es: "Gambia" },
  { code: "GE", en: "Georgia", ru: "Грузия", es: "Georgia" },
  { code: "DE", en: "Germany", ru: "Германия", es: "Alemania" },
  { code: "GH", en: "Ghana", ru: "Гана", es: "Ghana" },
  { code: "GI", en: "Gibraltar", ru: "Гибралтар", es: "Gibraltar" },
  { code: "GR", en: "Greece", ru: "Греция", es: "Grecia" },
  { code: "GL", en: "Greenland", ru: "Гренландия", es: "Groenlandia" },
  { code: "GD", en: "Grenada", ru: "Гренада", es: "Granada" },
  { code: "GP", en: "Guadeloupe", ru: "Гваделупа", es: "Guadalupe" },
  { code: "GU", en: "Guam", ru: "Гуам", es: "Guam" },
  { code: "GT", en: "Guatemala", ru: "Гватемала", es: "Guatemala" },
  { code: "GG", en: "Guernsey", ru: "Гернси", es: "Guernesey" },
  { code: "GN", en: "Guinea", ru: "Гвинея", es: "Guinea" },
  { code: "GW", en: "Guinea-Bissau", ru: "Гвинея-Бисау", es: "Guinea-Bisáu" },
  { code: "GY", en: "Guyana", ru: "Гайана", es: "Guyana" },
  { code: "HT", en: "Haiti", ru: "Гаити", es: "Haití" },
  { code: "HN", en: "Honduras", ru: "Гондурас", es: "Honduras" },
  { code: "HK", en: "Hong Kong SAR China", ru: "Гонконг (САР)", es: "RAE de Hong Kong (China)" },
  { code: "HU", en: "Hungary", ru: "Венгрия", es: "Hungría" },
  { code: "IS", en: "Iceland", ru: "Исландия", es: "Islandia" },
  { code: "IN", en: "India", ru: "Индия", es: "India" },
  { code: "ID", en: "Indonesia", ru: "Индонезия", es: "Indonesia" },
  { code: "IR", en: "Iran", ru: "Иран", es: "Irán" },
  { code: "IQ", en: "Iraq", ru: "Ирак", es: "Irak" },
  { code: "IE", en: "Ireland", ru: "Ирландия", es: "Irlanda" },
  { code: "IM", en: "Isle of Man", ru: "о-в Мэн", es: "Isla de Man" },
  { code: "IL", en: "Israel", ru: "Израиль", es: "Israel" },
  { code: "IT", en: "Italy", ru: "Италия", es: "Italia" },
  { code: "JM", en: "Jamaica", ru: "Ямайка", es: "Jamaica" },
  { code: "JP", en: "Japan", ru: "Япония", es: "Japón" },
  { code: "JE", en: "Jersey", ru: "Джерси", es: "Jersey" },
  { code: "JO", en: "Jordan", ru: "Иордания", es: "Jordania" },
  { code: "KZ", en: "Kazakhstan", ru: "Казахстан", es: "Kazajistán" },
  { code: "KE", en: "Kenya", ru: "Кения", es: "Kenia" },
  { code: "KI", en: "Kiribati", ru: "Кирибати", es: "Kiribati" },
  { code: "XK", en: "Kosovo", ru: "Косово", es: "Kosovo" },
  { code: "KW", en: "Kuwait", ru: "Кувейт", es: "Kuwait" },
  { code: "KG", en: "Kyrgyzstan", ru: "Киргизия", es: "Kirguistán" },
  { code: "LA", en: "Laos", ru: "Лаос", es: "Laos" },
  { code: "LV", en: "Latvia", ru: "Латвия", es: "Letonia" },
  { code: "LB", en: "Lebanon", ru: "Ливан", es: "Líbano" },
  { code: "LS", en: "Lesotho", ru: "Лесото", es: "Lesoto" },
  { code: "LR", en: "Liberia", ru: "Либерия", es: "Liberia" },
  { code: "LY", en: "Libya", ru: "Ливия", es: "Libia" },
  { code: "LI", en: "Liechtenstein", ru: "Лихтенштейн", es: "Liechtenstein" },
  { code: "LT", en: "Lithuania", ru: "Литва", es: "Lituania" },
  { code: "LU", en: "Luxembourg", ru: "Люксембург", es: "Luxemburgo" },
  { code: "MO", en: "Macao SAR China", ru: "Макао (САР)", es: "RAE de Macao (China)" },
  { code: "MG", en: "Madagascar", ru: "Мадагаскар", es: "Madagascar" },
  { code: "MW", en: "Malawi", ru: "Малави", es: "Malaui" },
  { code: "MY", en: "Malaysia", ru: "Малайзия", es: "Malasia" },
  { code: "MV", en: "Maldives", ru: "Мальдивы", es: "Maldivas" },
  { code: "ML", en: "Mali", ru: "Мали", es: "Mali" },
  { code: "MT", en: "Malta", ru: "Мальта", es: "Malta" },
  { code: "MH", en: "Marshall Islands", ru: "Маршалловы о-ва", es: "Islas Marshall" },
  { code: "MQ", en: "Martinique", ru: "Мартиника", es: "Martinica" },
  { code: "MR", en: "Mauritania", ru: "Мавритания", es: "Mauritania" },
  { code: "MU", en: "Mauritius", ru: "Маврикий", es: "Mauricio" },
  { code: "YT", en: "Mayotte", ru: "Майотта", es: "Mayotte" },
  { code: "MX", en: "Mexico", ru: "Мексика", es: "México" },
  { code: "FM", en: "Micronesia", ru: "Федеративные Штаты Микронезии", es: "Micronesia" },
  { code: "MD", en: "Moldova", ru: "Молдова", es: "Moldavia" },
  { code: "MC", en: "Monaco", ru: "Монако", es: "Mónaco" },
  { code: "MN", en: "Mongolia", ru: "Монголия", es: "Mongolia" },
  { code: "ME", en: "Montenegro", ru: "Черногория", es: "Montenegro" },
  { code: "MS", en: "Montserrat", ru: "Монтсеррат", es: "Montserrat" },
  { code: "MA", en: "Morocco", ru: "Марокко", es: "Marruecos" },
  { code: "MZ", en: "Mozambique", ru: "Мозамбик", es: "Mozambique" },
  { code: "MM", en: "Myanmar (Burma)", ru: "Мьянма (Бирма)", es: "Myanmar (Birmania)" },
  { code: "NA", en: "Namibia", ru: "Намибия", es: "Namibia" },
  { code: "NR", en: "Nauru", ru: "Науру", es: "Nauru" },
  { code: "NP", en: "Nepal", ru: "Непал", es: "Nepal" },
  { code: "NL", en: "Netherlands", ru: "Нидерланды", es: "Países Bajos" },
  { code: "NC", en: "New Caledonia", ru: "Новая Каледония", es: "Nueva Caledonia" },
  { code: "NZ", en: "New Zealand", ru: "Новая Зеландия", es: "Nueva Zelanda" },
  { code: "NI", en: "Nicaragua", ru: "Никарагуа", es: "Nicaragua" },
  { code: "NE", en: "Niger", ru: "Нигер", es: "Níger" },
  { code: "NG", en: "Nigeria", ru: "Нигерия", es: "Nigeria" },
  { code: "NU", en: "Niue", ru: "Ниуэ", es: "Niue" },
  { code: "NF", en: "Norfolk Island", ru: "о-в Норфолк", es: "Isla Norfolk" },
  { code: "KP", en: "North Korea", ru: "КНДР", es: "Corea del Norte" },
  { code: "MK", en: "North Macedonia", ru: "Северная Македония", es: "Macedonia del Norte" },
  { code: "MP", en: "Northern Mariana Islands", ru: "Северные Марианские о-ва", es: "Islas Marianas del Norte" },
  { code: "NO", en: "Norway", ru: "Норвегия", es: "Noruega" },
  { code: "OM", en: "Oman", ru: "Оман", es: "Omán" },
  { code: "PK", en: "Pakistan", ru: "Пакистан", es: "Pakistán" },
  { code: "PW", en: "Palau", ru: "Палау", es: "Palaos" },
  { code: "PS", en: "Palestinian Territories", ru: "Палестинские территории", es: "Territorios Palestinos" },
  { code: "PA", en: "Panama", ru: "Панама", es: "Panamá" },
  { code: "PG", en: "Papua New Guinea", ru: "Папуа — Новая Гвинея", es: "Papúa Nueva Guinea" },
  { code: "PY", en: "Paraguay", ru: "Парагвай", es: "Paraguay" },
  { code: "PE", en: "Peru", ru: "Перу", es: "Perú" },
  { code: "PH", en: "Philippines", ru: "Филиппины", es: "Filipinas" },
  { code: "PL", en: "Poland", ru: "Польша", es: "Polonia" },
  { code: "PT", en: "Portugal", ru: "Португалия", es: "Portugal" },
  { code: "PR", en: "Puerto Rico", ru: "Пуэрто-Рико", es: "Puerto Rico" },
  { code: "QA", en: "Qatar", ru: "Катар", es: "Catar" },
  { code: "RO", en: "Romania", ru: "Румыния", es: "Rumanía" },
  { code: "RU", en: "Russia", ru: "Россия", es: "Rusia" },
  { code: "RW", en: "Rwanda", ru: "Руанда", es: "Ruanda" },
  { code: "RE", en: "Réunion", ru: "Реюньон", es: "Reunión" },
  { code: "WS", en: "Samoa", ru: "Самоа", es: "Samoa" },
  { code: "SM", en: "San Marino", ru: "Сан-Марино", es: "San Marino" },
  { code: "SA", en: "Saudi Arabia", ru: "Саудовская Аравия", es: "Arabia Saudí" },
  { code: "SN", en: "Senegal", ru: "Сенегал", es: "Senegal" },
  { code: "RS", en: "Serbia", ru: "Сербия", es: "Serbia" },
  { code: "SC", en: "Seychelles", ru: "Сейшельские о-ва", es: "Seychelles" },
  { code: "SL", en: "Sierra Leone", ru: "Сьерра-Леоне", es: "Sierra Leona" },
  { code: "SG", en: "Singapore", ru: "Сингапур", es: "Singapur" },
  { code: "SX", en: "Sint Maarten", ru: "Синт-Мартен", es: "Sint Maarten" },
  { code: "SK", en: "Slovakia", ru: "Словакия", es: "Eslovaquia" },
  { code: "SI", en: "Slovenia", ru: "Словения", es: "Eslovenia" },
  { code: "SB", en: "Solomon Islands", ru: "Соломоновы о-ва", es: "Islas Salomón" },
  { code: "SO", en: "Somalia", ru: "Сомали", es: "Somalia" },
  { code: "ZA", en: "South Africa", ru: "Южно-Африканская Республика", es: "Sudáfrica" },
  { code: "KR", en: "South Korea", ru: "Республика Корея", es: "Corea del Sur" },
  { code: "SS", en: "South Sudan", ru: "Южный Судан", es: "Sudán del Sur" },
  { code: "ES", en: "Spain", ru: "Испания", es: "España" },
  { code: "LK", en: "Sri Lanka", ru: "Шри-Ланка", es: "Sri Lanka" },
  { code: "BL", en: "St. Barthélemy", ru: "Сен-Бартелеми", es: "San Bartolomé" },
  { code: "KN", en: "St. Kitts & Nevis", ru: "Сент-Китс и Невис", es: "San Cristóbal y Nieves" },
  { code: "LC", en: "St. Lucia", ru: "Сент-Люсия", es: "Santa Lucía" },
  { code: "MF", en: "St. Martin", ru: "Сен-Мартен", es: "San Martín" },
  { code: "PM", en: "St. Pierre & Miquelon", ru: "Сен-Пьер и Микелон", es: "San Pedro y Miquelón" },
  { code: "VC", en: "St. Vincent & Grenadines", ru: "Сент-Винсент и Гренадины", es: "San Vicente y las Granadinas" },
  { code: "SD", en: "Sudan", ru: "Судан", es: "Sudán" },
  { code: "SR", en: "Suriname", ru: "Суринам", es: "Surinam" },
  { code: "SJ", en: "Svalbard & Jan Mayen", ru: "Шпицберген и Ян-Майен", es: "Svalbard y Jan Mayen" },
  { code: "SE", en: "Sweden", ru: "Швеция", es: "Suecia" },
  { code: "CH", en: "Switzerland", ru: "Швейцария", es: "Suiza" },
  { code: "SY", en: "Syria", ru: "Сирия", es: "Siria" },
  { code: "ST", en: "São Tomé & Príncipe", ru: "Сан-Томе и Принсипи", es: "Santo Tomé y Príncipe" },
  { code: "TW", en: "Taiwan", ru: "Тайвань", es: "Taiwán" },
  { code: "TJ", en: "Tajikistan", ru: "Таджикистан", es: "Tayikistán" },
  { code: "TZ", en: "Tanzania", ru: "Танзания", es: "Tanzania" },
  { code: "TH", en: "Thailand", ru: "Таиланд", es: "Tailandia" },
  { code: "TL", en: "Timor-Leste", ru: "Восточный Тимор", es: "Timor-Leste" },
  { code: "TG", en: "Togo", ru: "Того", es: "Togo" },
  { code: "TK", en: "Tokelau", ru: "Токелау", es: "Tokelau" },
  { code: "TO", en: "Tonga", ru: "Тонга", es: "Tonga" },
  { code: "TT", en: "Trinidad & Tobago", ru: "Тринидад и Тобаго", es: "Trinidad y Tobago" },
  { code: "TN", en: "Tunisia", ru: "Тунис", es: "Túnez" },
  { code: "TM", en: "Turkmenistan", ru: "Туркменистан", es: "Turkmenistán" },
  { code: "TC", en: "Turks & Caicos Islands", ru: "Тёркс и Кайкос", es: "Islas Turcas y Caicos" },
  { code: "TV", en: "Tuvalu", ru: "Тувалу", es: "Tuvalu" },
  { code: "TR", en: "Türkiye", ru: "Турция", es: "Turquía" },
  { code: "UM", en: "U.S. Outlying Islands", ru: "Внешние малые о-ва (США)", es: "Islas menores alejadas de EE. UU." },
  { code: "VI", en: "U.S. Virgin Islands", ru: "Виргинские о-ва (США)", es: "Islas Vírgenes de EE. UU." },
  { code: "UG", en: "Uganda", ru: "Уганда", es: "Uganda" },
  { code: "UA", en: "Ukraine", ru: "Украина", es: "Ucrania" },
  { code: "AE", en: "United Arab Emirates", ru: "ОАЭ", es: "Emiratos Árabes Unidos" },
  { code: "GB", en: "United Kingdom", ru: "Великобритания", es: "Reino Unido" },
  { code: "US", en: "United States", ru: "Соединенные Штаты", es: "Estados Unidos" },
  { code: "UY", en: "Uruguay", ru: "Уругвай", es: "Uruguay" },
  { code: "UZ", en: "Uzbekistan", ru: "Узбекистан", es: "Uzbekistán" },
  { code: "VU", en: "Vanuatu", ru: "Вануату", es: "Vanuatu" },
  { code: "VE", en: "Venezuela", ru: "Венесуэла", es: "Venezuela" },
  { code: "VN", en: "Vietnam", ru: "Вьетнам", es: "Vietnam" },
  { code: "WF", en: "Wallis & Futuna", ru: "Уоллис и Футуна", es: "Wallis y Futuna" },
  { code: "YE", en: "Yemen", ru: "Йемен", es: "Yemen" },
  { code: "ZM", en: "Zambia", ru: "Замбия", es: "Zambia" },
  { code: "ZW", en: "Zimbabwe", ru: "Зимбабве", es: "Zimbabue" },
  { code: "AX", en: "Åland Islands", ru: "Аландские о-ва", es: "Islas Aland" },
];

export interface LanguageEntry { code: string; en: string; ru: string; es: string; }
export const LANGUAGES: LanguageEntry[] = [
  { code: "ak", en: "Akan", ru: "Акан", es: "Akan" },
  { code: "sq", en: "Albanian", ru: "Албанский", es: "Albanés" },
  { code: "am", en: "Amharic", ru: "Амхарский", es: "Amárico" },
  { code: "ar", en: "Arabic", ru: "Арабский", es: "Árabe" },
  { code: "hy", en: "Armenian", ru: "Армянский", es: "Armenio" },
  { code: "az", en: "Azerbaijani", ru: "Азербайджанский", es: "Azerbaiyano" },
  { code: "bn", en: "Bangla", ru: "Бенгальский", es: "Bengalí" },
  { code: "bi", en: "Bislama", ru: "Бислама", es: "Bislama" },
  { code: "bs", en: "Bosnian", ru: "Боснийский", es: "Bosnio" },
  { code: "bg", en: "Bulgarian", ru: "Болгарский", es: "Búlgaro" },
  { code: "my", en: "Burmese", ru: "Бирманский", es: "Birmano" },
  { code: "ca", en: "Catalan", ru: "Каталанский", es: "Catalán" },
  { code: "zh", en: "Chinese", ru: "Китайский", es: "Chino" },
  { code: "hr", en: "Croatian", ru: "Хорватский", es: "Croata" },
  { code: "cs", en: "Czech", ru: "Чешский", es: "Checo" },
  { code: "da", en: "Danish", ru: "Датский", es: "Danés" },
  { code: "dv", en: "Divehi", ru: "Мальдивский", es: "Divehi" },
  { code: "nl", en: "Dutch", ru: "Нидерландский", es: "Neerlandés" },
  { code: "dz", en: "Dzongkha", ru: "Дзонг-кэ", es: "Dzongkha" },
  { code: "en", en: "English", ru: "Английский", es: "Inglés" },
  { code: "et", en: "Estonian", ru: "Эстонский", es: "Estonio" },
  { code: "fo", en: "Faroese", ru: "Фарерский", es: "Feroés" },
  { code: "fi", en: "Finnish", ru: "Финский", es: "Finés" },
  { code: "fr", en: "French", ru: "Французский", es: "Francés" },
  { code: "ka", en: "Georgian", ru: "Грузинский", es: "Georgiano" },
  { code: "de", en: "German", ru: "Немецкий", es: "Alemán" },
  { code: "el", en: "Greek", ru: "Греческий", es: "Griego" },
  { code: "gn", en: "Guarani", ru: "Гуарани", es: "Guaraní" },
  { code: "ht", en: "Haitian Creole", ru: "Гаитянский", es: "Criollo haitiano" },
  { code: "he", en: "Hebrew", ru: "Иврит", es: "Hebreo" },
  { code: "hi", en: "Hindi", ru: "Хинди", es: "Hindi" },
  { code: "hu", en: "Hungarian", ru: "Венгерский", es: "Húngaro" },
  { code: "is", en: "Icelandic", ru: "Исландский", es: "Islandés" },
  { code: "id", en: "Indonesian", ru: "Индонезийский", es: "Indonesio" },
  { code: "it", en: "Italian", ru: "Итальянский", es: "Italiano" },
  { code: "ja", en: "Japanese", ru: "Японский", es: "Japonés" },
  { code: "kl", en: "Kalaallisut", ru: "Гренландский", es: "Groenlandés" },
  { code: "km", en: "Khmer", ru: "Кхмерский", es: "Jemer" },
  { code: "rw", en: "Kinyarwanda", ru: "Киньяруанда", es: "Kinyarwanda" },
  { code: "ko", en: "Korean", ru: "Корейский", es: "Coreano" },
  { code: "ky", en: "Kyrgyz", ru: "Киргизский", es: "Kirguís" },
  { code: "lo", en: "Lao", ru: "Лаосский", es: "Lao" },
  { code: "lv", en: "Latvian", ru: "Латышский", es: "Letón" },
  { code: "lt", en: "Lithuanian", ru: "Литовский", es: "Lituano" },
  { code: "mk", en: "Macedonian", ru: "Македонский", es: "Macedonio" },
  { code: "mg", en: "Malagasy", ru: "Малагасийский", es: "Malgache" },
  { code: "ms", en: "Malay", ru: "Малайский", es: "Malayo" },
  { code: "mt", en: "Maltese", ru: "Мальтийский", es: "Maltés" },
  { code: "mn", en: "Mongolian", ru: "Монгольский", es: "Mongol" },
  { code: "ne", en: "Nepali", ru: "Непальский", es: "Nepalí" },
  { code: "nb", en: "Norwegian Bokmål", ru: "Норвежский букмол", es: "Noruego bokmal" },
  { code: "fa", en: "Persian", ru: "Персидский", es: "Persa" },
  { code: "pl", en: "Polish", ru: "Польский", es: "Polaco" },
  { code: "pt", en: "Portuguese", ru: "Португальский", es: "Portugués" },
  { code: "ro", en: "Romanian", ru: "Румынский", es: "Rumano" },
  { code: "rn", en: "Rundi", ru: "Рунди", es: "Kirundi" },
  { code: "ru", en: "Russian", ru: "Русский", es: "Ruso" },
  { code: "sm", en: "Samoan", ru: "Самоанский", es: "Samoano" },
  { code: "sg", en: "Sango", ru: "Санго", es: "Sango" },
  { code: "sr", en: "Serbian", ru: "Сербский", es: "Serbio" },
  { code: "sn", en: "Shona", ru: "Шона", es: "Shona" },
  { code: "si", en: "Sinhala", ru: "Сингальский", es: "Cingalés" },
  { code: "sk", en: "Slovak", ru: "Словацкий", es: "Eslovaco" },
  { code: "sl", en: "Slovenian", ru: "Словенский", es: "Esloveno" },
  { code: "so", en: "Somali", ru: "Сомали", es: "Somalí" },
  { code: "st", en: "Southern Sotho", ru: "Южный сото", es: "Sotho meridional" },
  { code: "es", en: "Spanish", ru: "Испанский", es: "Español" },
  { code: "sw", en: "Swahili", ru: "Суахили", es: "Suajili" },
  { code: "sv", en: "Swedish", ru: "Шведский", es: "Sueco" },
  { code: "tg", en: "Tajik", ru: "Таджикский", es: "Tayiko" },
  { code: "th", en: "Thai", ru: "Тайский", es: "Tailandés" },
  { code: "ti", en: "Tigrinya", ru: "Тигринья", es: "Tigriña" },
  { code: "to", en: "Tongan", ru: "Тонганский", es: "Tongano" },
  { code: "tr", en: "Turkish", ru: "Турецкий", es: "Turco" },
  { code: "tk", en: "Turkmen", ru: "Туркменский", es: "Turcomano" },
  { code: "uk", en: "Ukrainian", ru: "Украинский", es: "Ucraniano" },
  { code: "ur", en: "Urdu", ru: "Урду", es: "Urdu" },
  { code: "uz", en: "Uzbek", ru: "Узбекский", es: "Uzbeko" },
  { code: "vi", en: "Vietnamese", ru: "Вьетнамский", es: "Vietnamita" },
  { code: "wo", en: "Wolof", ru: "Волоф", es: "Wólof" },
];

export const OPERATING_SYSTEMS: string[] = [
  "iOS",
  "ChromeOS",
  "Android",
  "Linux",
  "Windows",
  "macOS",
  "Harmony",
  "BlackBerry",
  "FreeBSD",
  "Windows Phone",
  "other",
];

export const BROWSERS: string[] = [
  "Chrome",
  "Safari",
  "Edge",
  "Firefox",
  "Samsung Browser",
  "Opera",
  "Opera Touch",
  "Huawei Browser",
  "Miui Browser",
  "Quark",
  "Aloha",
  "YaBrowser",
  "YaSearchBrowser",
  "Android Browser",
  "HeyTap Browser",
  "UC Browser",
  "UC Turbo",
  "QQ Browser",
  "Vivo Browser",
  "Sber Browser",
  "Puffin",
  "JioSphere",
  "Chromium",
  "Vivaldi",
  "Coc Coc Browser",
  "Bing Browser",
  "Brave",
  "Maxthon",
  "Slimjet",
  "UR Browser",
  "DuckDuckGo Browser",
  "Whale Browser",
  "TV Bro",
  "other",
];

export const COUNTRY_CODES: string[] = COUNTRIES.map(c => c.code);
export const LANGUAGE_CODES: string[] = LANGUAGES.map(l => l.code);

export const DEVICE_TYPES = ["mobile", "tablet", "desktop", "other"];
