package bidEngine

import (
	"encoding/xml"
	"strings"

	"gitlab.com/twinbid-exchange/RTB-exchange/internal/constants"
	utils "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/utils_grpc"
)

type advVideoClickVAST struct {
	XMLName xml.Name `xml:"VAST"`
	Ad      struct {
		Inline struct {
			Creatives struct {
				Creative struct {
					Linear struct {
						VideoClicks struct {
							ClickThrough string `xml:"ClickThrough"`
						} `xml:"VideoClicks"`
					} `xml:"Linear"`
				} `xml:"Creative"`
			} `xml:"Creatives"`
		} `xml:"InLine"`
	} `xml:"Ad"`
}

// finalizeADVVideoVAST converts the private VAST generated by ADV into the
// public VAST returned to an SSP. Only our own ADV VAST passes this function;
// external DSP VAST follows the normal DSP path and remains untouched.
func finalizeADVVideoVAST(source, admDomain, globalID string) (string, bool) {
	if !validVASTADM(source) {
		return "", false
	}
	var parsed advVideoClickVAST
	if err := xml.Unmarshal([]byte(source), &parsed); err != nil || !strings.EqualFold(parsed.XMLName.Local, "VAST") {
		return "", false
	}
	destination := strings.TrimSpace(parsed.Ad.Inline.Creatives.Creative.Linear.VideoClicks.ClickThrough)
	if destination == "" {
		return "", false
	}
	clickURL := utils.WrapURL(admDomain, destination, globalID, constants.VID)
	impressionURL := utils.WrapVideoImpressionNoopURL(admDomain)
	if clickURL == "" || impressionURL == "" {
		return "", false
	}
	return rewriteADVVideoVAST(source, impressionURL, clickURL)
}

// rewriteADVVideoVAST changes only the two private placeholders in VAST that
// was generated by our own ADV. Keeping the original bytes is intentional:
// re-encoding with encoding/xml would expand namespaces and turn MediaFile
// CDATA into normal character data, making a valid VAST 4 document less
// interoperable with strict players.
func rewriteADVVideoVAST(source, impressionURL, clickURL string) (string, bool) {
	if !validVASTADM(source) || strings.TrimSpace(impressionURL) == "" || strings.TrimSpace(clickURL) == "" {
		return "", false
	}
	result, ok := replaceSingleVASTElementContent(source, "Impression", xmlEscapeText(impressionURL))
	if !ok {
		return "", false
	}
	result, ok = replaceSingleVASTElementContent(result, "ClickThrough", cdataText(clickURL))
	if !ok || !validVASTADM(result) {
		return "", false
	}
	return result, true
}

func replaceSingleVASTElementContent(source, localName, content string) (string, bool) {
	open := "<" + localName + ">"
	close := "</" + localName + ">"
	if strings.Count(source, open) != 1 || strings.Count(source, close) != 1 {
		return "", false
	}
	start := strings.Index(source, open)
	if start < 0 {
		return "", false
	}
	contentStart := start + len(open)
	endRelative := strings.Index(source[contentStart:], close)
	if endRelative < 0 {
		return "", false
	}
	end := contentStart + endRelative
	return source[:contentStart] + content + source[end:], true
}

func xmlEscapeText(value string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

func cdataText(value string) string {
	// CDATA cannot contain ]]> literally. Splitting into adjacent CDATA sections
	// preserves the original URL text without changing its semantics.
	return "<![CDATA[" + strings.ReplaceAll(value, "]]>", "]]]]><![CDATA[>") + "]]>"
}
