package bidEngine

import (
	"bytes"
	"encoding/xml"
	"io"
	"strings"

	"gitlab.com/twinbid-exchange/RTB-exchange/internal/constants"
	utils "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/utils_grpc"
)

type advVideoClickVAST struct {
	XMLName xml.Name `xml:"VAST"`
	Ad      struct {
		Inline struct {
			Creatives struct {
				Creative struct {
					Linear struct {
						VideoClicks struct {
							ClickThrough string `xml:"ClickThrough"`
						} `xml:"VideoClicks"`
					} `xml:"Linear"`
				} `xml:"Creative"`
			} `xml:"Creatives"`
		} `xml:"InLine"`
	} `xml:"Ad"`
}

// finalizeADVVideoVAST converts the private VAST generated by ADV into the
// public VAST returned to an SSP. Only our own ADV VAST passes this function;
// external DSP VAST follows the normal DSP path and remains untouched.
func finalizeADVVideoVAST(source, admDomain, globalID string) (string, bool) {
	if !validVASTADM(source) {
		return "", false
	}
	var parsed advVideoClickVAST
	if err := xml.Unmarshal([]byte(source), &parsed); err != nil || !strings.EqualFold(parsed.XMLName.Local, "VAST") {
		return "", false
	}
	destination := strings.TrimSpace(parsed.Ad.Inline.Creatives.Creative.Linear.VideoClicks.ClickThrough)
	if destination == "" {
		return "", false
	}
	clickURL := utils.WrapURL(admDomain, destination, globalID, constants.VID)
	impressionURL := utils.WrapVideoImpressionNoopURL(admDomain)
	if clickURL == "" || impressionURL == "" {
		return "", false
	}
	return rewriteADVVideoVAST(source, impressionURL, clickURL)
}

// rewriteADVVideoVAST uses XML tokens rather than string replacement, so URLs
// are escaped correctly and the rest of the generated VAST is preserved.
func rewriteADVVideoVAST(source, impressionURL, clickURL string) (string, bool) {
	decoder := xml.NewDecoder(strings.NewReader(source))
	var out bytes.Buffer
	encoder := xml.NewEncoder(&out)

	stack := make([]string, 0, 16)
	target := ""
	targetDepth := 0
	wroteTarget := false
	impressions := 0
	clicks := 0

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", false
		}

		switch t := token.(type) {
		case xml.StartElement:
			stack = append(stack, t.Name.Local)
			if target == "" {
				switch strings.ToLower(t.Name.Local) {
				case "impression":
					target = "impression"
					targetDepth = len(stack)
					wroteTarget = false
					impressions++
				case "clickthrough":
					target = "clickthrough"
					targetDepth = len(stack)
					wroteTarget = false
					clicks++
				}
			}
			if err := encoder.EncodeToken(token); err != nil {
				return "", false
			}
		case xml.CharData:
			if target != "" && len(stack) == targetDepth {
				if !wroteTarget {
					value := impressionURL
					if target == "clickthrough" {
						value = clickURL
					}
					if err := encoder.EncodeToken(xml.CharData([]byte(value))); err != nil {
						return "", false
					}
					wroteTarget = true
				}
				continue
			}
			if err := encoder.EncodeToken(token); err != nil {
				return "", false
			}
		case xml.EndElement:
			if target != "" && len(stack) == targetDepth {
				if !wroteTarget {
					value := impressionURL
					if target == "clickthrough" {
						value = clickURL
					}
					if err := encoder.EncodeToken(xml.CharData([]byte(value))); err != nil {
						return "", false
					}
				}
				target = ""
				targetDepth = 0
				wroteTarget = false
			}
			if err := encoder.EncodeToken(token); err != nil {
				return "", false
			}
			if len(stack) == 0 {
				return "", false
			}
			stack = stack[:len(stack)-1]
		default:
			if err := encoder.EncodeToken(token); err != nil {
				return "", false
			}
		}
	}
	if err := encoder.Flush(); err != nil {
		return "", false
	}
	if impressions != 1 || clicks != 1 || len(stack) != 0 {
		return "", false
	}
	result := out.String()
	if !validVASTADM(result) {
		return "", false
	}
	return result, true
}
