import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from "react";
import { setErrorTranslator } from "@/lib/apiStatus";
import { translateServerError } from "@/lib/serverErrors";

export type Lang = "en" | "ru" | "es" | "fr";

export const LANGUAGE_OPTIONS: { code: Lang; label: string; name: string }[] = [
  { code: "en", label: "EN", name: "English" },
  { code: "ru", label: "RU", name: "Russian" },
  { code: "es", label: "ES", name: "Spanish" },
  { code: "fr", label: "FR", name: "Français" },
];

const translations: Record<string, Record<"ru" | "en", string>> = {

  // Header / Nav
  "nav.benefits": { ru: "Преимущества", en: "Benefits" },
  "nav.formats": { ru: "Форматы", en: "Formats" },
  "nav.howToStart": { ru: "Как начать", en: "How to start" },
  "nav.login": { ru: "Войти", en: "Log in" },
  "nav.register": { ru: "Регистрация", en: "Sign up" },

  // Hero
  "hero.badge": { ru: "Рекламная платформа нового поколения", en: "Next-generation ad platform" },
  "hero.title1": { ru: "TwinBid — рекламная", en: "TwinBid — advertising" },
  "hero.title2": { ru: "платформа-агрегатор", en: "aggregator platform" },
  "hero.subtitle": { ru: "Объединяет трафик сотен рекламных сетей. Одна регистрация — и вы получаете доступ к инвентарю более чем", en: "Combines traffic from hundreds of ad networks. One registration — and you get access to inventory from more than" },
  "hero.subtitleSites": { ru: "1 млн сайтов", en: "1M websites" },
  "hero.subtitleEnd": { ru: "через единый кабинет закупки, аналитики и оптимизации.", en: "through a single dashboard for buying, analytics and optimization." },
  "hero.cta": { ru: "Зарегистрироваться", en: "Sign up" },
  "hero.learnMore": { ru: "Узнать больше", en: "Learn more" },
  "hero.statSites": { ru: "Сайтов", en: "Websites" },
  "hero.statNetworks": { ru: "Рекламных сетей", en: "Ad networks" },
  "hero.statSupport": { ru: "Поддержка", en: "Support" },

  // Start Conditions
  "start.conditionsLabel": { ru: "Условия старта", en: "Start conditions" },
  "start.minDeposit": { ru: "Минимальный депозит", en: "Minimum deposit" },
  "start.startSmall": { ru: "Начните с небольшого бюджета и масштабируйтесь", en: "Start with a small budget and scale up" },
  "start.bonusBadge": { ru: "Бонус новым пользователям", en: "Bonus for new users" },
  "start.bonusDesc": { ru: "к бюджету на первое пополнение — зарегистрируйтесь и получите дополнительные средства на запуск кампаний", en: "to your budget on first deposit — sign up and get extra funds to launch campaigns" },
  "start.getBonus": { ru: "Получить бонус", en: "Get bonus" },

  // Benefits
  "benefits.title1": { ru: "Почему ", en: "Why " },
  "benefits.title2": { ru: " — это удобно?", en: " is convenient?" },
  "benefits.subtitle": { ru: "Всё, что нужно для эффективной рекламы, в одном месте", en: "Everything you need for effective advertising, in one place" },
  "benefits.1.title": { ru: "Единый кабинет вместо десятков площадок", en: "One dashboard instead of dozens of platforms" },
  "benefits.1.desc": { ru: "Одна интеграция, один баланс, общая статистика и логика управления кампаниями. Вы экономите время команды и быстрее масштабируете то, что приносит результат.", en: "One integration, one balance, shared statistics and campaign management logic. You save team time and scale what works faster." },
  "benefits.2.title": { ru: "Максимальный инвентарь без потолков по CPM и CPC моделям", en: "Maximum inventory without CPM and CPC model limits" },
  "benefits.2.desc": { ru: "Трафик сотни тысяч сайтов уже доступен на нашей площадке. Остается только зарегистрироваться в пару кликов!", en: "Traffic from hundreds of thousands of sites is already available on our platform. Just sign up in a few clicks!" },
  "benefits.3.title": { ru: "Оплата только за реальный показ", en: "Pay only for real impressions" },
  "benefits.3.desc": { ru: "Мы засчитываем исключительно фактически показанную пользователю рекламу: учитываются только прогруженные страницы, а баннер/креатив должен находиться в зоне видимости пользователя определенное время. Меньше пустых расходов и больше отдачи от рекламы.", en: "We only count ads actually shown to users: only loaded pages count, and the banner/creative must be in the user's viewport for a certain time. Less wasted spend and more ad ROI." },
  "benefits.4.title": { ru: "Встроенная антифрод-система", en: "Built-in anti-fraud system" },
  "benefits.4.desc": { ru: "Система фильтрует подозрительные действия и снижает долю некачественного трафика, тем самым защищая бюджет от мусора.", en: "The system filters suspicious activity and reduces low-quality traffic, protecting your budget from waste." },
  "benefits.5.title": { ru: "AI-оптимизация кампаний: больше эффективности при том же бюджете", en: "AI campaign optimization: more efficiency with the same budget" },
  "benefits.5.desc": { ru: "Алгоритмы оптимизации перераспределяют показы в пользу сегментов и источников с лучшей отдачей, чтобы реклама попадала к максимально релевантной аудитории.", en: "Optimization algorithms redistribute impressions to segments and sources with the best returns, so ads reach the most relevant audience." },

  // Creative tools landing section
  "creativeTools.title": { ru: "Подготовьте креатив без лишних итераций", en: "Prepare your creative without extra iterations" },
  "creativeTools.subtitle": { ru: "Отредактируйте изображение под нужный формат и заранее проверьте, как реклама будет выглядеть на странице — всё прямо в кабинете TwinBid.", en: "Adjust the image to the required format and see how the ad will look on the page before launch — all inside TwinBid." },
  "creativeTools.edit.badge": { ru: "Встроенный редактор", en: "Built-in editor" },
  "creativeTools.edit.title": { ru: "Адаптируйте изображение прямо в кабинете", en: "Adjust the image right in the dashboard" },
  "creativeTools.edit.desc": { ru: "Загрузите изображение, выберите нужную область и приведите креатив к размеру рекламного формата. Если пропорции не подходят, TwinBid предложит обрезать изображение перед запуском.", en: "Upload an image, select the right area and fit the creative to the ad format. If the proportions do not match, TwinBid will offer to crop it before launch." },
  "creativeTools.preview.badge": { ru: "Предпросмотр размещения", en: "Placement preview" },
  "creativeTools.preview.title": { ru: "Увидьте рекламу глазами пользователя", en: "See the ad through the user's eyes" },
  "creativeTools.preview.desc": { ru: "Откройте предпросмотр и оцените изображение, текст, кнопку и общий вид объявления на странице. Исправьте детали до отправки кампании на модерацию.", en: "Open the preview to check the image, copy, button and the overall appearance of the ad on a page. Fix the details before submitting the campaign for moderation." },
  "creativeTools.note.fit": { ru: "Подгонка под формат", en: "Format-ready creative" },
  "creativeTools.note.preview": { ru: "Проверка до запуска", en: "Pre-launch preview" },

  // Formats
  "formats.title": { ru: "Форматы ", en: "Ad " },
  "formats.title2": { ru: "рекламы", en: "formats" },
  "formats.subtitle": { ru: "Выбирайте оптимальный формат для вашей кампании", en: "Choose the optimal format for your campaign" },
  "formats.popunder.desc": { ru: "Полноэкранная реклама, открывающаяся в новой вкладке. Максимальная видимость и высокий CTR.", en: "Full-screen ad opening in a new tab. Maximum visibility and high CTR." },
  "formats.native.desc": { ru: "Органично интегрированная реклама, которая соответствует стилю площадки. Высокое доверие пользователей.", en: "Natively integrated ads matching the platform's style. High user trust." },
  "formats.banner.desc": { ru: "Классические баннеры различных размеров. Узнаваемость бренда и широкий охват аудитории.", en: "Classic banners of various sizes. Brand awareness and wide audience reach." },
  "formats.push.desc": { ru: "Push-уведомления прямо на странице без подписки. Мгновенное привлечение внимания.", en: "Push notifications right on the page without subscription. Instant attention grabbing." },

  // Steps
  "steps.title1": { ru: "Как ", en: "How to " },
  "steps.title2": { ru: "начать?", en: "get started?" },
  "steps.subtitle": { ru: "Получи доступ к премиальному неограниченному трафику с сотен тысяч сайтов уже сегодня", en: "Get access to premium unlimited traffic from hundreds of thousands of sites today" },
  "steps.1.title": { ru: "Зарегистрируйте кабинет", en: "Register an account" },
  "steps.1.desc": { ru: "Зарегистрируйте кабинет пользователя — это займёт всего пару минут.", en: "Register a user account — it only takes a couple of minutes." },
  "steps.2.title": { ru: "Создайте кампанию", en: "Create a campaign" },
  "steps.2.desc": { ru: "Создайте свою первую кампанию, используя десятки точных таргетингов.", en: "Create your first campaign using dozens of precise targeting options." },
  "steps.3.title": { ru: "Пополните баланс", en: "Top up your balance" },
  "steps.3.desc": { ru: "Напишите менеджеру и пополните баланс. Получите +25% от суммы пополнения бонусом на первый депозит. Минимум — $100.", en: "Contact a manager and top up your balance. Get +25% of the deposit amount as a bonus on your first deposit. Minimum — $100." },
  "steps.4.title": { ru: "Масштабируйте", en: "Scale up" },
  "steps.4.desc": { ru: "Масштабируйте свои кампании с защитой от фрода и AI-оптимизацией.", en: "Scale your campaigns with fraud protection and AI optimization." },

  // CTA
  "cta.badge": { ru: "Начните уже сегодня", en: "Start today" },
  "cta.title": { ru: "Получи доступ к премиальному неограниченному трафику", en: "Get access to premium unlimited traffic" },
  "cta.subtitle": { ru: "Присоединяйтесь к TwinBid и получите +25% на первый депозит. Сотни тысяч сайтов уже ждут вашу рекламу.", en: "Join TwinBid and get +25% on your first deposit. Hundreds of thousands of sites are already waiting for your ads." },
  "cta.register": { ru: "Зарегистрироваться", en: "Sign up" },
  "cta.contact": { ru: "Связаться с нами", en: "Contact us" },
  "cta.trust1": { ru: "✓ Минимальный депозит $100", en: "✓ Minimum deposit $100" },
  "cta.trust2": { ru: "✓ +25% бонус", en: "✓ +25% bonus" },
  "cta.trust3": { ru: "✓ Мгновенный старт", en: "✓ Instant start" },

  // Marquee
  "marquee.tryTwinBid": { ru: "Попробуй TwinBid", en: "Try TwinBid" },
  "marquee.registerNow": { ru: "Зарегистрируйся сейчас", en: "Register now" },

  // Footer
  "footer.privacy": { ru: "Политика конфиденциальности", en: "Privacy Policy" },
  "footer.terms": { ru: "Условия использования", en: "Terms of Service" },
  "footer.docs": { ru: "Документация", en: "Documentation" },

  // Auth Dialog
  "auth.login": { ru: "Вход", en: "Log in" },
  "auth.register": { ru: "Регистрация", en: "Sign up" },
  "auth.email": { ru: "Email", en: "Email" },
  "auth.password": { ru: "Пароль", en: "Password" },
  "password.show": { ru: "Показать пароль", en: "Show password" },
  "password.hide": { ru: "Скрыть пароль", en: "Hide password" },
  "auth.passwordResetSupport": { ru: "Для сброса пароля свяжитесь с поддержкой.", en: "Contact support to reset your password." },
  "auth.name": { ru: "Имя (опционально)", en: "Name (optional)" },
  "auth.phone": { ru: "Телефон", en: "Phone" },
  "auth.telegram": { ru: "Telegram", en: "Telegram" },
  "auth.telegramRequired": { ru: "Укажите ваш Telegram", en: "Please enter your Telegram" },
  "auth.confirmPassword": { ru: "Подтвердите пароль", en: "Confirm password" },
  "auth.loginBtn": { ru: "Войти", en: "Log in" },
  "auth.registerBtn": { ru: "Зарегистрироваться", en: "Sign up" },
  "auth.passwordMismatch": { ru: "Пароли не совпадают", en: "Passwords do not match" },
  "auth.passwordTooShort": { ru: "Пароль должен содержать минимум 6 символов", en: "Password must be at least 6 characters" },
  "auth.checkEmail": { ru: "Проверьте вашу почту для подтверждения аккаунта", en: "Check your email to confirm your account" },
  "auth.error.confirmEmail": { ru: "Подтвердите email", en: "Please confirm your email" },
  "auth.error.invalidCredentials": { ru: "Неверный email или пароль", en: "Invalid email or password" },
  "auth.error.loginFailed": { ru: "Не удалось войти", en: "Sign in failed" },
  "auth.consent": {
    ru: "Я ознакомлен(а) и согласен(на) с Условиями использования и Политикой конфиденциальности, а также даю согласие на обработку моих персональных данных",
    en: "I have read and agree to the Terms of Use and Privacy Policy, and I consent to the processing of my personal data",
  },
  "auth.consent.terms": { ru: "Условиями использования", en: "Terms of Use" },
  "auth.consent.privacy": { ru: "Политикой конфиденциальности", en: "Privacy Policy" },
  "auth.consent.required": {
    ru: "Необходимо принять условия для регистрации",
    en: "You must accept the terms to sign up",
  },
  "auth.consent.intro": { ru: "Я ознакомлен(а) и согласен(на) с ", en: "I have read and agree to the " },
  "auth.consent.and": { ru: "и", en: "and" },
  "auth.consent.outro": {
    ru: ", а также даю согласие на обработку моих персональных данных",
    en: ", and I consent to the processing of my personal data",
  },


  // Legal page
  "legal.pageTitle": { ru: "Правовая информация", en: "Legal" },
  "legal.pageSubtitle": {
    ru: "Условия использования и Политика конфиденциальности TwinBid",
    en: "TwinBid Terms of Use and Privacy Policy",
  },
  "legal.back": { ru: "Назад", en: "Back" },
  "legal.contactText": {
    ru: "Остались вопросы? Свяжитесь с нами:",
    en: "Have questions? Contact us:",
  },

  // Verify email page
  "verify.loading": { ru: "Подтверждаем ваш аккаунт...", en: "Confirming your account..." },
  "verify.success.title": { ru: "Аккаунт подтверждён", en: "Account confirmed" },
  "verify.success.desc": { ru: "Ваш email успешно подтверждён. Теперь вы можете войти в кабинет.", en: "Your email has been confirmed. You can now sign in to your account." },
  "verify.already.title": { ru: "Аккаунт уже подтверждён", en: "Account already confirmed" },
  "verify.already.desc": { ru: "Этот аккаунт уже был подтверждён ранее.", en: "This account has already been confirmed." },
  "verify.invalid.title": { ru: "Недействительная ссылка", en: "Invalid link" },
  "verify.invalid.desc": { ru: "Ссылка для подтверждения недействительна или устарела, пройдите регистрацию заново.", en: "The confirmation link is invalid or expired, please sign up again." },
  "verify.goHome": { ru: "На главную", en: "Go home" },
  "verify.goLogin": { ru: "Войти", en: "Sign in" },

  // Dashboard Sidebar
  "sidebar.overview": { ru: "Обзор", en: "Overview" },
  "sidebar.campaigns": { ru: "Кампании", en: "Campaigns" },
  "sidebar.statistics": { ru: "Статистика", en: "Statistics" },
  "sidebar.trafficCalculator": { ru: "Калькулятор трафика", en: "Traffic calculator" },
  "sidebar.balance": { ru: "Баланс", en: "Balance" },
  "sidebar.settings": { ru: "Настройки", en: "Settings" },
  "sidebar.logout": { ru: "Выйти", en: "Log out" },

  // Dashboard Header
  "header.search": { ru: "Поиск кампаний...", en: "Search campaigns..." },
  "header.notifications": { ru: "Уведомления", en: "Notifications" },
  "header.noNotifications": { ru: "Нет уведомлений", en: "No notifications" },
  "header.advertiser": { ru: "Рекламодатель", en: "Advertiser" },
  "header.manager": { ru: "Персональный менеджер", en: "Personal manager" },

  // Dashboard Overview
  "overview.recentCampaigns": { ru: "Кампании", en: "Campaigns" },
  "overview.activeCampaignsTitle": { ru: "Активные кампании", en: "Active campaigns" },
  "overview.id": { ru: "ID", en: "ID" },
  "overview.name": { ru: "Название", en: "Name" },
  "overview.status": { ru: "Статус", en: "Status" },
  "overview.impressions": { ru: "Показы", en: "Impressions" },
  "overview.clicks": { ru: "Клики", en: "Clicks" },
  "overview.spent": { ru: "Расход", en: "Spent" },

  // StatsCards (overview) — labels reflect that widgets aggregate active campaigns only
  "statsCards.impressions": { ru: "Показы по активным кампаниям", en: "Impressions on active campaigns" },
  "statsCards.clicks": { ru: "Клики по активным кампаниям", en: "Clicks on active campaigns" },
  "statsCards.ctr": { ru: "CTR по активным кампаниям", en: "CTR of active campaigns" },

  // BalanceCard (overview)
  "balanceCard.title": { ru: "Баланс", en: "Balance" },
  "balanceCard.daysLeft": { ru: "≈ 14 дней показов", en: "≈ 14 days of impressions" },
  "balanceCard.topUp": { ru: "Пополнить", en: "Top up" },

  // Statuses
  "status.active": { ru: "Активна", en: "Active" },
  "status.paused": { ru: "На паузе", en: "Paused" },
  "status.draft": { ru: "Черновик", en: "Draft" },
  "status.completed": { ru: "Завершена", en: "Completed" },
  "status.moderation": { ru: "На модерации", en: "In moderation" },
  "status.no_budget": { ru: "Нет бюджета", en: "No budget" },
  "status.waiting": { ru: "Ожидает запуска", en: "Waiting" },

  // Balance page
  "balance.title": { ru: "Баланс и платежи", en: "Balance & Payments" },
  "balance.subtitle": { ru: "Пополнение через TwinBid Crypto, PassimPay и Cryptomus", en: "Top up with TwinBid Crypto, PassimPay or Cryptomus" },
  "balance.current": { ru: "Текущий баланс", en: "Current balance" },
  "balance.spentToday": { ru: "Потрачено сегодня", en: "Spent today" },
  "balance.spentWeek": { ru: "Потрачено за неделю", en: "Spent this week" },
  "balance.estimatedDays": { ru: "Хватит примерно на", en: "Estimated for" },
  "balance.days": { ru: "дней", en: "days" },
  "balance.topUp": { ru: "Пополнить баланс", en: "Top up balance" },
  "balance.amount": { ru: "Сумма", en: "Amount" },
  "balance.otherAmount": { ru: "Другая сумма", en: "Custom amount" },
  "balance.network": { ru: "Сеть", en: "Network" },
  "balance.topUpBtn": { ru: "Пополнить", en: "Top up" },
  "balance.minAmount": { ru: "Минимальная сумма — $100. Бонус +25% на первый депозит.", en: "Minimum amount — $100. +25% bonus on first deposit." },
  "balance.promo.label": { ru: "Промокод", en: "Promo code" },
  "balance.promo.placeholder": { ru: "Введите промокод", en: "Enter promo code" },
  "balance.promo.apply": { ru: "Применить", en: "Apply" },
  "balance.promo.remove": { ru: "Убрать", en: "Remove" },
  "balance.promo.applied": { ru: "Промокод применён! Бонус +{percent}% к пополнению", en: "Promo code applied! +{percent}% bonus to deposit" },
  "balance.promo.invalid": { ru: "Промокод не найден", en: "Promo code not found" },
  "balance.promo.alreadyUsed": { ru: "Вы уже использовали этот промокод", en: "You have already used this promo code" },
  "balance.promo.active": { ru: "Промокод {code} — бонус +{percent}%", en: "Promo code {code} — +{percent}% bonus" },
  "balance.promo.bonusShort": { ru: "бонус", en: "bonus" },
  "balance.promo.telegramPost": { ru: "Промокод — в закреплённом посте Telegram-канала", en: "Get the promo code from the pinned Telegram post" },
  "balance.paymentTitle": { ru: "Оплата", en: "Payment" },
  "balance.paymentDesc": { ru: "Переведите точную сумму на указанный адрес и вставьте хэш транзакции", en: "Transfer the exact amount to the specified address and paste the transaction hash" },
  "balance.topUpAmount": { ru: "Сумма пополнения:", en: "Top-up amount:" },
  "balance.walletAddress": { ru: "Адрес кошелька", en: "Wallet address" },
  "balance.transferNote": { ru: "Переведите точную сумму. Средства зачислятся после подтверждения сети.", en: "Transfer the exact amount. Funds will be credited after network confirmation." },
  "balance.txHash": { ru: "Хэш транзакции *", en: "Transaction hash *" },
  "balance.submit": { ru: "Отправить", en: "Submit" },
  "balance.cancelPayment": { ru: "Отменить оплату", en: "Cancel payment" },
  "balance.supportText": { ru: "По вопросам оплаты обращайтесь к вашему персональному менеджеру.", en: "For payment inquiries, please contact your personal manager." },
  "balance.inTelegram": { ru: "", en: "" },
  "balance.history": { ru: "История операций", en: "Transaction history" },
  "balance.date": { ru: "Дата", en: "Date" },
  "balance.description": { ru: "Описание", en: "Description" },
  "balance.amountCol": { ru: "Сумма", en: "Amount" },
  "balance.statusCol": { ru: "Статус", en: "Status" },
  "balance.topUpVia": { ru: "Пополнение", en: "Top-up" },
  "balance.created": { ru: "Создан", en: "Created" },
  "balance.completed": { ru: "Зачислено", en: "Credited" },
  "balance.pending": { ru: "В обработке", en: "Processing" },
  "balance.rejected": { ru: "Отклонено", en: "Rejected" },
  "balance.cancelled": { ru: "Отменено", en: "Cancelled" },
  "balance.noTransactions": { ru: "Нет операций", en: "No transactions" },
  "balance.crypto.choose": { ru: "После выбора укажите валюту и сеть", en: "Choose a currency and network after selecting" },
  "balance.passimpay.feeHint": { ru: "Комиссия 1% рассчитывается от суммы пополнения {amount}, без учёта бонуса: {fee}.", en: "The 1% fee is calculated from the deposit amount {amount}, excluding the bonus: {fee}." },
  "balance.passimpay.create": { ru: "Оплатить через PassimPay", en: "Pay with PassimPay" },
  "balance.payment.creating": { ru: "Создаём платёж...", en: "Creating payment..." },
  "balance.passimpay.title": { ru: "Оплата через PassimPay", en: "PassimPay payment" },
  "balance.passimpay.description": { ru: "Оплатите счёт в защищённом окне PassimPay. Баланс обновится после подтверждения оплаты.", en: "Pay the invoice in the secure PassimPay window. Your balance will update after confirmation." },
  "balance.passimpay.deposit": { ru: "Сумма пополнения", en: "Deposit amount" },
  "balance.passimpay.fee": { ru: "Комиссия (1%)", en: "Fee (1%)" },
  "balance.passimpay.credit": { ru: "Будет зачислено на баланс", en: "Amount credited to balance" },
  "balance.passimpay.open": { ru: "Перейти к оплате", en: "Proceed to payment" },
  "balance.passimpay.view": { ru: "Открыть платёж", en: "Open payment" },
  "balance.passimpay.check": { ru: "Проверить статус", en: "Check status" },
  "balance.passimpay.resume": { ru: "Продолжить оплату", en: "Continue payment" },
  "balance.passimpay.checking": { ru: "Проверяем...", en: "Checking..." },
  "balance.passimpay.creatingLink": { ru: "Формируем ссылку на оплату", en: "Creating payment link" },
  "balance.passimpay.waiting": { ru: "Ожидаем оплату", en: "Waiting for payment" },
  "balance.passimpay.paid": { ru: "Оплата зачислена", en: "Payment credited" },
  "balance.passimpay.failed": { ru: "Платёж не выполнен или истёк", en: "Payment failed or expired" },
  "balance.passimpay.done": { ru: "Готово", en: "Done" },
  "balance.passimpay.notCompleted": { ru: "Оплата через PassimPay не завершена", en: "PassimPay payment is not complete" },
  "balance.passimpay.pendingReason": { ru: "У вас уже есть незавершённая оплата через PassimPay. Продолжите её перед созданием новой.", en: "You already have an unfinished PassimPay payment. Continue it before creating a new one." },
  "balance.passimpay.checkingPayment": { ru: "Проверяем платёж", en: "Checking payment" },
  "balance.passimpay.partial": { ru: "Оплачено частично", en: "Partially paid" },
  "balance.passimpay.received": { ru: "Получено: {paid} из {total}", en: "Received: {paid} of {total}" },
  "balance.passimpay.cancelled": { ru: "Отменено", en: "Cancelled" },
  "balance.passimpay.error": { ru: "Ошибка платежа", en: "Payment error" },
  "balance.passimpay.unavailable": { ru: "Платёжный сервис временно недоступен. Попробуйте позднее или выберите TwinBid Crypto.", en: "The payment service is temporarily unavailable. Try again later or choose TwinBid Crypto." },
  "balance.passimpay.notFound": { ru: "Транзакция не найдена или недоступна.", en: "The transaction was not found or is unavailable." },
  "balance.cryptomus.feeHint": { ru: "Комиссия — 2,5%. Оплата откроется в защищённом окне Cryptomus.", en: "The fee is 2.5%. Payment will open in a secure Cryptomus window." },
  "balance.cryptomus.create": { ru: "Оплатить через Cryptomus", en: "Pay with Cryptomus" },
  "balance.cryptomus.title": { ru: "Оплата через Cryptomus", en: "Cryptomus payment" },
  "balance.cryptomus.description": { ru: "Оплатите счёт в защищённом окне Cryptomus. Баланс обновится после подтверждения оплаты.", en: "Pay the invoice in the secure Cryptomus window. Your balance will update after confirmation." },
  "balance.cryptomus.fee": { ru: "Комиссия (2,5%)", en: "Fee (2.5%)" },
  "balance.cryptomus.view": { ru: "Открыть платёж", en: "Open payment" },
  "balance.cryptomus.unavailable": { ru: "Cryptomus временно недоступен. Попробуйте позднее или выберите другой способ оплаты.", en: "Cryptomus is temporarily unavailable. Try again later or choose another payment method." },

  // Balance toasts
  "balance.toast.pendingExists": { ru: "У вас есть незавершённая оплата. Завершите или отмените её.", en: "You have a pending payment. Complete or cancel it." },
  "balance.toast.enterHash": { ru: "Введите хэш транзакции", en: "Enter transaction hash" },
  "balance.toast.paymentSent": { ru: "Платёж отправлен на проверку. Средства появятся на балансе в ближайшее время.", en: "Payment sent for review. Funds will appear on your balance shortly." },
  "balance.toast.paymentSupport": { ru: "По вопросам оплаты обращайтесь к вашему персональному менеджеру", en: "For payment inquiries please contact your personal manager" },
  "balance.toast.paymentCanceled": { ru: "Оплата отменена", en: "Payment cancelled" },
  "balance.toast.addressCopied": { ru: "Адрес скопирован", en: "Address copied" },
  "balance.toast.notCompleted": { ru: "Оплата не завершена. Проверьте уведомления.", en: "Payment not completed. Check notifications." },
  "balance.notif.notCompleted": { ru: "Оплата не завершена", en: "Payment not completed" },
  "balance.notif.noHash": { ru: "Вы не отправили хэш транзакции на", en: "You did not submit the transaction hash for" },
  "balance.notif.completePayment": { ru: "Завершить оплату", en: "Complete payment" },
  "balance.disabledReason": { ru: "У вас есть незавершённая оплата — завершите её или отмените, чтобы создать новую.", en: "You have an unfinished payment — complete or cancel it to start a new one." },
  "balance.notif.cancelConfirmTitle": { ru: "Отменить транзакцию?", en: "Cancel transaction?" },
  "balance.notif.cancelConfirmDesc": { ru: "Вы уверены, что хотите отменить незавершённую транзакцию? Это действие нельзя будет отменить.", en: "Are you sure you want to cancel the pending transaction? This action cannot be undone." },
  "balance.notif.cancelConfirmYes": { ru: "Да, отменить", en: "Yes, cancel" },
  "balance.notif.cancelConfirmNo": { ru: "Нет, оставить", en: "No, keep it" },
  "balance.notif.lowBalance": { ru: "Низкий баланс", en: "Low balance" },
  "balance.notif.lowBalanceDesc": { ru: "Ваш баланс составляет", en: "Your balance is" },
  "balance.notif.recommend": { ru: "Рекомендуем пополнить счёт.", en: "We recommend topping up." },
  "balance.notif.topUp": { ru: "Пополнить", en: "Top up" },
  "balance.notif.paymentSuccess": { ru: "Платёж отправлен", en: "Payment submitted" },
  "balance.notif.paymentSuccessDesc": { ru: "Платёж на сумму ${amount} отправлен на проверку. По вопросам обратитесь к вашему менеджеру.", en: "Payment of ${amount} sent for review. For any questions please contact your manager." },

  // Statistics
  "stats.title": { ru: "Статистика", en: "Statistics" },
  "stats.subtitle": { ru: "Подробная аналитика по вашим кампаниям", en: "Detailed analytics for your campaigns" },
  "stats.campaigns": { ru: "Кампании", en: "Campaigns" },
  "stats.allCampaigns": { ru: "Все кампании", en: "All campaigns" },
  "stats.selected": { ru: "Выбрано:", en: "Selected:" },
  "stats.period": { ru: "Период", en: "Period" },
  "stats.selectPeriod": { ru: "Выберите период", en: "Select period" },
  "stats.selectCampaign": { ru: "Выберите кампанию", en: "Select campaign" },
  "stats.selectAll": { ru: "Все кампании", en: "All campaigns" },
  "stats.refresh": { ru: "Обновить", en: "Refresh" },
  "stats.refreshed": { ru: "Статистика обновлена", en: "Statistics refreshed" },
  "stats.loading": { ru: "Статистика обновляется, подождите...", en: "Statistics are loading, please wait..." },
  "stats.impressions": { ru: "Показы", en: "Impressions" },
  "stats.clicks": { ru: "Клики", en: "Clicks" },
  "stats.ctr": { ru: "CTR", en: "CTR" },
  "stats.spent": { ru: "Расход", en: "Spent" },
  "stats.chartTitle": { ru: "Динамика показов", en: "Impressions dynamics" },
  "stats.byDates": { ru: "По датам", en: "By dates" },
  "stats.byHours": { ru: "По часам", en: "By hours" },
  "stats.byBrowsers": { ru: "По браузерам", en: "By browsers" },
  "stats.bySiteId": { ru: "По SiteID", en: "By SiteID" },
  "stats.byDevices": { ru: "По устройствам", en: "By devices" },
  "stats.byOS": { ru: "По ОС", en: "By OS" },
  "stats.byCountry": { ru: "По странам", en: "By countries" },
  "stats.date": { ru: "Дата", en: "Date" },
  "stats.dateAndHour": { ru: "Дата и час", en: "Date and hour" },
  "stats.browser": { ru: "Браузер", en: "Browser" },
  "stats.device": { ru: "Устройство", en: "Device" },
  "stats.os": { ru: "ОС", en: "OS" },
  "stats.country": { ru: "Страна", en: "Country" },
  "stats.total": { ru: "Итого", en: "Total" },
  "stats.noData": { ru: "Нет данных для выбранных фильтров", en: "No data for selected filters" },
  "stats.rows": { ru: "Строк", en: "Rows" },
  "stats.rowsAll": { ru: "Все", en: "All" },
  "stats.selectCampaignAndPeriod": { ru: "Выберите кампанию и период для просмотра статистики", en: "Select a campaign and period to view statistics" },
  "stats.filters": { ru: "Фильтры", en: "Filters" },
  "stats.filterCountry": { ru: "Страна", en: "Country" },
  "stats.filterBrowser": { ru: "Браузер", en: "Browser" },
  "stats.filterDevice": { ru: "Устройство", en: "Device" },
  "stats.filterOS": { ru: "ОС", en: "OS" },
  "stats.allValues": { ru: "Все", en: "All" },
  "stats.clearFilters": { ru: "Сбросить фильтры", en: "Clear filters" },
  "stats.creatives": { ru: "Креативы", en: "Creatives" },
  "stats.selectCreative": { ru: "Выберите креатив", en: "Select creative" },
  "stats.allCreatives": { ru: "Все креативы", en: "All creatives" },
  "stats.today": { ru: "Сегодня", en: "Today" },
  "stats.yesterday": { ru: "Вчера", en: "Yesterday" },
   "stats.week": { ru: "7 дней", en: "7 days" },
   "stats.month": { ru: "30 дней", en: "30 days" },
  "stats.chartTitleHours": { ru: "Динамика по часам", en: "Hourly dynamics" },

  // Campaigns page
  "campaigns.title": { ru: "Кампании", en: "Campaigns" },
  "campaigns.clicks": { ru: "Клики", en: "Clicks" },
  "campaigns.subtitle": { ru: "Управляйте вашими рекламными кампаниями", en: "Manage your ad campaigns" },
  "campaigns.create": { ru: "Создать кампанию", en: "Create campaign" },
  "campaigns.searchPlaceholder": { ru: "Поиск по названию или ID...", en: "Search by name or ID..." },
  "campaigns.allStatuses": { ru: "Все статусы", en: "All statuses" },
  "campaigns.activeFilter": { ru: "Активные", en: "Active" },
  "campaigns.pausedFilter": { ru: "На паузе", en: "Paused" },
  "campaigns.draftsFilter": { ru: "Черновики", en: "Drafts" },
  "campaigns.moderationFilter": { ru: "На модерации", en: "In moderation" },
  "campaigns.completedFilter": { ru: "Завершённые", en: "Completed" },
  "campaigns.noBudgetFilter": { ru: "Нет бюджета", en: "No budget" },
  "campaigns.waitingFilter": { ru: "Ожидает запуска", en: "Waiting" },
  "campaigns.total": { ru: "Всего", en: "Total" },
  "campaigns.activeCount": { ru: "Активных", en: "Active" },
  "campaigns.budget": { ru: "Бюджет", en: "Budget" },
  "campaigns.format": { ru: "Формат", en: "Format" },
  "campaigns.view": { ru: "Просмотр", en: "View" },
  "campaigns.openStatistics": { ru: "Открыть статистику", en: "Open statistics" },
  "campaigns.showId": { ru: "Показать ID кампании", en: "Show campaign ID" },
  "campaigns.campaignId": { ru: "ID кампании", en: "Campaign ID" },
  "campaigns.idHint": { ru: "Может понадобиться для поддержки и интеграций.", en: "You may need it for support and integrations." },
  "campaigns.copyId": { ru: "Скопировать ID", en: "Copy ID" },
  "campaigns.idCopied": { ru: "ID кампании скопирован", en: "Campaign ID copied" },
  "campaigns.actions": { ru: "Действия с кампанией", en: "Campaign actions" },
  "campaigns.showDetails": { ru: "Показать остальные показатели", en: "Show more metrics" },
  "campaigns.hideDetails": { ru: "Скрыть показатели", en: "Hide metrics" },
  "campaigns.rename": { ru: "Переименовать", en: "Rename" },
  "campaigns.renameTitle": { ru: "Переименовать кампанию", en: "Rename campaign" },
  "campaigns.renameDescription": { ru: "Введите новое название кампании.", en: "Enter a new campaign name." },
  "campaigns.name": { ru: "Название кампании", en: "Campaign name" },
  "campaigns.renameSave": { ru: "Сохранить название", en: "Save name" },
  "campaigns.renaming": { ru: "Сохранение...", en: "Saving..." },
  "campaigns.renamed": { ru: "Кампания переименована", en: "Campaign renamed" },
  "campaigns.renameFailed": { ru: "Не удалось переименовать кампанию", en: "Failed to rename campaign" },
  "campaigns.nameRequired": { ru: "Введите название кампании", en: "Enter a campaign name" },
  "campaigns.edit": { ru: "Редактировать", en: "Edit" },
  "campaigns.copy": { ru: "Копировать", en: "Copy" },
  "campaigns.copyPostfix": { ru: "(копия)", en: "(copy)" },
  "campaigns.pause": { ru: "Приостановить", en: "Pause" },
  "campaigns.start": { ru: "Запустить", en: "Start" },
  "campaigns.finishCreation": { ru: "Завершить создание", en: "Finish creation" },
  "campaigns.delete": { ru: "Удалить", en: "Delete" },
  "campaigns.notFound": { ru: "Кампании не найдены", en: "No campaigns found" },
  "campaigns.deleteConfirm": { ru: "Удалить кампанию?", en: "Delete campaign?" },
  "campaigns.deleteDesc": { ru: "Это действие нельзя отменить. Кампания будет удалена навсегда.", en: "This action cannot be undone. The campaign will be permanently deleted." },
  "campaigns.cancel": { ru: "Отмена", en: "Cancel" },
  "campaigns.started": { ru: "Кампания запущена", en: "Campaign started" },
  "campaigns.paused": { ru: "Кампания приостановлена", en: "Campaign paused" },
  "campaigns.deleted": { ru: "Кампания удалена", en: "Campaign deleted" },
  "campaigns.copied": { ru: "Кампания скопирована", en: "Campaign copied" },
  "campaigns.restart": { ru: "Перезапустить", en: "Restart" },
  "campaigns.restarted": { ru: "Обновите даты и сохраните для перезапуска", en: "Update dates and save to restart" },
  "campaigns.increaseBudget": { ru: "Увеличить бюджет", en: "Increase budget" },
  "campaigns.increaseBudgetHint": { ru: "Увеличьте бюджет и сохраните, чтобы возобновить кампанию", en: "Increase the budget and save to resume the campaign" },
  "edit.errorBudgetMustIncrease": { ru: "Чтобы возобновить кампанию, увеличьте бюджет", en: "Increase the budget to resume the campaign" },
  "campaigns.cancelModeration": { ru: "Отменить модерацию", en: "Cancel moderation" },
  "campaigns.moderationCanceled": { ru: "Модерация отменена", en: "Moderation cancelled" },
  "campaigns.draftIncomplete": { ru: "Завершите настройку кампании перед запуском", en: "Complete campaign setup before launching" },

  // Settings
  "settings.title": { ru: "Настройки", en: "Settings" },
  "settings.subtitle": { ru: "Управление аккаунтом и предпочтениями", en: "Account and preferences management" },
  "settings.profile": { ru: "Профиль", en: "Profile" },
  "settings.notifications": { ru: "Уведомления", en: "Notifications" },
  "settings.security": { ru: "Безопасность", en: "Security" },
  "settings.appearance": { ru: "Цвет интерфейса", en: "Interface color" },
  "settings.appearanceDescription": { ru: "Выберите цветовую схему кабинета. Настройка сохранится на этом устройстве.", en: "Choose the dashboard color scheme. The setting will be saved on this device." },
  "settings.darkTheme": { ru: "Тёмная тема", en: "Dark theme" },
  "settings.darkThemeDescription": { ru: "Текущее тёмное оформление TwinBid.", en: "The current dark TwinBid appearance." },
  "settings.lightTheme": { ru: "Светлая тема", en: "Light theme" },
  "settings.lightThemeDescription": { ru: "Светлый фон и контрастные рабочие панели.", en: "A light background with high-contrast workspace panels." },
  "settings.name": { ru: "Имя", en: "Name" },
  "settings.email": { ru: "Email", en: "Email" },
  "settings.telegram": { ru: "Telegram", en: "Telegram" },
  "settings.timezone": { ru: "Часовой пояс", en: "Timezone" },
  "settings.save": { ru: "Сохранить", en: "Save" },
  "settings.saved": { ru: "Настройки сохранены", en: "Settings saved" },
  "settings.emailNotifications": { ru: "Email-уведомления", en: "Email notifications" },
  "settings.campaignStatus": { ru: "Изменения статуса кампаний", en: "Campaign status changes" },
  "settings.lowBalance": { ru: "Низкий баланс", en: "Low balance" },
  "settings.balanceThreshold": { ru: "Порог баланса для уведомления", en: "Balance threshold for notification" },
  "settings.currentPassword": { ru: "Текущий пароль", en: "Current password" },
  "settings.newPassword": { ru: "Новый пароль", en: "New password" },
  "settings.repeatPassword": { ru: "Повторите пароль", en: "Repeat password" },
  "settings.changePassword": { ru: "Сменить пароль", en: "Change password" },
  "settings.passwordUpdated": { ru: "Пароль обновлён", en: "Password updated" },

  // Create Campaign
  "create.title": { ru: "Создание кампании", en: "Create campaign" },
  "create.step": { ru: "Шаг", en: "Step" },
  "create.of": { ru: "из", en: "of" },
  "create.step1": { ru: "Основная информация и креатив", en: "Basic info and creative" },
  "create.step2": { ru: "Таргетинг и списки", en: "Targeting and lists" },
  "create.step3": { ru: "Бюджет и расписание", en: "Budget and schedule" },
  "create.trafficType": { ru: "Тип трафика", en: "Traffic type" },
  "create.mainstream": { ru: "Мейнстрим", en: "Mainstream" },
  "create.adult": { ru: "Адалт", en: "Adult" },
  "create.mixed": { ru: "Миксед (смешанный)", en: "Mixed" },
  "create.trafficTypeHint": { ru: "Где вы хотите показывать кампанию", en: "Where do you want to show the campaign" },
  "create.campaignName": { ru: "Название кампании *", en: "Campaign name *" },
  "create.campaignNamePlaceholder": { ru: "Например: Летняя распродажа", en: "E.g.: Summer sale" },
  "create.adFormat": { ru: "Формат рекламы *", en: "Ad format *" },
  "create.selectFormat": { ru: "Выберите формат", en: "Select format" },
  "create.creativeFor": { ru: "Креатив для формата", en: "Creative for format" },
  "create.creatives": { ru: "Креативы", en: "Creatives" },
  "create.creative": { ru: "Креатив", en: "Creative" },
  "create.addCreative": { ru: "Добавить креатив", en: "Add creative" },
  "create.generateAllBannerSizes": { ru: "Создать все размеры", en: "Create all sizes" },
  "create.generateAllBannerSizesHint": { ru: "Больше размеров — больше доступных рекламных мест и выше охват кампании. Мы создадим 4 креатива из этого визуала — вам останется подрезать каждый под выбранный размер.", en: "More sizes unlock more ad placements and increase campaign reach. We'll create 4 creatives from this visual — you only need to crop each one to its selected size." },
  "create.allBannerSizesCreated": { ru: "Созданы креативы всех размеров", en: "Creatives for all sizes created" },
  "create.bannerSize": { ru: "Размер баннера", en: "Banner size" },
  "create.selectBannerSize": { ru: "Выберите размер", en: "Select size" },
  "create.brandName": { ru: "Название бренда", en: "Brand name" },
  "create.brandNamePlaceholder": { ru: "Например: MyBrand", en: "E.g.: MyBrand" },
  "create.optional": { ru: "опционально", en: "optional" },
  "create.creativeName": { ru: "Название креатива", en: "Creative name" },
  "create.creativeNamePlaceholder": { ru: "Например: Баннер лето 2024", en: "E.g.: Summer banner 2024" },
  "create.creativeNameHint": { ru: "Используется для фильтрации по креативам в статистике", en: "Used for filtering by creatives in statistics" },
  "create.titlePlaceholder": { ru: "Заголовок объявления", en: "Ad headline" },
  "create.descriptionPlaceholder": { ru: "Описание объявления...", en: "Ad description..." },
  "create.required": { ru: "Обязательное поле", en: "Required field" },
  "create.selectFormatError": { ru: "Выберите формат", en: "Select format" },
  "create.back": { ru: "Назад", en: "Back" },
  "create.next": { ru: "Далее", en: "Next" },
  "create.createBtn": { ru: "Создать кампанию", en: "Create campaign" },
  "create.created": { ru: "Кампания создана и отправлена на модерацию!", en: "Campaign created and sent for moderation!" },
  "create.draftSaved": { ru: "Кампания сохранена в черновики", en: "Campaign saved as draft" },
  "create.draftSavedDesc": { ru: "Создание кампании не завершено. Вы можете продолжить редактирование в любое время.", en: "Campaign creation is not finished. You can continue editing at any time." },
  "create.uploadImage": { ru: "Загрузить изображение", en: "Upload image" },
  "create.uploadBannerMedia": { ru: "Загрузить визуал", en: "Upload visual" },
  "create.imageUploaded": { ru: "Изображение загружено", en: "Image uploaded" },
  "create.imageFormatError": { ru: "Неверный формат. Поддерживаются: PNG, JPG, JPEG, GIF", en: "Invalid format. Supported: PNG, JPG, JPEG, GIF" },
  "create.bannerMediaFormatError": { ru: "Неверный формат. Поддерживаются: PNG, JPG, JPEG, GIF и MP4", en: "Invalid format. Supported: PNG, JPG, JPEG, GIF and MP4" },
  "create.imageFormatHint": { ru: "PNG, JPG или GIF, до 1 МБ", en: "PNG, JPG or GIF, up to 1 MB" },
  "create.bannerMediaFormatHint": { ru: "PNG, JPG или GIF до 1 МБ; MP4 до 10 МБ", en: "PNG, JPG or GIF up to 1 MB; MP4 up to 10 MB" },
  "create.imageSizeError": { ru: "Размер изображения не должен превышать 1 МБ", en: "Image size must not exceed 1 MB" },
  "create.videoSizeError": { ru: "Размер MP4-файла не должен превышать 10 МБ", en: "MP4 file size must not exceed 10 MB" },
  "create.videoUploaded": { ru: "Видео загружено", en: "Video uploaded" },
  "create.creativeLimit": { ru: "Можно добавить не более {max} креативов на кампанию", en: "You can add up to {max} creatives per campaign" },
  "create.imageWrongSize": { ru: "Размер не соответствует требуемому ({w}×{h}). Если не обрежете вручную, картинка будет автоматически подогнана под формат при сохранении.", en: "Size doesn't match required ({w}×{h}). If you don't crop it manually, the image will be auto-fit to the format on save." },
  "create.videoExactSize": { ru: "Размер видео не соответствует требуемому ({w}×{h}). Обрежьте видимую область перед сохранением.", en: "Video size doesn't match the required size ({w}×{h}). Crop the visible area before saving." },
  "create.editImage": { ru: "Редактировать", en: "Edit" },
  "create.previewCreative": { ru: "Предпросмотр", en: "Preview" },

  // Banner creative type selector (image / html / iframe) — banner format only
  "create.creativeType": { ru: "Тип креатива", en: "Creative type" },
  "create.creativeTypeImage": { ru: "Изображение", en: "Image" },
  "create.creativeTypeHtml": { ru: "HTML-код", en: "HTML code" },
  "create.creativeTypeIframe": { ru: "iframe", en: "iframe" },
  "create.htmlCode": { ru: "HTML-код баннера *", en: "Banner HTML code *" },
  "create.htmlCodePlaceholder": { ru: "<html>...</html>", en: "<html>...</html>" },
  "create.htmlCodeHint": { ru: "Вставьте полный HTML-код баннера. Отдельно загружать изображение не нужно. Размер содержимого должен быть {w}×{h}px.", en: "Paste the full banner HTML. No separate image upload is needed. The content size must be {w}×{h}px." },
  "create.httpUrlWarning": { ru: "HTTP-ссылка может привести к блокировке показа рекламы на некоторых источниках. По возможности используйте HTTPS.", en: "An HTTP URL may cause ad delivery to be blocked on some publisher sources. Use HTTPS when possible." },
  "create.iframeUrl": { ru: "URL iframe *", en: "iframe URL *" },
  "create.iframeUrlPlaceholder": { ru: "http://example.com/banner", en: "http://example.com/banner" },
  "create.iframeUrlHint": { ru: "Укажите абсолютный URL с протоколом HTTP или HTTPS, который отдаёт содержимое размера {w}×{h}px.", en: "Enter an absolute HTTP or HTTPS URL that serves content of size {w}×{h}px." },
  "create.iframeUrlInvalid": { ru: "Введите корректный абсолютный URL (HTTP/HTTPS)", en: "Enter a valid absolute URL (HTTP/HTTPS)" },
  "create.iframeExplanation": {
    ru: "iframe — это окно внутри рекламного места, в котором загружается содержимое по вашей ссылке. Достаточно указать URL: TwinBid сам создаст код нужного размера и передаст его для показа.",
    en: "An iframe is a window inside the ad placement that loads content from your URL. Enter the URL and TwinBid will create the correctly sized code for delivery.",
  },
  "create.iframeSizeConfirm": { ru: "Подтверждаю, что содержимое iframe имеет размер {w}×{h}px", en: "I confirm the iframe content is {w}×{h}px" },
  "create.htmlSizeMismatch": { ru: "Размер содержимого HTML ({actualW}×{actualH}) не совпадает с требуемым {w}×{h}. Исправьте перед продолжением.", en: "HTML content size ({actualW}×{actualH}) doesn't match the required {w}×{h}. Fix before continuing." },
  "create.iframeSizeMismatch": { ru: "Размер содержимого iframe ({actualW}×{actualH}) не совпадает с требуемым {w}×{h}. Исправьте перед продолжением.", en: "iframe content size ({actualW}×{actualH}) doesn't match the required {w}×{h}. Fix before continuing." },
  "create.iframeSizeUnknown": { ru: "Не удалось автоматически определить размер iframe (cross-origin). Подтвердите вручную ниже.", en: "Couldn't automatically detect iframe size (cross-origin). Please confirm manually below." },
  "create.iframeModeUrl": { ru: "Ссылка", en: "URL" },
  "create.iframeModeCode": { ru: "Код iframe", en: "iframe code" },
  "create.iframeCode": { ru: "Код iframe *", en: "iframe code *" },
  "create.iframeCodePlaceholder": { ru: '<iframe src="http://example.com/banner" width="300" height="250"></iframe>', en: '<iframe src="http://example.com/banner" width="300" height="250"></iframe>' },
  "create.iframeCodeNoSrc": { ru: "Не удалось найти атрибут src в коде iframe.", en: "Couldn't find a src attribute in the iframe code." },
  "create.uploadHtmlFile": { ru: "Загрузить HTML-файл", en: "Upload HTML file" },
  "create.htmlFileUploaded": { ru: "HTML-файл загружен", en: "HTML file uploaded" },
  "create.htmlFileFormatError": { ru: "Неверный формат. Поддерживается .html / .htm", en: "Invalid format. Supported: .html / .htm" },
  "create.htmlFileSizeError": { ru: "Размер HTML-файла не должен превышать 1 МБ", en: "HTML file size must not exceed 1 MB" },
  "create.previewTitle": { ru: "Как креатив будет показан на сайте", en: "How the creative will look on a site" },
  "create.previewDesktop": { ru: "Десктоп", en: "Desktop" },
  "create.previewMobile": { ru: "Мобильный", en: "Mobile" },
  "create.previewDisclaimer": { ru: "Примерный вид. На разных площадках оформление может отличаться.", en: "Approximate look. Rendering may differ across sites." },
  "create.previewPopunderNote": { ru: "Popunder открывается как отдельная вкладка с вашим URL — предпросмотр не требуется.", en: "Popunder opens as a new tab with your URL — no preview needed." },
  "create.cropTitle": { ru: "Редактор видимой области", en: "Visible area editor" },
  "create.cropSave": { ru: "Сохранить", en: "Save" },
  "create.cropCancel": { ru: "Отмена", en: "Cancel" },
  "create.cropZoom": { ru: "Масштаб", en: "Zoom" },
  "create.cropHintFixed": { ru: "Перетащите визуал под рамку — в креатив попадёт только область внутри неё", en: "Drag the visual under the frame — only the area inside it will appear in the creative" },
  "create.cropHintSquare": { ru: "Перетащите визуал и растяните рамку", en: "Drag the visual and resize the frame" },
  "create.cropTooLarge": { ru: "Итоговое изображение больше 1 МБ, уменьшите область/зум", en: "Output image exceeds 1 MB, reduce area/zoom" },
  "create.gifExactSize": { ru: "GIF должен быть точно {w}×{h} пикселей", en: "GIF must be exactly {w}×{h} pixels" },
  "create.cropGifTooLarge": { ru: "После обрезки GIF превышает 1 МБ. Выберите меньшую область или загрузите более лёгкий файл.", en: "The cropped GIF exceeds 1 MB. Select a smaller area or upload a lighter file." },
  "create.cropVideoTooLarge": { ru: "После обрезки MP4 превышает 10 МБ. Загрузите более лёгкий файл.", en: "The cropped MP4 exceeds 10 MB. Upload a lighter file." },
  "create.cropFailed": { ru: "Не удалось обрезать визуал. Проверьте файл и попробуйте ещё раз.", en: "Couldn't crop the visual. Check the file and try again." },
  "create.mismatchConfirmTitle": { ru: "Размер картинки не соответствует", en: "Image size doesn't match" },
  "create.mismatchConfirmBody": { ru: "У некоторых креативов размер картинки не совпадает с требуемым.", en: "Some creatives have images that don't match the required size." },
  "create.mismatchSaveAnyway": { ru: "Обрезать и сохранить", en: "Auto-crop and save" },
  "create.mismatchGoEdit": { ru: "Отредактировать вручную", en: "Edit manually" },
  "create.autoCropBody": { ru: "Ниже показано, как картинки будут автоматически обрезаны под требуемый формат. Подтвердите, чтобы сохранить, или вернитесь и обрежьте вручную.", en: "Below is how images will be auto-cropped to fit the required format. Confirm to save, or go back to edit manually." },
  "create.autoCropPreparing": { ru: "Готовим превью…", en: "Preparing preview…" },
  "create.autoCropBefore": { ru: "Оригинал", en: "Original" },
  "create.autoCropAfter": { ru: "После обрезки", en: "After crop" },
  "create.autoCropConfirm": { ru: "Обрезать и сохранить", en: "Auto-crop and save" },
  "create.autoCropGifSkip": { ru: "Для GIF и MP4 нужно вручную выбрать видимую область в редакторе.", en: "For GIF and MP4, select the visible area manually in the editor." },
  "create.autoCropGifNote": { ru: "Сохранение заблокировано: откройте редактор и обрежьте видимую область GIF или MP4 под требуемый размер.", en: "Saving is blocked: open the editor and crop the visible area of the GIF or MP4 to the required size." },
  "create.autoCropError": { ru: "Не удалось подготовить превью. Отредактируйте вручную.", en: "Failed to prepare preview. Please edit manually." },
  "create.creativeTitle": { ru: "Заголовок", en: "Title" },
  "create.creativeDescription": { ru: "Описание", en: "Description" },
  "create.visibleTextLengthHint": { ru: "Рекомендуем не больше 80 символов", en: "We recommend no more than 80 characters" },
  "create.creativeUrl": { ru: "Ссылка", en: "URL" },
  "create.urlMacrosHint": { ru: "Нажмите для добавления макросов отслеживания:", en: "Click to add tracking macros:" },
  "create.urlMacroNamesWarning": {
    ru: "Базовые названия параметров, выделенные жёлтым, необходимо заменить на названия, которые обрабатывает ваша партнёрская сеть или трекер. Это необходимо для корректной работы статистики. Если их не заменить, будут передаваться базовые названия, которые партнёрская сеть может не распознать.",
    en: "Replace the default parameter names highlighted in yellow with the names supported by your affiliate network or tracker. This is required for correct statistics. Otherwise, the default names will be sent and may not be recognized by the affiliate network.",
  },
  "create.endDateError": { ru: "Дата окончания не может быть раньше сегодняшнего дня", en: "End date cannot be earlier than today" },
  "create.endDateRequired": { ru: "Укажите корректные даты для завершения создания", en: "Specify valid dates to complete creation" },
  "create.step4": { ru: "Отслеживание конверсий", en: "Conversion tracking" },
  "create.creating": { ru: "Кампания создаётся, пожалуйста, подождите...", en: "Creating campaign, please wait..." },

  // Postback / conversion tracking
  "postback.urlLabel": { ru: "Postback URL", en: "Postback URL" },
  "postback.copy": { ru: "Копировать", en: "Copy" },
  "postback.copied": { ru: "Скопировано", en: "Copied" },
  "postback.copyFailed": { ru: "Не удалось скопировать", en: "Failed to copy" },
  "postback.help1": {
    ru: "Скопируйте Postback URL и добавьте его в настройках вашего трекера, CPA-сети или прямого рекламодателя.",
    en: "Copy the Postback URL and add it to the settings of your tracker, CPA network or direct advertiser.",
  },
  "postback.help2": {
    ru: "Когда по вашей кампании произойдёт конверсия, система отправит нам информацию об этом по данной ссылке. После этого конверсия появится в статистике кампании, и вы сможете оценивать эффективность трафика и доход прямо внутри нашей платформы.",
    en: "When a conversion occurs in your campaign, the system will send us information about it via this URL. After that the conversion will appear in the campaign statistics, and you'll be able to evaluate traffic efficiency and revenue right inside our platform.",
  },
  "postback.help3": {
    ru: "Ссылка статичная и не меняется — её можно использовать для всех кампаний.",
    en: "The link is static and does not change — you can use it for all campaigns.",
  },
  "postback.payoutLabel": { ru: "Выплата за конверсию", en: "Conversion payout" },
  "postback.payoutHint": {
    ru: "Если выплата по конверсии не будет автоматически передана через postback, в статистике будет использоваться значение из этого поля.",
    en: "If the conversion payout is not delivered automatically via postback, the value from this field will be used in statistics.",
  },

  // Stats CSV export
  "stats.downloadCsv": { ru: "Скачать CSV", en: "Download CSV" },
  "stats.showConversions": { ru: "Показывать конверсии", en: "Show conversions" },
  "stats.postbackHint": {
    ru: "Для отслеживания конверсий используйте Postback URL из настроек кампании.",
    en: "To track conversions, use the Postback URL from your campaign settings.",
  },
  "stats.conversions": { ru: "Конверсии", en: "Conversions" },
  "stats.cr": { ru: "CR", en: "CR" },
  "stats.income": { ru: "Доход", en: "Income" },
  "stats.roi": { ru: "ROI", en: "ROI" },
  "stats.cpm": { ru: "CPM", en: "CPM" },
  "stats.cpc": { ru: "CPC", en: "CPC" },
  "stats.confirmed": { ru: "Подтв.", en: "Confirmed" },
  "stats.confirmedConversions": { ru: "Подтв. конверсии", en: "Confirmed conversions" },
  "stats.confirmedIncome": { ru: "Подтв. доход", en: "Confirmed income" },
  "stats.columns": { ru: "Колонки", en: "Columns" },
  "stats.groupTraffic": { ru: "Трафик", en: "Traffic" },
  "stats.groupCost": { ru: "Стоимость", en: "Cost" },
  "stats.groupConversions": { ru: "Конверсии", en: "Conversions" },
  "stats.cleaner.description": { ru: "Отберите источники по статистике и сразу добавьте их в White- или Blacklist кампании.", en: "Select sources from statistics and add them directly to a campaign White- or Blacklist." },
  "stats.cleaner.selectedCount": { ru: "Выбрано: {count}", en: "Selected: {count}" },
  "stats.cleaner.campaign": { ru: "Кампания", en: "Campaign" },
  "stats.cleaner.selectCampaign": { ru: "Выберите кампанию", en: "Select a campaign" },
  "stats.cleaner.minimumSpend": { ru: "Расход без конверсий выше, USD", en: "Spend without conversions above, USD" },
  "stats.cleaner.selectNoConversions": { ru: "Выбрать источники", en: "Select sources" },
  "stats.cleaner.clearSelection": { ru: "Очистить", en: "Clear" },
  "stats.cleaner.addWhitelist": { ru: "Добавить в Whitelist", en: "Add to Whitelist" },
  "stats.cleaner.addBlacklist": { ru: "Добавить в Blacklist", en: "Add to Blacklist" },
  "stats.cleaner.selectVisible": { ru: "Выбрать видимые SiteID", en: "Select visible SiteIDs" },
  "stats.cleaner.selectSite": { ru: "Выбрать SiteID {site}", en: "Select SiteID {site}" },
  "stats.cleaner.noMatches": { ru: "Источники с нулём конверсий и расходом выше указанной суммы не найдены", en: "No sources with zero conversions and spend above the specified amount were found" },
  "stats.cleaner.selectCampaignError": { ru: "Выберите кампанию", en: "Select a campaign" },
  "stats.cleaner.selectSitesError": { ru: "Выберите хотя бы один SiteID", en: "Select at least one SiteID" },
  "stats.cleaner.alreadyAdded": { ru: "Все выбранные источники уже находятся в этом списке", en: "All selected sources are already in this list" },
  "stats.cleaner.inBlacklist": { ru: "В Blacklist", en: "In Blacklist" },
  "stats.cleaner.inWhitelist": { ru: "В Whitelist", en: "In Whitelist" },
  "stats.cleaner.removeFromList": { ru: "Убрать источник из списка", en: "Remove source from list" },
  "stats.cleaner.remove": { ru: "Убрать", en: "Remove" },
  "stats.cleaner.removed": { ru: "Источник {site} убран из списка кампании «{campaign}»", en: "Source {site} removed from the list of “{campaign}”" },
  "stats.cleaner.removeFailed": { ru: "Не удалось убрать источник из списка кампании", en: "Failed to remove the source from the campaign list" },
  "stats.cleaner.blacklistSaved": { ru: "{count} источников добавлено в Blacklist кампании «{campaign}»", en: "{count} sources added to the Blacklist of “{campaign}”" },
  "stats.cleaner.whitelistSaved": { ru: "{count} источников добавлено в Whitelist кампании «{campaign}»", en: "{count} sources added to the Whitelist of “{campaign}”" },
  "stats.cleaner.saveFailed": { ru: "Не удалось обновить список источников кампании", en: "Failed to update the campaign source list" },
  "stats.cleaner.replaceTitle": { ru: "Заменить текущий список источников?", en: "Replace the current source list?" },
  "stats.cleaner.replaceDescription": { ru: "У кампании уже есть список источников другого типа. Чтобы не изменить его смысл случайно, при продолжении текущий список будет заменён выбранными SiteID.", en: "The campaign already has a source list of another type. To avoid changing its meaning accidentally, continuing will replace the current list with the selected SiteIDs." },
  "stats.cleaner.cancel": { ru: "Отмена", en: "Cancel" },
  "stats.cleaner.replace": { ru: "Заменить и продолжить", en: "Replace and continue" },

  // Edit Campaign
  "edit.title": { ru: "Редактирование кампании", en: "Edit campaign" },
  "edit.notFound": { ru: "Кампания не найдена", en: "Campaign not found" },
  "edit.general": { ru: "Основное", en: "General" },
  "edit.targeting": { ru: "Таргетинг и списки", en: "Targeting and lists" },
  "edit.budget": { ru: "Бюджет", en: "Budget" },
  "edit.name": { ru: "Название", en: "Name" },
  "edit.formatLabel": { ru: "Формат рекламы", en: "Ad format" },
  "edit.formatLocked": { ru: "Формат нельзя изменить после создания", en: "Format cannot be changed after creation" },
  "edit.moderationWarning": { ru: "Изменён контент кампании — после сохранения она будет отправлена на модерацию", en: "Campaign content changed — it will be sent for moderation after saving" },
  "edit.save": { ru: "Сохранить", en: "Save" },
  "edit.savedModeration": { ru: "Кампания сохранена и отправлена на модерацию", en: "Campaign saved and sent for moderation" },
  "edit.saved": { ru: "Кампания сохранена", en: "Campaign saved" },
  "edit.conversion": { ru: "Отслеживание конверсий", en: "Conversion tracking" },

  // Targeting Section
  "targeting.description": { ru: "Для каждого параметра выберите режим: Whitelist (только эти значения) или Blacklist (исключить эти значения)", en: "For each parameter choose a mode: Whitelist (only these values) or Blacklist (exclude these values)" },
  "targeting.country": { ru: "Страны", en: "Countries" },
  "targeting.deviceType": { ru: "Тип устройства", en: "Device type" },
  "targeting.os": { ru: "ОС", en: "OS" },
  "targeting.browser": { ru: "Браузер", en: "Browser" },
  "targeting.schedule": { ru: "Расписание показов", en: "Display schedule" },
  "targeting.sites": { ru: "ID сайта", en: "Site ID" },
  "targeting.ip": { ru: "IP-адреса", en: "IP addresses" },
  "targeting.language": { ru: "Язык", en: "Language" },
  "targeting.off": { ru: "Выкл", en: "Off" },
  "targeting.on": { ru: "Вкл", en: "On" },
  "targeting.freeTextPlaceholder": { ru: "Введите значение...", en: "Enter value..." },
  "targeting.autocompletePlaceholder": { ru: "Начните вводить...", en: "Start typing..." },
  "targeting.addCustom": { ru: "Добавить", en: "Add" },
  "targeting.sitesHint": { ru: "Добавляйте ID сайтов по одному или через запятую без пробелов (например: 12345,abdjhx)", en: "Add site IDs one by one or separated by commas without spaces (e.g.: 12345,abdjhx)" },
  "targeting.sitesFormatError": { ru: "Неверный формат. Используйте значения через запятую без пробелов", en: "Invalid format. Use comma-separated values without spaces" },
  "targeting.scheduleHint": { ru: "Кликните или протяните мышью для выбора часов. Кликните на день/час для выделения целого ряда/столбца", en: "Click or drag to select hours. Click a day/hour header to toggle an entire row/column" },
  "targeting.selectAll": { ru: "Все", en: "All" },
  "targeting.deselectAll": { ru: "Снять", en: "Clear" },
  "targeting.clear": { ru: "Очистить", en: "Clear" },
  "targetingImport.open": { ru: "Импортировать из кампании", en: "Import from campaign" },
  "targetingImport.title": { ru: "Перенос таргетингов", en: "Import targeting" },
  "targetingImport.description": { ru: "Выберите кампанию и группы таргетингов, которые нужно перенести.", en: "Choose a campaign and the targeting groups to import." },
  "targetingImport.source": { ru: "Кампания-источник", en: "Source campaign" },
  "targetingImport.selectCampaign": { ru: "Выберите кампанию", en: "Select a campaign" },
  "targetingImport.groups": { ru: "Что перенести", en: "Groups to import" },
  "targetingImport.selectAll": { ru: "Выбрать всё", en: "Select all" },
  "targetingImport.clear": { ru: "Снять выбор", en: "Clear selection" },
  "targetingImport.values": { ru: "{count} значений", en: "{count} values" },
  "targetingImport.empty": { ru: "В этой кампании нет заполненных таргетингов.", en: "This campaign has no populated targeting groups." },
  "targetingImport.replaceWarning": { ru: "Выбранные группы полностью заменят текущие значения вместе с режимом White/Black. Изменения отправятся на сервер только после сохранения кампании.", en: "Selected groups will replace the current values together with their White/Black mode. Changes are sent to the server only when the campaign is saved." },
  "targetingImport.import": { ru: "Перенести таргетинги", en: "Import targeting" },
  "targetingImport.success": { ru: "Перенесено групп: {groups}, значений: {values}", en: "Imported groups: {groups}, values: {values}" },
  "targeting.scheduleRequired": { ru: "Выберите хотя бы один активный час в расписании", en: "Select at least one active hour in the schedule" },
  "targeting.ipHint": { ru: "Введите IPv4 адреса через запятую", en: "Enter IPv4 addresses, comma-separated" },
  "targeting.ipFormatError": { ru: "Неверный формат IP. Допускаются только IPv4 адреса", en: "Invalid IP format. Only IPv4 addresses are allowed" },

  // Days of week
  "day.monday": { ru: "Понедельник", en: "Monday" },
  "day.tuesday": { ru: "Вторник", en: "Tuesday" },
  "day.wednesday": { ru: "Среда", en: "Wednesday" },
  "day.thursday": { ru: "Четверг", en: "Thursday" },
  "day.friday": { ru: "Пятница", en: "Friday" },
  "day.saturday": { ru: "Суббота", en: "Saturday" },
  "day.sunday": { ru: "Воскресенье", en: "Sunday" },

  // Budget Section
  "budget.totalBudget": { ru: "Общий бюджет *", en: "Total budget *" },
  "budget.totalBudgetHint": { ru: "Обязательное поле. Минимум $1", en: "Required field. Minimum $1" },
  "budget.dailyBudget": { ru: "Дневной бюджет", en: "Daily budget" },
  "budget.dailyBudgetPlaceholder": { ru: "Без ограничений", en: "No limit" },
  "budget.trafficType": { ru: "Уровень фильтрации трафика *", en: "Traffic filtering level *" },
  "budget.trafficCommon": { ru: "Фильтрация на стороне партнёра + фильтрация TwinBid. Базовый сегмент: хорошие объёмы при контроле качества.", en: "Partner-side filtering + TwinBid filtering. Base segment: good volumes with quality control." },
  "budget.trafficHigh": { ru: "Жёсткие фильтры у партнёра + усиленная фильтрация TwinBid. Меньше объёмов, но минимальная вероятность фрода.", en: "Strict partner filters + enhanced TwinBid filtering. Lower volumes but minimal fraud probability." },
  "budget.trafficUltra": { ru: "Фильтры партнёра + фильтрация TwinBid + сторонние fraud-checker системы. Максимальная глубина проверки и защита от фрода.", en: "Partner filters + TwinBid filtering + third-party fraud-checker systems. Maximum verification depth and fraud protection." },
  "budget.pricingModel": { ru: "Модель оплаты *", en: "Pricing model *" },
  "budget.cpmLabel": { ru: "CPM (стоимость за 1000 показов)", en: "CPM (cost per 1000 impressions)" },
  "budget.cpcLabel": { ru: "CPC (стоимость за клик)", en: "CPC (cost per click)" },
  "budget.min": { ru: "Мин", en: "Min" },
  "budget.recommended": { ru: "Рекомендованная", en: "Recommended" },
  "budget.minimumBid": { ru: "Минимальная ставка", en: "Minimum bid" },
  "budget.minimumRecommended": { ru: "Минимально рекомендованная", en: "Minimum recommended" },
  "budget.optimalRecommended": { ru: "Оптимальная рекомендованная", en: "Optimal recommended" },
  "view.bid": { ru: "Ставка", en: "Bid" },
  "budget.belowMin": { ru: "Ставка ниже минимальной", en: "Bid is below minimum" },
  "budget.belowRec": { ru: "Ставка ниже рекомендованной — может быть мало показов", en: "Bid is below recommended — may result in few impressions" },
  "budget.aboveMax": { ru: "Максимум: ${max}", en: "Maximum: ${max}" },
  "budget.aboveMaxError": { ru: "Ставка не может превышать ${max}", en: "Bid cannot exceed ${max}" },
  "budget.startDate": { ru: "Дата начала", en: "Start date" },
  "budget.endDate": { ru: "Дата окончания", en: "End date" },
  "budget.endDateError": { ru: "Дата окончания не может быть раньше сегодняшнего дня", en: "End date cannot be earlier than today" },
  "budget.evenSpend": { ru: "Равномерное распределение бюджета", en: "Even budget distribution" },
  "budget.evenSpendTooltip": { ru: "Бюджет кампании будет равномерно распределён на весь период работы кампании, чтобы избежать преждевременного расходования средств.", en: "The campaign budget will be evenly distributed across the entire campaign period to avoid premature spending." },

  // Legacy components
  "legacy.campaigns": { ru: "Рекламные кампании", en: "Ad campaigns" },
  "legacy.createCampaign": { ru: "Создать кампанию", en: "Create campaign" },
  "legacy.campaignName": { ru: "Название", en: "Name" },
  "legacy.status": { ru: "Статус", en: "Status" },
  "legacy.format": { ru: "Формат", en: "Format" },
  "legacy.budget": { ru: "Бюджет", en: "Budget" },
  "legacy.spent": { ru: "Потрачено", en: "Spent" },
  "legacy.impressions": { ru: "Показы", en: "Impressions" },
  "legacy.clicks": { ru: "Клики", en: "Clicks" },
  "legacy.view": { ru: "Просмотр", en: "View" },
  "legacy.edit": { ru: "Редактировать", en: "Edit" },
  "legacy.pause": { ru: "Приостановить", en: "Pause" },
  "legacy.start": { ru: "Запустить", en: "Start" },
  "legacy.delete": { ru: "Удалить", en: "Delete" },
  "legacy.topUpTitle": { ru: "Пополнение баланса", en: "Top up balance" },
  "legacy.topUpDesc": { ru: "Выберите сумму и способ оплаты", en: "Choose amount and payment method" },
  "legacy.topUpAmount": { ru: "Сумма пополнения", en: "Top-up amount" },
  "legacy.otherAmount": { ru: "Другая сумма", en: "Custom amount" },
  "legacy.paymentMethod": { ru: "Способ оплаты", en: "Payment method" },
  "legacy.bankCard": { ru: "Банковская карта", en: "Bank card" },
  "legacy.invoice": { ru: "Счёт для юрлица", en: "Invoice for company" },
  "legacy.eWallet": { ru: "Электронный кошелёк", en: "E-wallet" },
  "legacy.pay": { ru: "Оплатить", en: "Pay" },
  "legacy.minAmount": { ru: "Минимальная сумма пополнения — 1 000 ₽", en: "Minimum top-up amount — 1,000 ₽" },
  "legacy.createTitle": { ru: "Создание кампании", en: "Create campaign" },
  "legacy.step": { ru: "Шаг", en: "Step" },
  "legacy.basicInfo": { ru: "Основная информация", en: "Basic information" },
  "legacy.targeting": { ru: "Таргетинг", en: "Targeting" },
  "legacy.budgetSchedule": { ru: "Бюджет и расписание", en: "Budget and schedule" },
  "legacy.campaignNameLabel": { ru: "Название кампании", en: "Campaign name" },
  "legacy.campaignNamePlaceholder": { ru: "Например: Летняя распродажа", en: "E.g.: Summer sale" },
  "legacy.adFormat": { ru: "Формат рекламы", en: "Ad format" },
  "legacy.selectFormat": { ru: "Выберите формат", en: "Select format" },
  "legacy.descLabel": { ru: "Описание (опционально)", en: "Description (optional)" },
  "legacy.descPlaceholder": { ru: "Опишите цели кампании...", en: "Describe campaign goals..." },
  "legacy.geography": { ru: "География", en: "Geography" },
  "legacy.selectRegion": { ru: "Выберите регион", en: "Select region" },
  "legacy.audienceAge": { ru: "Возраст аудитории", en: "Audience age" },
  "legacy.from": { ru: "От", en: "From" },
  "legacy.to": { ru: "До", en: "To" },
  "legacy.interests": { ru: "Интересы", en: "Interests" },
  "legacy.selectCategories": { ru: "Выберите категории", en: "Select categories" },
  "legacy.dailyBudget": { ru: "Дневной бюджет", en: "Daily budget" },
  "legacy.dailyMin": { ru: "Минимум 1 000 ₽ в день", en: "Minimum 1,000 ₽ per day" },
  "legacy.totalBudgetOptional": { ru: "Общий бюджет (опционально)", en: "Total budget (optional)" },
  "legacy.noLimit": { ru: "Без ограничений", en: "No limit" },
  "legacy.startDate": { ru: "Дата начала", en: "Start date" },
  "legacy.endDate": { ru: "Дата окончания", en: "End date" },
  "legacy.back": { ru: "Назад", en: "Back" },
  "legacy.next": { ru: "Далее", en: "Next" },
  "legacy.createBtn": { ru: "Создать кампанию", en: "Create campaign" },

  // NotFound
  "notFound.title": { ru: "404", en: "404" },
  "notFound.message": { ru: "Страница не найдена", en: "Page not found" },
  "notFound.back": { ru: "Вернуться на главную", en: "Return to Home" },


  // Vertical
  "create.vertical": { ru: "Вертикаль", en: "Vertical" },

  // Cashback
  "cashback.title": { ru: "Система кэшбэка", en: "Cashback system" },
  "cashback.subtitle": { ru: "Получайте возврат бюджета за объём трат — чем больше тратите, тем больше экономите", en: "Get budget returns based on spend volume — the more you spend, the more you save" },
  "cashback.perWeek": { ru: "в неделю", en: "per week" },
  "cashback.from": { ru: "от", en: "from" },

  // Budget date picker
  "budget.selectDate": { ru: "Выберите дату", en: "Select date" },

  // Edit campaign errors
  "edit.errorBudgetMin": { ru: "Бюджет кампании должен быть не менее $1", en: "Campaign budget must be at least $1" },
  "edit.restartedActive": { ru: "Кампания перезапущена", en: "Campaign restarted" },

  // Payment
  "balance.paymentMethod": { ru: "Способ оплаты", en: "Payment method" },

  // Settings - campaign budget alert
  "settings.campaignBudgetAlert": { ru: "Бюджет кампании", en: "Campaign budget" },
  "settings.campaignBudgetAlertDesc": { ru: "Уведомление при остатке менее 10% бюджета кампании", en: "Notification when less than 10% of campaign budget remains" },

  // Budget notification
  "notif.campaignBudgetLow": { ru: "Бюджет кампании заканчивается", en: "Campaign budget running low" },
  "notif.budgetRemaining": { ru: "бюджета осталось", en: "budget remaining" },

  // Server error translations (shown as toast bodies)
  "balance.toast.submitError": { ru: "Ошибка пополнения", en: "Top-up error" },
  "errors.generic": { ru: "Не удалось выполнить операцию. Попробуйте позже.", en: "Something went wrong. Please try again later." },
  "errors.promoAlreadyUsed": { ru: "Вы уже использовали этот промокод.", en: "You have already used this promo code." },
  "errors.promoNotFound": { ru: "Промокод не найден.", en: "Promo code not found." },
  "errors.insufficientFunds": { ru: "Недостаточно средств.", en: "Insufficient funds." },
  "errors.unauthorized": { ru: "Сессия истекла. Войдите заново.", en: "Session expired. Please sign in again." },
  "errors.forbidden": { ru: "Действие запрещено.", en: "Action not allowed." },
  "errors.notFound": { ru: "Данные не найдены.", en: "Not found." },
  "errors.network": { ru: "Проблемы с сетью. Проверьте соединение.", en: "Network problem. Please check your connection." },
  "errors.rateLimit": { ru: "Слишком много запросов. Попробуйте позже.", en: "Too many requests. Please try again later." },
  "errors.invalidHash": { ru: "Неверный хэш транзакции.", en: "Invalid transaction hash." },
};




import { ES_TRANSLATIONS } from "@/lib/translations-es";
import { FR_TRANSLATIONS } from "@/lib/translations-fr";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    try {
      const stored = localStorage.getItem("twinbid_lang");
      if (stored === "en" || stored === "ru" || stored === "es" || stored === "fr") return stored;
    } catch {
      // localStorage can be unavailable in privacy-restricted browser contexts.
    }
    return "ru";
  });

  const handleSetLang = useCallback((newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("twinbid_lang", newLang);
  }, []);

  const t = useCallback((key: string): string => {
    if (lang === "es") {
      const es = ES_TRANSLATIONS[key];
      if (es !== undefined) return es;
    }
    if (lang === "fr") {
      const fr = FR_TRANSLATIONS[key];
      if (fr !== undefined) return fr;
    }
    const entry = translations[key];
    if (!entry) return key;
    if (lang === "ru") return entry.ru || entry.en || key;
    return entry.en || entry.ru || key;
  }, [lang]);

  useEffect(() => {
    setErrorTranslator((raw) => translateServerError(raw, t));
    return () => setErrorTranslator(null);
  }, [t]);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
