// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/dspRouter.proto

package dspRouterGrpc

import (
	ortb_V2_5 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DspRouterRequest_V2_5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest  `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	GlobalId      string                 `protobuf:"bytes,2,opt,name=globalId,proto3" json:"globalId,omitempty"`
	SspDomain     string                 `protobuf:"bytes,3,opt,name=ssp_domain,json=sspDomain,proto3" json:"ssp_domain,omitempty"`
	Logged        bool                   `protobuf:"varint,4,opt,name=logged,proto3" json:"logged,omitempty"`
	Typic         string                 `protobuf:"bytes,5,opt,name=typic,proto3" json:"typic,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspRouterRequest_V2_5) Reset() {
	*x = DspRouterRequest_V2_5{}
	mi := &file_services_dspRouter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspRouterRequest_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspRouterRequest_V2_5) ProtoMessage() {}

func (x *DspRouterRequest_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_dspRouter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspRouterRequest_V2_5.ProtoReflect.Descriptor instead.
func (*DspRouterRequest_V2_5) Descriptor() ([]byte, []int) {
	return file_services_dspRouter_proto_rawDescGZIP(), []int{0}
}

func (x *DspRouterRequest_V2_5) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *DspRouterRequest_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

func (x *DspRouterRequest_V2_5) GetSspDomain() string {
	if x != nil {
		return x.SspDomain
	}
	return ""
}

func (x *DspRouterRequest_V2_5) GetLogged() bool {
	if x != nil {
		return x.Logged
	}
	return false
}

func (x *DspRouterRequest_V2_5) GetTypic() string {
	if x != nil {
		return x.Typic
	}
	return ""
}

func (x *DspRouterRequest_V2_5) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type DspRouterResponse_V2_5 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest             `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	BidResponses  map[string]*ortb_V2_5.BidResponse `protobuf:"bytes,2,rep,name=bidResponses,proto3" json:"bidResponses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GlobalId      string                            `protobuf:"bytes,3,opt,name=globalId,proto3" json:"globalId,omitempty"`
	SspDomain     string                            `protobuf:"bytes,4,opt,name=ssp_domain,json=sspDomain,proto3" json:"ssp_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspRouterResponse_V2_5) Reset() {
	*x = DspRouterResponse_V2_5{}
	mi := &file_services_dspRouter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspRouterResponse_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspRouterResponse_V2_5) ProtoMessage() {}

func (x *DspRouterResponse_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_dspRouter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspRouterResponse_V2_5.ProtoReflect.Descriptor instead.
func (*DspRouterResponse_V2_5) Descriptor() ([]byte, []int) {
	return file_services_dspRouter_proto_rawDescGZIP(), []int{1}
}

func (x *DspRouterResponse_V2_5) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *DspRouterResponse_V2_5) GetBidResponses() map[string]*ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponses
	}
	return nil
}

func (x *DspRouterResponse_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

func (x *DspRouterResponse_V2_5) GetSspDomain() string {
	if x != nil {
		return x.SspDomain
	}
	return ""
}

var File_services_dspRouter_proto protoreflect.FileDescriptor

const file_services_dspRouter_proto_rawDesc = "" +
	"\n" +
	"\x18services/dspRouter.proto\x12\tdspRouter\x1a\x1atypes/ortb_V2_5/ortb.proto\"\xcf\x01\n" +
	"\x15DspRouterRequest_V2_5\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_5.BidRequestR\n" +
	"bidRequest\x12\x1a\n" +
	"\bglobalId\x18\x02 \x01(\tR\bglobalId\x12\x1d\n" +
	"\n" +
	"ssp_domain\x18\x03 \x01(\tR\tsspDomain\x12\x16\n" +
	"\x06logged\x18\x04 \x01(\bR\x06logged\x12\x14\n" +
	"\x05typic\x18\x05 \x01(\tR\x05typic\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"\xbc\x02\n" +
	"\x16DspRouterResponse_V2_5\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_5.BidRequestR\n" +
	"bidRequest\x12W\n" +
	"\fbidResponses\x18\x02 \x03(\v23.dspRouter.DspRouterResponse_V2_5.BidResponsesEntryR\fbidResponses\x12\x1a\n" +
	"\bglobalId\x18\x03 \x01(\tR\bglobalId\x12\x1d\n" +
	"\n" +
	"ssp_domain\x18\x04 \x01(\tR\tsspDomain\x1aW\n" +
	"\x11BidResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.ortb_V2_5.BidResponseR\x05value:\x028\x012g\n" +
	"\x10DspRouterService\x12S\n" +
	"\fGetBids_V2_5\x12 .dspRouter.DspRouterRequest_V2_5\x1a!.dspRouter.DspRouterResponse_V2_5B_Z]gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/dspRouter;dspRouterGrpcb\x06proto3"

var (
	file_services_dspRouter_proto_rawDescOnce sync.Once
	file_services_dspRouter_proto_rawDescData []byte
)

func file_services_dspRouter_proto_rawDescGZIP() []byte {
	file_services_dspRouter_proto_rawDescOnce.Do(func() {
		file_services_dspRouter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_dspRouter_proto_rawDesc), len(file_services_dspRouter_proto_rawDesc)))
	})
	return file_services_dspRouter_proto_rawDescData
}

var file_services_dspRouter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_dspRouter_proto_goTypes = []any{
	(*DspRouterRequest_V2_5)(nil),  // 0: dspRouter.DspRouterRequest_V2_5
	(*DspRouterResponse_V2_5)(nil), // 1: dspRouter.DspRouterResponse_V2_5
	nil,                            // 2: dspRouter.DspRouterResponse_V2_5.BidResponsesEntry
	(*ortb_V2_5.BidRequest)(nil),   // 3: ortb_V2_5.BidRequest
	(*ortb_V2_5.BidResponse)(nil),  // 4: ortb_V2_5.BidResponse
}
var file_services_dspRouter_proto_depIdxs = []int32{
	3, // 0: dspRouter.DspRouterRequest_V2_5.bidRequest:type_name -> ortb_V2_5.BidRequest
	3, // 1: dspRouter.DspRouterResponse_V2_5.bidRequest:type_name -> ortb_V2_5.BidRequest
	2, // 2: dspRouter.DspRouterResponse_V2_5.bidResponses:type_name -> dspRouter.DspRouterResponse_V2_5.BidResponsesEntry
	4, // 3: dspRouter.DspRouterResponse_V2_5.BidResponsesEntry.value:type_name -> ortb_V2_5.BidResponse
	0, // 4: dspRouter.DspRouterService.GetBids_V2_5:input_type -> dspRouter.DspRouterRequest_V2_5
	1, // 5: dspRouter.DspRouterService.GetBids_V2_5:output_type -> dspRouter.DspRouterResponse_V2_5
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_dspRouter_proto_init() }
func file_services_dspRouter_proto_init() {
	if File_services_dspRouter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_dspRouter_proto_rawDesc), len(file_services_dspRouter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_dspRouter_proto_goTypes,
		DependencyIndexes: file_services_dspRouter_proto_depIdxs,
		MessageInfos:      file_services_dspRouter_proto_msgTypes,
	}.Build()
	File_services_dspRouter_proto = out.File
	file_services_dspRouter_proto_goTypes = nil
	file_services_dspRouter_proto_depIdxs = nil
}
