package constants

const (
	NEGATIVE_BIDFLOOR = -1
	ZERO_BIDFLOOR
)

const (
	UUID_COLUMN                = "UUID"
	TIMESTAMP_COLUMN           = "TIMESTAMP"
	SPP_DOMAIN_COLUMN          = "SPP_DOMAIN"
	BID_REQUEST_COLUMN         = "BID_REQUEST"
	GEO_COLUMN                 = "GEO"
	BID_RESPONSES_COLUMN       = "BID_RESPONSES"
	BID_RESPONSE_WINNER_COLUMN = "BID_RESPONSE_WINNER"
	RESULT_COLUMN              = "RESULT"
)

const (
	UNSUCCESS = "0"
	SUCCESS   = "1"
)
