// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: services/bidEngine.proto

package bidEngineGrpc

import (
	ortb_V2_5 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidEngineRequest_V2_5 struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest             `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	BidResponses  map[string]*ortb_V2_5.BidResponse `protobuf:"bytes,2,rep,name=bidResponses,proto3" json:"bidResponses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GlobalId      string                            `protobuf:"bytes,3,opt,name=globalId,proto3" json:"globalId,omitempty"`
	SspDomain     string                            `protobuf:"bytes,4,opt,name=ssp_domain,json=sspDomain,proto3" json:"ssp_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineRequest_V2_5) Reset() {
	*x = BidEngineRequest_V2_5{}
	mi := &file_services_bidEngine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineRequest_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineRequest_V2_5) ProtoMessage() {}

func (x *BidEngineRequest_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineRequest_V2_5.ProtoReflect.Descriptor instead.
func (*BidEngineRequest_V2_5) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{0}
}

func (x *BidEngineRequest_V2_5) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *BidEngineRequest_V2_5) GetBidResponses() map[string]*ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponses
	}
	return nil
}

func (x *BidEngineRequest_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

func (x *BidEngineRequest_V2_5) GetSspDomain() string {
	if x != nil {
		return x.SspDomain
	}
	return ""
}

type BidEngineResponse_V2_5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidResponse   *ortb_V2_5.BidResponse `protobuf:"bytes,1,opt,name=bidResponse,proto3" json:"bidResponse,omitempty"`
	GlobalId      string                 `protobuf:"bytes,2,opt,name=globalId,proto3" json:"globalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineResponse_V2_5) Reset() {
	*x = BidEngineResponse_V2_5{}
	mi := &file_services_bidEngine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineResponse_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineResponse_V2_5) ProtoMessage() {}

func (x *BidEngineResponse_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineResponse_V2_5.ProtoReflect.Descriptor instead.
func (*BidEngineResponse_V2_5) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{1}
}

func (x *BidEngineResponse_V2_5) GetBidResponse() *ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponse
	}
	return nil
}

func (x *BidEngineResponse_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

type SspGeoPercentsRequest_V2_5 struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Changes       map[string]*MapStringToFloat `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SspGeoPercentsRequest_V2_5) Reset() {
	*x = SspGeoPercentsRequest_V2_5{}
	mi := &file_services_bidEngine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SspGeoPercentsRequest_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SspGeoPercentsRequest_V2_5) ProtoMessage() {}

func (x *SspGeoPercentsRequest_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SspGeoPercentsRequest_V2_5.ProtoReflect.Descriptor instead.
func (*SspGeoPercentsRequest_V2_5) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{2}
}

func (x *SspGeoPercentsRequest_V2_5) GetChanges() map[string]*MapStringToFloat {
	if x != nil {
		return x.Changes
	}
	return nil
}

type MapStringToFloat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]float32     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapStringToFloat) Reset() {
	*x = MapStringToFloat{}
	mi := &file_services_bidEngine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapStringToFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStringToFloat) ProtoMessage() {}

func (x *MapStringToFloat) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStringToFloat.ProtoReflect.Descriptor instead.
func (*MapStringToFloat) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{3}
}

func (x *MapStringToFloat) GetValues() map[string]float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_services_bidEngine_proto protoreflect.FileDescriptor

const file_services_bidEngine_proto_rawDesc = "" +
	"\n" +
	"\x18services/bidEngine.proto\x12\tbidEngine\x1a\x1atypes/ortb_V2_5/ortb.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xba\x02\n" +
	"\x15BidEngineRequest_V2_5\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_5.BidRequestR\n" +
	"bidRequest\x12V\n" +
	"\fbidResponses\x18\x02 \x03(\v22.bidEngine.BidEngineRequest_V2_5.BidResponsesEntryR\fbidResponses\x12\x1a\n" +
	"\bglobalId\x18\x03 \x01(\tR\bglobalId\x12\x1d\n" +
	"\n" +
	"ssp_domain\x18\x04 \x01(\tR\tsspDomain\x1aW\n" +
	"\x11BidResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.ortb_V2_5.BidResponseR\x05value:\x028\x01\"n\n" +
	"\x16BidEngineResponse_V2_5\x128\n" +
	"\vbidResponse\x18\x01 \x01(\v2\x16.ortb_V2_5.BidResponseR\vbidResponse\x12\x1a\n" +
	"\bglobalId\x18\x02 \x01(\tR\bglobalId\"\xc3\x01\n" +
	"\x1aSspGeoPercentsRequest_V2_5\x12L\n" +
	"\achanges\x18\x01 \x03(\v22.bidEngine.SspGeoPercentsRequest_V2_5.ChangesEntryR\achanges\x1aW\n" +
	"\fChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.bidEngine.MapStringToFloatR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10MapStringToFloat\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.bidEngine.MapStringToFloat.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012\xc8\x01\n" +
	"\x10BidEngineService\x12Z\n" +
	"\x11getWinnerBid_V2_5\x12 .bidEngine.BidEngineRequest_V2_5\x1a!.bidEngine.BidEngineResponse_V2_5\"\x00\x12X\n" +
	"\x17ChangeSspGeoPercentsMap\x12%.bidEngine.SspGeoPercentsRequest_V2_5\x1a\x16.google.protobuf.EmptyB_Z]gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/bidEngine;bidEngineGrpcb\x06proto3"

var (
	file_services_bidEngine_proto_rawDescOnce sync.Once
	file_services_bidEngine_proto_rawDescData []byte
)

func file_services_bidEngine_proto_rawDescGZIP() []byte {
	file_services_bidEngine_proto_rawDescOnce.Do(func() {
		file_services_bidEngine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_bidEngine_proto_rawDesc), len(file_services_bidEngine_proto_rawDesc)))
	})
	return file_services_bidEngine_proto_rawDescData
}

var file_services_bidEngine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_bidEngine_proto_goTypes = []any{
	(*BidEngineRequest_V2_5)(nil),      // 0: bidEngine.BidEngineRequest_V2_5
	(*BidEngineResponse_V2_5)(nil),     // 1: bidEngine.BidEngineResponse_V2_5
	(*SspGeoPercentsRequest_V2_5)(nil), // 2: bidEngine.SspGeoPercentsRequest_V2_5
	(*MapStringToFloat)(nil),           // 3: bidEngine.MapStringToFloat
	nil,                                // 4: bidEngine.BidEngineRequest_V2_5.BidResponsesEntry
	nil,                                // 5: bidEngine.SspGeoPercentsRequest_V2_5.ChangesEntry
	nil,                                // 6: bidEngine.MapStringToFloat.ValuesEntry
	(*ortb_V2_5.BidRequest)(nil),       // 7: ortb_V2_5.BidRequest
	(*ortb_V2_5.BidResponse)(nil),      // 8: ortb_V2_5.BidResponse
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_services_bidEngine_proto_depIdxs = []int32{
	7, // 0: bidEngine.BidEngineRequest_V2_5.bidRequest:type_name -> ortb_V2_5.BidRequest
	4, // 1: bidEngine.BidEngineRequest_V2_5.bidResponses:type_name -> bidEngine.BidEngineRequest_V2_5.BidResponsesEntry
	8, // 2: bidEngine.BidEngineResponse_V2_5.bidResponse:type_name -> ortb_V2_5.BidResponse
	5, // 3: bidEngine.SspGeoPercentsRequest_V2_5.changes:type_name -> bidEngine.SspGeoPercentsRequest_V2_5.ChangesEntry
	6, // 4: bidEngine.MapStringToFloat.values:type_name -> bidEngine.MapStringToFloat.ValuesEntry
	8, // 5: bidEngine.BidEngineRequest_V2_5.BidResponsesEntry.value:type_name -> ortb_V2_5.BidResponse
	3, // 6: bidEngine.SspGeoPercentsRequest_V2_5.ChangesEntry.value:type_name -> bidEngine.MapStringToFloat
	0, // 7: bidEngine.BidEngineService.getWinnerBid_V2_5:input_type -> bidEngine.BidEngineRequest_V2_5
	2, // 8: bidEngine.BidEngineService.ChangeSspGeoPercentsMap:input_type -> bidEngine.SspGeoPercentsRequest_V2_5
	1, // 9: bidEngine.BidEngineService.getWinnerBid_V2_5:output_type -> bidEngine.BidEngineResponse_V2_5
	9, // 10: bidEngine.BidEngineService.ChangeSspGeoPercentsMap:output_type -> google.protobuf.Empty
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_services_bidEngine_proto_init() }
func file_services_bidEngine_proto_init() {
	if File_services_bidEngine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_bidEngine_proto_rawDesc), len(file_services_bidEngine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_bidEngine_proto_goTypes,
		DependencyIndexes: file_services_bidEngine_proto_depIdxs,
		MessageInfos:      file_services_bidEngine_proto_msgTypes,
	}.Build()
	File_services_bidEngine_proto = out.File
	file_services_bidEngine_proto_goTypes = nil
	file_services_bidEngine_proto_depIdxs = nil
}
