// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: services/bidEngine.proto

package bidEngineGrpc

import (
	ortb_V2_4 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_4"
	ortb_V2_5 "gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/types/ortb_V2_5"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidEngineRequest_V2_4 struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BidRequest    *ortb_V2_4.BidRequest    `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	BidResponses  []*ortb_V2_4.BidResponse `protobuf:"bytes,2,rep,name=bidResponses,proto3" json:"bidResponses,omitempty"`
	GlobalId      string                   `protobuf:"bytes,3,opt,name=globalId,proto3" json:"globalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineRequest_V2_4) Reset() {
	*x = BidEngineRequest_V2_4{}
	mi := &file_services_bidEngine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineRequest_V2_4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineRequest_V2_4) ProtoMessage() {}

func (x *BidEngineRequest_V2_4) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineRequest_V2_4.ProtoReflect.Descriptor instead.
func (*BidEngineRequest_V2_4) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{0}
}

func (x *BidEngineRequest_V2_4) GetBidRequest() *ortb_V2_4.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *BidEngineRequest_V2_4) GetBidResponses() []*ortb_V2_4.BidResponse {
	if x != nil {
		return x.BidResponses
	}
	return nil
}

func (x *BidEngineRequest_V2_4) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

type BidEngineResponse_V2_4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidResponse   *ortb_V2_4.BidResponse `protobuf:"bytes,1,opt,name=bidResponse,proto3" json:"bidResponse,omitempty"`
	GlobalId      string                 `protobuf:"bytes,2,opt,name=globalId,proto3" json:"globalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineResponse_V2_4) Reset() {
	*x = BidEngineResponse_V2_4{}
	mi := &file_services_bidEngine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineResponse_V2_4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineResponse_V2_4) ProtoMessage() {}

func (x *BidEngineResponse_V2_4) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineResponse_V2_4.ProtoReflect.Descriptor instead.
func (*BidEngineResponse_V2_4) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{1}
}

func (x *BidEngineResponse_V2_4) GetBidResponse() *ortb_V2_4.BidResponse {
	if x != nil {
		return x.BidResponse
	}
	return nil
}

func (x *BidEngineResponse_V2_4) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

type BidEngineRequest_V2_5 struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BidRequest    *ortb_V2_5.BidRequest    `protobuf:"bytes,1,opt,name=bidRequest,proto3" json:"bidRequest,omitempty"`
	BidResponses  []*ortb_V2_5.BidResponse `protobuf:"bytes,2,rep,name=bidResponses,proto3" json:"bidResponses,omitempty"`
	GlobalId      string                   `protobuf:"bytes,3,opt,name=globalId,proto3" json:"globalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineRequest_V2_5) Reset() {
	*x = BidEngineRequest_V2_5{}
	mi := &file_services_bidEngine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineRequest_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineRequest_V2_5) ProtoMessage() {}

func (x *BidEngineRequest_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineRequest_V2_5.ProtoReflect.Descriptor instead.
func (*BidEngineRequest_V2_5) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{2}
}

func (x *BidEngineRequest_V2_5) GetBidRequest() *ortb_V2_5.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *BidEngineRequest_V2_5) GetBidResponses() []*ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponses
	}
	return nil
}

func (x *BidEngineRequest_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

type BidEngineResponse_V2_5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidResponse   *ortb_V2_5.BidResponse `protobuf:"bytes,1,opt,name=bidResponse,proto3" json:"bidResponse,omitempty"`
	GlobalId      string                 `protobuf:"bytes,2,opt,name=globalId,proto3" json:"globalId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidEngineResponse_V2_5) Reset() {
	*x = BidEngineResponse_V2_5{}
	mi := &file_services_bidEngine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidEngineResponse_V2_5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidEngineResponse_V2_5) ProtoMessage() {}

func (x *BidEngineResponse_V2_5) ProtoReflect() protoreflect.Message {
	mi := &file_services_bidEngine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidEngineResponse_V2_5.ProtoReflect.Descriptor instead.
func (*BidEngineResponse_V2_5) Descriptor() ([]byte, []int) {
	return file_services_bidEngine_proto_rawDescGZIP(), []int{3}
}

func (x *BidEngineResponse_V2_5) GetBidResponse() *ortb_V2_5.BidResponse {
	if x != nil {
		return x.BidResponse
	}
	return nil
}

func (x *BidEngineResponse_V2_5) GetGlobalId() string {
	if x != nil {
		return x.GlobalId
	}
	return ""
}

var File_services_bidEngine_proto protoreflect.FileDescriptor

const file_services_bidEngine_proto_rawDesc = "" +
	"\n" +
	"\x18services/bidEngine.proto\x12\tbidEngine\x1a\x1atypes/ortb_V2_4/ortb.proto\x1a\x1atypes/ortb_V2_5/ortb.proto\"\xa6\x01\n" +
	"\x15BidEngineRequest_V2_4\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_4.BidRequestR\n" +
	"bidRequest\x12:\n" +
	"\fbidResponses\x18\x02 \x03(\v2\x16.ortb_V2_4.BidResponseR\fbidResponses\x12\x1a\n" +
	"\bglobalId\x18\x03 \x01(\tR\bglobalId\"n\n" +
	"\x16BidEngineResponse_V2_4\x128\n" +
	"\vbidResponse\x18\x01 \x01(\v2\x16.ortb_V2_4.BidResponseR\vbidResponse\x12\x1a\n" +
	"\bglobalId\x18\x02 \x01(\tR\bglobalId\"\xa6\x01\n" +
	"\x15BidEngineRequest_V2_5\x125\n" +
	"\n" +
	"bidRequest\x18\x01 \x01(\v2\x15.ortb_V2_5.BidRequestR\n" +
	"bidRequest\x12:\n" +
	"\fbidResponses\x18\x02 \x03(\v2\x16.ortb_V2_5.BidResponseR\fbidResponses\x12\x1a\n" +
	"\bglobalId\x18\x03 \x01(\tR\bglobalId\"n\n" +
	"\x16BidEngineResponse_V2_5\x128\n" +
	"\vbidResponse\x18\x01 \x01(\v2\x16.ortb_V2_5.BidResponseR\vbidResponse\x12\x1a\n" +
	"\bglobalId\x18\x02 \x01(\tR\bglobalId2\xca\x01\n" +
	"\x10BidEngineService\x12Z\n" +
	"\x11getWinnerBid_V2_4\x12 .bidEngine.BidEngineRequest_V2_4\x1a!.bidEngine.BidEngineResponse_V2_4\"\x00\x12Z\n" +
	"\x11getWinnerBid_V2_5\x12 .bidEngine.BidEngineRequest_V2_5\x1a!.bidEngine.BidEngineResponse_V2_5\"\x00B_Z]gitlab.com/twinbid-exchange/RTB-exchange/internal/grpc/proto/services/bidEngine;bidEngineGrpcb\x06proto3"

var (
	file_services_bidEngine_proto_rawDescOnce sync.Once
	file_services_bidEngine_proto_rawDescData []byte
)

func file_services_bidEngine_proto_rawDescGZIP() []byte {
	file_services_bidEngine_proto_rawDescOnce.Do(func() {
		file_services_bidEngine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_bidEngine_proto_rawDesc), len(file_services_bidEngine_proto_rawDesc)))
	})
	return file_services_bidEngine_proto_rawDescData
}

var file_services_bidEngine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_bidEngine_proto_goTypes = []any{
	(*BidEngineRequest_V2_4)(nil),  // 0: bidEngine.BidEngineRequest_V2_4
	(*BidEngineResponse_V2_4)(nil), // 1: bidEngine.BidEngineResponse_V2_4
	(*BidEngineRequest_V2_5)(nil),  // 2: bidEngine.BidEngineRequest_V2_5
	(*BidEngineResponse_V2_5)(nil), // 3: bidEngine.BidEngineResponse_V2_5
	(*ortb_V2_4.BidRequest)(nil),   // 4: ortb_V2_4.BidRequest
	(*ortb_V2_4.BidResponse)(nil),  // 5: ortb_V2_4.BidResponse
	(*ortb_V2_5.BidRequest)(nil),   // 6: ortb_V2_5.BidRequest
	(*ortb_V2_5.BidResponse)(nil),  // 7: ortb_V2_5.BidResponse
}
var file_services_bidEngine_proto_depIdxs = []int32{
	4, // 0: bidEngine.BidEngineRequest_V2_4.bidRequest:type_name -> ortb_V2_4.BidRequest
	5, // 1: bidEngine.BidEngineRequest_V2_4.bidResponses:type_name -> ortb_V2_4.BidResponse
	5, // 2: bidEngine.BidEngineResponse_V2_4.bidResponse:type_name -> ortb_V2_4.BidResponse
	6, // 3: bidEngine.BidEngineRequest_V2_5.bidRequest:type_name -> ortb_V2_5.BidRequest
	7, // 4: bidEngine.BidEngineRequest_V2_5.bidResponses:type_name -> ortb_V2_5.BidResponse
	7, // 5: bidEngine.BidEngineResponse_V2_5.bidResponse:type_name -> ortb_V2_5.BidResponse
	0, // 6: bidEngine.BidEngineService.getWinnerBid_V2_4:input_type -> bidEngine.BidEngineRequest_V2_4
	2, // 7: bidEngine.BidEngineService.getWinnerBid_V2_5:input_type -> bidEngine.BidEngineRequest_V2_5
	1, // 8: bidEngine.BidEngineService.getWinnerBid_V2_4:output_type -> bidEngine.BidEngineResponse_V2_4
	3, // 9: bidEngine.BidEngineService.getWinnerBid_V2_5:output_type -> bidEngine.BidEngineResponse_V2_5
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_services_bidEngine_proto_init() }
func file_services_bidEngine_proto_init() {
	if File_services_bidEngine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_bidEngine_proto_rawDesc), len(file_services_bidEngine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_bidEngine_proto_goTypes,
		DependencyIndexes: file_services_bidEngine_proto_depIdxs,
		MessageInfos:      file_services_bidEngine_proto_msgTypes,
	}.Build()
	File_services_bidEngine_proto = out.File
	file_services_bidEngine_proto_goTypes = nil
	file_services_bidEngine_proto_depIdxs = nil
}
